/**
 * 트랙별 30일 큐레이션 매트릭스 — 9개 트랙 × 30일 = 270개 콘텐츠 슬롯
 *
 * 자동 생성 (scripts/gen_tracks.py). 수동 편집 시 각 트랙의 days[] 30개,
 * VIDEO_POOLS의 검증된 영상 ID만 사용하세요. 영상은 admin override
 * (mind_track_daily_content_overrides) 로 즉시 교체 가능합니다.
 */

import type {
  MindTrackDailyContent,
} from './mindTrackDailyContent';
import type { MindTrackFocusId } from './mindTrackFocusTracks';

type VideoPick = MindTrackDailyContent['video'];

const VIDEO_POOLS: Record<MindTrackFocusId, VideoPick[]> = {
  sleep: [
    { videoId: "c9W414XrdF0", title: "밤 명상 — 잠들기 전 하루를 마무리 하는 고요한 시간", channel: "명상하는그녀_내안의별", durationLabel: "10분", reason: '' },
    { videoId: "inxAScz0PTM", title: "누워서 하는 10분 명상 — 호흡명상 가이드", channel: "에일린 mind yoga", durationLabel: "10분", reason: '' },
    { videoId: "NsVVO9hnCJ4", title: "완벽한 피로회복 효과 이완명상", channel: "에일린 mind yoga", durationLabel: "15분", reason: '' },
    { videoId: "ZcEBlA-9r9k", title: "마음이 편안해지는 10분 명상 가이드", channel: "에일린 mind yoga", durationLabel: "10분", reason: '' },
    { videoId: "dZewQEbQQM0", title: "5분 호흡명상 — 뇌를 위한 최고의 휴식법", channel: "에일린 mind yoga", durationLabel: "5분", reason: '' },
    { videoId: "yiysD0Jl2Wo", title: "명상이 필요할 때 10분 명상 가이드", channel: "에일린 mind yoga", durationLabel: "10분", reason: '' },
    { videoId: "GBBh694I1bw", title: "쉽게 배워보는 마음챙김 명상 \"바디스캔\"", channel: "한국MBSR마음챙김연구소", durationLabel: "15분", reason: '' },
  ],
  stress: [
    { videoId: "TGoAN5L_oPI", title: "5분 마음챙김 명상 — 마음을 다스리는 호흡", channel: "에일린 mind yoga", durationLabel: "5분", reason: '' },
    { videoId: "dZewQEbQQM0", title: "5분 호흡명상 — 뇌를 위한 최고의 휴식법", channel: "에일린 mind yoga", durationLabel: "5분", reason: '' },
    { videoId: "XgVjs-WeBWY", title: "불안하고 생각이 많을 때 즉시 도움되는 10분 호흡명상", channel: "마보TV", durationLabel: "10분", reason: '' },
    { videoId: "QN9v0nkmR_o", title: "박스 호흡법 따라해보세요", channel: "세바시 인생질문", durationLabel: "4분", reason: '' },
    { videoId: "NKoiz6YtlRE", title: "생각이 많아질 때 멈추는 호흡법", channel: "헤럴드TV", durationLabel: "5분", reason: '' },
    { videoId: "GQgjJUN02u4", title: "스트레스 관리 — 알아차림 명상", channel: "명상상담 Meditation TV", durationLabel: "12분", reason: '' },
    { videoId: "Lllh4HdUMvk", title: "회복탄력성 향상법 두 가지 — 김주환 교수", channel: "김주환의 내면소통", durationLabel: "12분", reason: '' },
  ],
  mood: [
    { videoId: "3hyTLOCQFTE", title: "감정 라벨링의 힘", channel: "모찌 심리학", durationLabel: "7분", reason: '' },
    { videoId: "wQfWgYCMeLw", title: "내 몸 안에서 감정 느끼고 흘려보내기 명상", channel: "마인드풀tv", durationLabel: "10분", reason: '' },
    { videoId: "YkFiiNBo6O0", title: "나를 사랑하는 연습 — 자애 명상", channel: "마보TV", durationLabel: "10분", reason: '' },
    { videoId: "TtTbhde9A3E", title: "감정을 피하지 않고 마주하는 RAIN 자기돌봄 명상", channel: "숲의그림자MindfulDay", durationLabel: "15분", reason: '' },
    { videoId: "hTSLx_wCQjU", title: "불편한 감정을 건강히 다루는 명상", channel: "숨쉬는고래", durationLabel: "12분", reason: '' },
    { videoId: "xeul9fEvo-Q", title: "7분 긍정확언 — 나는 결국 잘될 것이다", channel: "에일린 mind yoga", durationLabel: "7분", reason: '' },
    { videoId: "RptypCXGN-c", title: "매일 아침 따라 해보세요 — 10분 긍정확언", channel: "마음빛 글", durationLabel: "10분", reason: '' },
  ],
  focus: [
    { videoId: "Uuq4OME-7-M", title: "인생을 성공으로 이끄는 5초 법칙 — 멜 로빈스", channel: "잭스파이어", durationLabel: "8분", reason: '' },
    { videoId: "Bcs33wFg-KA", title: "회피형 성격 극복 방법 — 회피의 과학", channel: "장동선의 궁금한 뇌", durationLabel: "12분", reason: '' },
    { videoId: "6Qu5E3MrVH8", title: "5분 명상 — 인생을 180도 바꾸는 습관", channel: "에일린 mind yoga", durationLabel: "5분", reason: '' },
    { videoId: "LaM3-_ntnjU", title: "복잡한 생각, 5분 만에 정리하는 빼기명상", channel: "마음수련 명상", durationLabel: "5분", reason: '' },
    { videoId: "cvPS_25gRPs", title: "생각 비우기 명상", channel: "에일린 mind yoga", durationLabel: "10분", reason: '' },
    { videoId: "PIoK5ZdYk6E", title: "5분 아침명상", channel: "에일린 mind yoga", durationLabel: "5분", reason: '' },
    { videoId: "0KROAacWzEA", title: "진정한 명상은 생각을 쉬게하는 것", channel: "용수스님의렛고명상", durationLabel: "10분", reason: '' },
  ],
  relationship: [
    { videoId: "Oo43FrfVXOk", title: "거절은 다정한 경계", channel: "행복한 오늘", durationLabel: "8분", reason: '' },
    { videoId: "Tiwk1f6ZS9Y", title: "회피형 성격의 인생이 꼬이는 이유 & 극복법", channel: "희렌최널", durationLabel: "12분", reason: '' },
    { videoId: "inxAScz0PTM", title: "누워서 하는 10분 호흡명상", channel: "에일린 mind yoga", durationLabel: "10분", reason: '' },
    { videoId: "NsVVO9hnCJ4", title: "완벽한 피로회복 이완명상", channel: "에일린 mind yoga", durationLabel: "15분", reason: '' },
    { videoId: "YkFiiNBo6O0", title: "나를 사랑하는 연습 — 자애 명상", channel: "마보TV", durationLabel: "10분", reason: '' },
    { videoId: "3hyTLOCQFTE", title: "감정 라벨링의 힘", channel: "모찌 심리학", durationLabel: "7분", reason: '' },
    { videoId: "NKoiz6YtlRE", title: "생각이 많아질 때 멈추는 호흡법", channel: "헤럴드TV", durationLabel: "5분", reason: '' },
  ],
  self: [
    { videoId: "Lllh4HdUMvk", title: "회복탄력성 향상법 두 가지 — 김주환 교수", channel: "김주환의 내면소통", durationLabel: "12분", reason: '' },
    { videoId: "0KROAacWzEA", title: "진정한 명상은 생각을 쉬게하는 것", channel: "용수스님의렛고명상", durationLabel: "10분", reason: '' },
    { videoId: "LaM3-_ntnjU", title: "복잡한 생각, 5분 만에 정리하는 빼기명상", channel: "마음수련 명상", durationLabel: "5분", reason: '' },
    { videoId: "YkFiiNBo6O0", title: "나를 사랑하는 연습 — 자애 명상", channel: "마보TV", durationLabel: "10분", reason: '' },
    { videoId: "xeul9fEvo-Q", title: "7분 긍정확언", channel: "에일린 mind yoga", durationLabel: "7분", reason: '' },
    { videoId: "ZcEBlA-9r9k", title: "마음이 편안해지는 10분 명상 가이드", channel: "에일린 mind yoga", durationLabel: "10분", reason: '' },
    { videoId: "3hyTLOCQFTE", title: "감정 라벨링의 힘", channel: "모찌 심리학", durationLabel: "7분", reason: '' },
  ],
  parenting: [
    { videoId: "YkFiiNBo6O0", title: "나를 사랑하는 연습 — 자애 명상", channel: "마보TV", durationLabel: "10분", reason: '' },
    { videoId: "NsVVO9hnCJ4", title: "완벽한 피로회복 이완명상", channel: "에일린 mind yoga", durationLabel: "15분", reason: '' },
    { videoId: "hTSLx_wCQjU", title: "불편한 감정을 건강히 다루는 명상", channel: "숨쉬는고래", durationLabel: "12분", reason: '' },
    { videoId: "dZewQEbQQM0", title: "5분 호흡명상 — 뇌를 위한 휴식", channel: "에일린 mind yoga", durationLabel: "5분", reason: '' },
    { videoId: "inxAScz0PTM", title: "누워서 하는 10분 호흡명상", channel: "에일린 mind yoga", durationLabel: "10분", reason: '' },
    { videoId: "xeul9fEvo-Q", title: "7분 긍정확언", channel: "에일린 mind yoga", durationLabel: "7분", reason: '' },
    { videoId: "c9W414XrdF0", title: "밤 명상 — 잠들기 전 하루 마무리", channel: "명상하는그녀_내안의별", durationLabel: "10분", reason: '' },
  ],
  child_development: [
    { videoId: "Lllh4HdUMvk", title: "회복탄력성 — 김주환 교수", channel: "김주환의 내면소통", durationLabel: "12분", reason: '' },
    { videoId: "3hyTLOCQFTE", title: "감정 라벨링의 힘", channel: "모찌 심리학", durationLabel: "7분", reason: '' },
    { videoId: "Bcs33wFg-KA", title: "회피의 과학 — 장동선의 궁금한 뇌", channel: "장동선의 궁금한 뇌", durationLabel: "12분", reason: '' },
    { videoId: "YkFiiNBo6O0", title: "자애 명상 — 부모의 마음 자원 채우기", channel: "마보TV", durationLabel: "10분", reason: '' },
    { videoId: "dZewQEbQQM0", title: "5분 호흡명상", channel: "에일린 mind yoga", durationLabel: "5분", reason: '' },
    { videoId: "PIoK5ZdYk6E", title: "5분 아침명상", channel: "에일린 mind yoga", durationLabel: "5분", reason: '' },
    { videoId: "ZcEBlA-9r9k", title: "편안해지는 10분 명상", channel: "에일린 mind yoga", durationLabel: "10분", reason: '' },
  ],
  family_communication: [
    { videoId: "Oo43FrfVXOk", title: "거절은 다정한 경계 — 양육에 적용", channel: "행복한 오늘", durationLabel: "8분", reason: '' },
    { videoId: "3hyTLOCQFTE", title: "감정 라벨링의 힘", channel: "모찌 심리학", durationLabel: "7분", reason: '' },
    { videoId: "NKoiz6YtlRE", title: "생각이 많아질 때 멈추는 호흡법", channel: "헤럴드TV", durationLabel: "5분", reason: '' },
    { videoId: "YkFiiNBo6O0", title: "자애 명상 — 부모-아이 관계", channel: "마보TV", durationLabel: "10분", reason: '' },
    { videoId: "hTSLx_wCQjU", title: "불편한 감정을 건강히 다루는 명상", channel: "숨쉬는고래", durationLabel: "12분", reason: '' },
    { videoId: "TtTbhde9A3E", title: "RAIN 자기돌봄 명상", channel: "숲의그림자MindfulDay", durationLabel: "15분", reason: '' },
    { videoId: "xeul9fEvo-Q", title: "긍정확언 — 부모의 자기 강화", channel: "에일린 mind yoga", durationLabel: "7분", reason: '' },
  ],
};

export const ASSESSMENT_DAYS: Record<number, MindTrackDailyContent['assessment']> = {
  1: { route: "/stress-package", title: "스트레스 베이스라인 진단", desc: "오늘의 긴장도 · 회복 여력을 객관 점수로 측정", minutes: 5, why: "30일 변화 그래프의 0번째 점이 됩니다." },
  2: { route: "/depression-package", title: "마음 무게 진단", desc: "최근 2주 마음의 무게를 단계별로 짚어봐요", minutes: 6, why: "미션을 더 정확히 맞춤화하기 위해 두 번째 층을 확인합니다." },
  7: { route: "/assessment/resilience", title: "회복탄력성 1주차 진단", desc: "한 주 변화를 회복력 관점에서 측정", minutes: 7, why: "1주간 데이터를 진단 점수와 합쳐 첫 주간 인사이트가 만들어집니다." },
  10: { route: "/anxiety-package", title: "불안 결 진단", desc: "내 패턴이 가장 떨어지는 시간대를 진단으로 짚어요", minutes: 6, why: "골든타임을 정하기 전 패턴을 확인합니다." },
  14: { route: "/stress-package", title: "스트레스 진단 (2주차)", desc: "Day 1과 같은 진단을 다시 하고 변화량을 그래프로", minutes: 5, why: "시작 점수와 똑같은 측정을 해야 변화 그래프가 만들어집니다." },
  18: { route: "/anxiety-package", title: "감정 강도 진단", desc: "오늘 가장 강한 감정의 강도를 0~10으로 측정", minutes: 5, why: "감정 강도 다루기 미션의 베이스라인이 됩니다." },
  21: { route: "/assessment/resilience", title: "회복탄력성 3주차 진단", desc: "3주간의 패턴 전환이 회복력에 미친 영향 측정", minutes: 7, why: "3주차 코칭 인사이트의 핵심 데이터가 됩니다." },
  26: { route: "/relationship-package", title: "관계 패턴 진단", desc: "관계 회복의 한 걸음 전, 내 관계 패턴 측정", minutes: 7, why: "관계 회복 미션이 더 정확해지도록 패턴을 객관화합니다." },
  29: { route: "/depression-package", title: "우울감 최종 진단", desc: "Day 2와 같은 진단을 다시 — 30일 변화 그래프 완성", minutes: 6, why: "내일의 종합 리포트가 정확해지려면 마지막 측정이 필요해요." },
};

export interface DayDef {
  mission: string;
  actionTitle: string;
  actionHowTo: string;
  actionMinutes: number;
  videoReason: string;
}

export const TRACK_DAYS: Record<MindTrackFocusId, DayDef[]> = {
  sleep: [
    { mission: "취침·기상 시각 기록", actionTitle: "어젯밤 잠든·오늘 기상 시각 적기", actionHowTo: "0~1분 메모장 열기 · 1~2분 어젯밤 잠든 시각·오늘 일어난 시각·중간에 깬 횟수를 한 줄로 기록 · 2~3분 워크북 체크인에 그대로 옮겨 적기.", actionMinutes: 3, videoReason: "수면 베이스라인 직후 가장 가벼운 호흡 루틴." },
    { mission: "수면 환경 점검", actionTitle: "침실 조도·온도 1가지 손보기", actionHowTo: "0~1분 침실 조명 한 단계 낮추기 · 1~3분 실내 온도 1℃ 조정(여름 26·겨울 20 기준) · 3~4분 바뀐 환경 한 줄 기록.", actionMinutes: 4, videoReason: "취침 전 자극을 줄이는 호흡법." },
    { mission: "카페인 컷오프 시간 정하기", actionTitle: "오후 2시 카페인 컷오프 선언", actionHowTo: "0~1분 휴대폰 알람을 매일 오후 2시로 설정 · 1~2분 '오늘 마지막 카페인' 시각을 워크북에 기록 · 2~3분 가족·동료에게 한 줄 공지.", actionMinutes: 3, videoReason: "각성 신호를 누그러뜨리는 명상." },
    { mission: "스크린 타임 제한", actionTitle: "취침 60분 전 화면 끄기 알람", actionHowTo: "0~1분 평소 취침 시각 확인 · 1~2분 취침 60분 전 알람 등록 · 2~3분 알람이 울리면 휴대폰을 침실 밖에 두기로 결심 한 줄 적기.", actionMinutes: 3, videoReason: "잠들기 전 마음을 차분히 정리." },
    { mission: "취침 1시간 전 루틴 1개", actionTitle: "따뜻한 물로 손·발 30초 씻기", actionHowTo: "0~1분 물 온도(38~40℃) 맞추기 · 1~3분 손·발을 30초씩 따뜻한 물로 씻고 부드럽게 닦기 · 3~4분 직후 어깨 힘을 빼고 깊은 숨 5번.", actionMinutes: 4, videoReason: "각성된 신경을 가라앉히는 5분 호흡." },
    { mission: "호흡으로 잠들기 시도", actionTitle: "누워서 4-7-8 호흡 5세트", actionHowTo: "0~1분 침대에 똑바로 누워 눈 감기 · 1~4분 4초 들이마시고 7초 멈추고 8초 내쉬기를 5세트 · 4~5분 그대로 호흡을 자연스럽게 두기.", actionMinutes: 5, videoReason: "잠 들기 직전 누워 따라하기 좋은 가이드." },
    { mission: "1주차 수면 회고", actionTitle: "가장 잘 잔 날 1개 + 행동 메모", actionHowTo: "0~1분 지난 7일 체크인 훑어보기 · 1~3분 가장 잘 잔 날을 고르고 그날 한 행동 1가지 기록 · 3~4분 그 행동을 내일도 반복할지 ○/× 표시.", actionMinutes: 4, videoReason: "1주 흐름을 정리하는 명상." },
    { mission: "저녁 운동 강도 낮추기", actionTitle: "해 진 뒤 가벼운 산책 10분", actionHowTo: "0~1분 외투 챙기고 현관 나서기 · 1~9분 평소보다 천천히 동네 한 바퀴(심박 가볍게) · 9~10분 돌아와 어깨를 풀고 물 한 잔.", actionMinutes: 5, videoReason: "부교감 신경을 활성화하는 호흡." },
    { mission: "취침 직전 생각 비우기", actionTitle: "내일 할 일 3개 적고 노트 덮기", actionHowTo: "0~1분 종이·노트 펼치기 · 1~3분 머릿속에 떠오르는 '내일 할 일' 3개를 짧게 기록 · 3~4분 노트를 덮고 침대로 이동, 휴대폰은 보지 않기.", actionMinutes: 4, videoReason: "생각의 자동재생을 멈추는 가이드." },
    { mission: "수면 중간 깸 대처", actionTitle: "깼을 때 시계 안 보고 호흡 5세트", actionHowTo: "0~1분 눈 뜨더라도 시계·휴대폰 보지 않기 규칙 다짐 · 1~3분 누운 채 4-4-6 호흡 5세트 · 다시 잠들지 않으면 어두운 거실에서 5분 앉아 있기.", actionMinutes: 3, videoReason: "한밤중에도 적용 가능한 호흡법." },
    { mission: "아침 햇빛 받기", actionTitle: "기상 후 10분 내 햇빛 5분", actionHowTo: "0~1분 일어나자마자 커튼·창문 열기 · 1~5분 베란다·창가에서 햇빛 받으며 깊은 숨 10번 · 5~6분 물 한 잔 마시며 오늘 첫 한 줄 메모.", actionMinutes: 5, videoReason: "수면-각성 리듬을 맞춰주는 명상." },
    { mission: "취침 알람 자동화", actionTitle: "매일 같은 '잠 준비 알람' 등록", actionHowTo: "0~1분 휴대폰 시계 앱 열기 · 1~2분 매일 같은 시각의 반복 알람 1개 등록 · 2~3분 알람 이름을 '잠 준비 시작'으로 저장.", actionMinutes: 3, videoReason: "취침 직전 짧은 호흡 가이드." },
    { mission: "저녁 식사 시간 고정", actionTitle: "저녁을 평소보다 30분 일찍", actionHowTo: "0~1분 평소 저녁 시각 확인 · 1~3분 가족·메뉴 일정 30분 앞당기기 알림 보내기 · 3~4분 식사 후 가벼운 정리(설거지 5분).", actionMinutes: 4, videoReason: "위장 부담을 줄여 더 잘 자도록 돕는 명상." },
    { mission: "2주차 비교 측정", actionTitle: "Day 1과 같은 스트레스 진단 반복", actionHowTo: "0~1분 /stress-package 열기 · 1~5분 Day 1과 동일 문항 응답 · 5~6분 결과 점수를 워크북 '2주차 변화'에 기록.", actionMinutes: 6, videoReason: "중간 점검 직후 차분히 마음을 가라앉히는 호흡." },
    { mission: "효과 있던 루틴 강화", actionTitle: "효과 좋았던 수면 루틴 2개 재실행", actionHowTo: "0~1분 1~14일 체크인에서 수면 효과가 좋았던 루틴 2개 고르기 · 1~5분 그중 1개를 지금 즉시 시도 · 5~6분 다른 1개는 오늘 밤 시각으로 예약.", actionMinutes: 6, videoReason: "15일차의 정체감을 통과하는 짧은 명상." },
    { mission: "취침 전 글쓰기", actionTitle: "오늘 감사한 일 1개 한 문장", actionHowTo: "0~1분 침대 옆 노트 열기 · 1~3분 오늘 감사한 일 1개를 '누가·언제·무엇' 형식 한 문장으로 기록 · 3~4분 노트 덮고 불 끄기.", actionMinutes: 4, videoReason: "마음을 비워 잘 잠들도록 돕는 명상." },
    { mission: "주말 수면 보정", actionTitle: "주말도 평일과 같은 시각 기상", actionHowTo: "0~1분 주말 알람을 평일과 같은 시각으로 설정 · 1~2분 잠 더 자고 싶다면 낮잠 20분 이내로 제한 룰 메모 · 2~3분 가족과 룰 공유.", actionMinutes: 3, videoReason: "리듬을 깨지 않는 짧은 호흡." },
    { mission: "수면 강도 진단", actionTitle: "오늘 수면의 질 0~10 기록", actionHowTo: "0~1분 어젯밤 수면을 0~10으로 점수화 · 1~3분 그 점수의 이유를 한 줄(예: '중간에 두 번 깸') · 3~4분 워크북 체크인에 옮기기.", actionMinutes: 4, videoReason: "수면 패턴을 객관화하는 명상." },
    { mission: "자기 친절 한 줄", actionTitle: "'잘 자고 있어' 자기 칭찬 1문장", actionHowTo: "0~1분 거울 앞에 서기 · 1~2분 자신에게 '잘 자고 있어, ___'를 소리 내 말하기 · 2~3분 그 문장을 워크북에 기록.", actionMinutes: 3, videoReason: "자기 친절의 한국어 가이드." },
    { mission: "환경 1개 더 손보기", actionTitle: "베개 또는 이불 1개 점검", actionHowTo: "0~1분 베개 높이가 옆으로 누웠을 때 어깨선과 맞는지 확인 · 1~3분 안 맞으면 수건 한 장 접어 보정 · 3~5분 이불 두께가 땀나지 않을 정도인지 확인 후 조정.", actionMinutes: 5, videoReason: "이완 효과가 큰 가이드 명상." },
    { mission: "3주차 진단", actionTitle: "회복탄력성 진단 (3주차)", actionHowTo: "0~1분 /assessment/resilience 열기 · 1~6분 응답 완료 · 6~7분 점수를 1주차와 비교해 워크북에 기록.", actionMinutes: 7, videoReason: "3주차 마무리 명상." },
    { mission: "워크북 심화 1개", actionTitle: "잘 잔 날 vs 못 잔 날 차이 3줄", actionHowTo: "0~1분 노트 펼치기 · 1~5분 '잘 잔 날' 행동 3개와 '못 잔 날' 행동 3개를 양쪽에 적기 · 5~8분 차이 1가지를 다음 주 실험으로 표시.", actionMinutes: 8, videoReason: "맞춤 워크북 심화 직전 마음 비우기." },
    { mission: "코파일럿 1:1", actionTitle: "수면 주제 1개 코파일럿에 던지기", actionHowTo: "0~1분 코파일럿 열기 · 1~3분 '잠을 깊게 자려면 ___ 가 필요해요' 한 문장 입력 · 3~6분 답변 중 가장 와닿는 한 가지를 워크북에 옮겨 적기.", actionMinutes: 6, videoReason: "코파일럿 직전 차분한 명상." },
    { mission: "재발 방지 신호", actionTitle: "수면 무너질 때의 신호 1줄", actionHowTo: "0~1분 최근 못 잔 날 떠올리기 · 1~3분 '___ 신호가 오면 ___ 한다' 한 문장 작성 · 3~5분 휴대폰 메모 첫 화면에 고정.", actionMinutes: 5, videoReason: "재발 방지 알아차림 명상." },
    { mission: "핵심 루틴 고정", actionTitle: "수면 루틴 TOP 3 시각 부여", actionHowTo: "0~1분 효과 컸던 루틴 3개 선정 · 1~4분 각 루틴에 시작 시각을 부여(예: 22:00 샤워·22:30 알람·22:45 호흡) · 4~6분 휴대폰 반복 알람 3개 등록.", actionMinutes: 6, videoReason: "매일 짧게 — 데일리 명상." },
    { mission: "관계 패턴 점검", actionTitle: "수면을 방해하는 관계 1개 적기", actionHowTo: "0~1분 최근 늦게 잔 날을 떠올려 보기 · 1~4분 그날 영향을 준 사람·상황 1개 기록 · 4~6분 다음번엔 어떻게 다르게 할지 한 줄.", actionMinutes: 6, videoReason: "마음을 정렬하는 호흡 명상." },
    { mission: "거절 문장 1개", actionTitle: "늦은 약속 거절 템플릿 작성", actionHowTo: "0~1분 자주 받는 늦은 제안 1개 떠올리기 · 1~3분 '미안, 22시 이후엔 ___ 때문에 어려워. 다른 시간 어때?' 형식으로 1개 작성 · 3~4분 메모에 저장.", actionMinutes: 4, videoReason: "두려움을 내려놓는 이완명상." },
    { mission: "4주차 요약", actionTitle: "4주 동안 수면이 ___ 변했다", actionHowTo: "0~1분 1주차·4주차 수면 점수 비교 · 1~3분 변화 한 문장으로 작성 · 3~5분 변화의 핵심 행동 1개 표시.", actionMinutes: 5, videoReason: "리포트 직전 마무리 명상." },
    { mission: "최종 진단", actionTitle: "우울감 최종 진단 (Day 2 반복)", actionHowTo: "0~1분 /depression-package 열기 · 1~5분 Day 2와 동일 문항 응답 · 5~6분 결과 점수를 30일 그래프와 함께 캡처 저장.", actionMinutes: 6, videoReason: "리포트 직전 마음 정리." },
    { mission: "30일 선언문", actionTitle: "'나는 ___한 수면을 가진 사람'", actionHowTo: "0~1분 30일 변화 떠올리기 · 1~3분 '나는 ___한 수면을 가진 사람이다' 한 문장 작성 · 3~5분 거울·휴대폰 잠금화면에 적어두기.", actionMinutes: 5, videoReason: "30일을 차분히 마무리하는 명상." },
  ],
  stress: [
    { mission: "긴장 베이스라인", actionTitle: "4-4-6 호흡 5번 1세트", actionHowTo: "0~1분 의자에 등 펴고 앉기 · 1~3분 4초 들이마시고 4초 멈추고 6초 내쉬기 5번 · 마지막 30초 어깨 힘 빼고 가만히.", actionMinutes: 3, videoReason: "베이스라인 직후 가장 가벼운 진정 루틴." },
    { mission: "내 스트레스 신호 3개", actionTitle: "신체 신호 단어 3개 적기", actionHowTo: "0~1분 눈 감고 몸 훑기 · 1~3분 스트레스가 가장 잘 나타나는 부위 3개를 단어로 기록(예: 어깨·턱·속) · 3~4분 워크북에 옮기기.", actionMinutes: 4, videoReason: "몸의 긴장을 풀어주는 명상." },
    { mission: "스트레스 강도 0~10", actionTitle: "오늘 가장 강했던 순간 강도 기록", actionHowTo: "0~1분 오늘 가장 긴장됐던 순간 떠올리기 · 1~3분 '언제·무슨 일·강도(0~10)' 한 줄 기록 · 3~4분 그 순간 호흡으로 다시 4-4-6 1세트.", actionMinutes: 4, videoReason: "긴장 직후 빠른 호흡 가이드." },
    { mission: "바디스캔 1회", actionTitle: "어깨·턱 풀기 5분", actionHowTo: "0~1분 눈 감고 깊은 숨 3번 · 1~4분 머리→얼굴→어깨→가슴→배 순서로 1부위 30초 알아차림 · 4~5분 가장 긴장된 부위에 1번 더 호흡.", actionMinutes: 5, videoReason: "바디스캔 한국어 가이드." },
    { mission: "5초 마이크로 결정", actionTitle: "5분이면 끝나는 일 1개 즉시 처리", actionHowTo: "0~1분 미루던 일 중 5분이면 끝나는 1가지 고르기 · 1~5분 타이머 맞추고 멈추지 않고 처리 · 끝나면 워크북에 '오늘 처리한 1개' 기록.", actionMinutes: 5, videoReason: "행동 시작의 심리적 장벽 영상." },
    { mission: "에너지 도둑 1개", actionTitle: "줄일 한 가지 + 방법 1줄", actionHowTo: "0~1분 오늘 에너지를 가장 빼앗은 1가지 떠올리기 · 1~3분 '___ 를 ___ 만큼 줄인다' 한 줄 작성 · 3~4분 캘린더에 시각 알람 1개.", actionMinutes: 4, videoReason: "다정한 경계의 언어 영상." },
    { mission: "1주차 진단", actionTitle: "회복탄력성 진단 (1주차)", actionHowTo: "0~1분 /assessment/resilience 열기 · 1~6분 응답 완료 · 6~7분 점수를 워크북에 기록.", actionMinutes: 7, videoReason: "1주차 정리 영상." },
    { mission: "호흡 강화", actionTitle: "박스호흡 4-4-4-4 아·점·저 1세트씩", actionHowTo: "0~1분 알람 3개(09·13·19시) 등록 · 1~5분 지금 한 세트 4-4-4-4 5번 · 5~6분 알람 울릴 때마다 30초만 호흡 약속.", actionMinutes: 6, videoReason: "박스호흡 가이드." },
    { mission: "자동사고 멈추기", actionTitle: "'멈춤' 한 단어 + 4-4-6 호흡", actionHowTo: "0~1분 반복되는 부정적 생각 1개 알아차림 · 1~2분 입 밖으로 '멈춤' 소리 내기 · 2~3분 4-4-6 호흡 5번 후 다른 일로 시선 이동.", actionMinutes: 3, videoReason: "생각 비우기 명상." },
    { mission: "스트레스 패턴 진단", actionTitle: "불안 결 진단으로 패턴 객관화", actionHowTo: "0~1분 /anxiety-package 열기 · 1~5분 응답 완료 · 5~6분 가장 점수 높은 영역 1개를 워크북에 기록.", actionMinutes: 6, videoReason: "불안 호흡 가이드." },
    { mission: "최근 갈등 1장면", actionTitle: "사실 1문장으로 묘사", actionHowTo: "0~1분 최근 가장 떠오르는 갈등 1장면 떠올리기 · 1~4분 감정·해석 빼고 사실만 1문장으로 작성 · 4~5분 다시 읽고 강도 0~10 표시.", actionMinutes: 5, videoReason: "호흡으로 반응 멈추기." },
    { mission: "호흡 분산 적용", actionTitle: "아·점·저 박스호흡 1세트씩", actionHowTo: "0~1분 알람 3개 확인 · 1~5분 지금 한 세트 박스호흡 5번 · 5~6분 다음 알람 시각 메모.", actionMinutes: 6, videoReason: "박스호흡 가이드." },
    { mission: "자유 기록 5분", actionTitle: "타이머 5분 손 멈추지 않고 적기", actionHowTo: "0~1분 종이·노트 펼치고 타이머 5분 · 1~5분 머릿속에 떠오르는 단어를 손 멈추지 말고 기록(맞춤법·문장 신경X).", actionMinutes: 5, videoReason: "저널링 직전 호흡." },
    { mission: "2주차 비교", actionTitle: "스트레스 진단 반복 (2주차)", actionHowTo: "0~1분 /stress-package 열기 · 1~5분 Day 1과 동일 문항 응답 · 5~6분 변화량을 워크북 그래프에 기록.", actionMinutes: 5, videoReason: "2주차 변화 직전 호흡." },
    { mission: "루틴 TOP 3 강화", actionTitle: "효과 컸던 스트레스 루틴 3개 재실행", actionHowTo: "0~1분 1~14일 체크인에서 가장 효과 컸던 루틴 3개 선정 · 1~5분 그중 1개를 지금 시도 · 5~6분 나머지 2개의 시각을 캘린더에 등록.", actionMinutes: 6, videoReason: "15일차 통과 명상." },
    { mission: "회피 마주하기", actionTitle: "미뤄둔 일 5분만 시도", actionHowTo: "0~1분 가장 미뤄둔 일 1개 고르기 · 1~5분 타이머 5분 맞추고 시작, 5분 뒤 멈춰도 OK · 끝나면 '한 일/안 한 일' 한 줄.", actionMinutes: 5, videoReason: "회피의 과학 영상." },
    { mission: "도움 요청", actionTitle: "한 사람에게 '도와줄 수 있어?'", actionHowTo: "0~1분 가장 편한 1명 떠올리기 · 1~3분 '요즘 ___ 때문에 힘든데 ___ 좀 도와줄 수 있어?' 메시지 작성 · 3~4분 전송.", actionMinutes: 4, videoReason: "도움 요청 장벽 낮추기." },
    { mission: "감정 강도 진단", actionTitle: "오늘 가장 강한 감정 0~10", actionHowTo: "0~1분 눈 감고 지금 감정 떠올리기 · 1~3분 단어 1개와 0~10 강도 기록 · 3~5분 그 강도가 어떤 신체 신호로 나타나는지 한 줄.", actionMinutes: 5, videoReason: "강도 객관화 명상." },
    { mission: "자기 친절", actionTitle: "오늘 잘한 일 1개 자기 칭찬", actionHowTo: "0~1분 오늘 한 일 떠올리기 · 1~2분 잘한 일 1개를 구체적으로 적기 · 2~3분 '잘했어, ___' 한 문장으로 자신에게.", actionMinutes: 3, videoReason: "자애 명상." },
    { mission: "환경 1개 손보기", actionTitle: "책상·휴대폰·소파 중 1개 5분 정리", actionHowTo: "0~1분 가장 거슬리는 1곳 정하기 · 1~5분 위치 이동·알림 끄기·물건 치우기 등 5분 안에 가능한 변경 1개 실행.", actionMinutes: 5, videoReason: "긍정확언 영상." },
    { mission: "3주차 진단", actionTitle: "회복탄력성 진단 (3주차)", actionHowTo: "0~1분 /assessment/resilience 열기 · 1~6분 응답 완료 · 6~7분 1주차 점수와 비교해 변화 한 줄.", actionMinutes: 7, videoReason: "3주차 마무리 명상." },
    { mission: "워크북 심화 1개", actionTitle: "스트레스 트리거 1개 3층 분해", actionHowTo: "0~1분 가장 자주 오는 트리거 1개 선정 · 1~5분 '상황·생각·신체반응' 3층으로 분해 · 5~8분 각 층마다 대응 1개씩 적기.", actionMinutes: 8, videoReason: "마음 비우기 명상." },
    { mission: "코파일럿 1:1", actionTitle: "오늘 스트레스 주제 1개 입력", actionHowTo: "0~1분 코파일럿 열기 · 1~3분 '요즘 ___ 때문에 ___' 한 문장 입력 · 3~6분 답변 중 가장 와닿는 한 가지를 워크북에 옮기기.", actionMinutes: 6, videoReason: "코파일럿 직전 명상." },
    { mission: "재발 방지 신호", actionTitle: "스트레스 무너질 때의 신호 1줄", actionHowTo: "0~1분 최근 폭발 직전 상황 떠올리기 · 1~3분 '___ 신호가 오면 ___ 한다' 작성 · 3~5분 메모 첫 화면 고정.", actionMinutes: 5, videoReason: "알아차림 명상." },
    { mission: "핵심 루틴 고정", actionTitle: "스트레스 루틴 TOP 3 시각 부여", actionHowTo: "0~1분 효과 컸던 루틴 3개 선정 · 1~4분 각 루틴 시작 시각 부여 · 4~6분 휴대폰 반복 알람 3개 등록.", actionMinutes: 6, videoReason: "데일리 명상." },
    { mission: "관계 패턴 진단", actionTitle: "관계 패턴 진단으로 트리거 점검", actionHowTo: "0~1분 /relationship-package 열기 · 1~6분 응답 완료 · 6~7분 스트레스 유발 관계 1개를 워크북에 기록.", actionMinutes: 7, videoReason: "호흡명상." },
    { mission: "거절 문장 1개", actionTitle: "거절 템플릿 1개 미리 작성", actionHowTo: "0~1분 자주 받는 부담스러운 부탁 1개 떠올리기 · 1~3분 '고마워, 이번엔 ___ 때문에 어려워' 형식 1문장 · 3~4분 메모 저장.", actionMinutes: 4, videoReason: "이완명상." },
    { mission: "4주차 요약", actionTitle: "4주 동안 스트레스가 ___ 변했다", actionHowTo: "0~1분 1·4주차 점수 비교 · 1~3분 한 문장 요약 · 3~5분 핵심 행동 1개 표시.", actionMinutes: 5, videoReason: "마무리 명상." },
    { mission: "최종 진단", actionTitle: "우울감 최종 진단 (Day 2 반복)", actionHowTo: "0~1분 /depression-package 열기 · 1~5분 응답 완료 · 5~6분 결과를 30일 그래프와 함께 저장.", actionMinutes: 6, videoReason: "리포트 직전 정렬." },
    { mission: "30일 선언문", actionTitle: "'스트레스를 ___하는 사람'", actionHowTo: "0~1분 30일 변화 떠올리기 · 1~3분 '나는 스트레스를 ___하는 사람이다' 한 문장 작성 · 3~5분 잠금화면에 메모.", actionMinutes: 5, videoReason: "마무리 명상." },
  ],
  mood: [
    { mission: "감정 베이스라인", actionTitle: "오늘 감정 단어 3개 분리", actionHowTo: "0~1분 눈 감고 지금 감정 훑기 · 1~3분 단어 3개로 분리해 적기(예: 답답·미안·기대) · 3~4분 가장 큰 1개에 별표.", actionMinutes: 4, videoReason: "감정 라벨링의 신경과학." },
    { mission: "감정 강도 기록", actionTitle: "가장 강한 감정 0~10 강도 기록", actionHowTo: "0~1분 오늘 가장 강했던 감정 1개 떠올리기 · 1~3분 단어 + 0~10 강도 기록 · 3~4분 그 감정이 시작된 시각·상황 한 줄.", actionMinutes: 4, videoReason: "감정을 흘려보내는 명상." },
    { mission: "감정-신체 연결", actionTitle: "감정이 느껴지는 신체 위치 1줄", actionHowTo: "0~1분 가장 강한 감정 떠올리기 · 1~3분 그 감정이 몸 어디에 느껴지는지 위치+감각(예: 가슴 압박감) · 3~4분 그 부위에 손 얹고 깊은 숨 5번.", actionMinutes: 4, videoReason: "몸 안에서 감정 느끼기." },
    { mission: "자기자비 한 줄", actionTitle: "친구라면 뭐라 할까 한 문장", actionHowTo: "0~1분 오늘 자신에게 가혹했던 순간 떠올리기 · 1~2분 친한 친구가 같은 일을 겪었다면 뭐라 위로할지 1문장 · 2~3분 그 문장을 자신에게 소리 내 말하기.", actionMinutes: 3, videoReason: "자애 명상." },
    { mission: "RAIN 1회", actionTitle: "Recognize·Allow·Investigate·Nurture", actionHowTo: "0~1분 가장 불편한 감정 1개 알아차림(R) · 1~3분 막지 않고 허용(A) · 3~5분 호기심으로 살피기(I) · 5~6분 자신을 다정히 안아주기(N) 한 줄.", actionMinutes: 6, videoReason: "RAIN 명상." },
    { mission: "감정 일기 5분", actionTitle: "오늘 감정 흐름 아·점·저 1줄씩", actionHowTo: "0~1분 노트 펼치기 · 1~4분 아침/점심/저녁 감정을 단어 1개와 강도로 각 1줄 · 4~5분 가장 큰 변화 구간에 별표.", actionMinutes: 5, videoReason: "감정 흘려보내기." },
    { mission: "1주차 진단", actionTitle: "회복탄력성 진단 (1주차)", actionHowTo: "0~1분 /assessment/resilience 열기 · 1~6분 응답 완료 · 6~7분 점수를 워크북에 기록.", actionMinutes: 7, videoReason: "회복력 영상." },
    { mission: "긍정 확언 1회", actionTitle: "아침 확언 영상 따라 1회", actionHowTo: "0~1분 영상 찾기 · 1~6분 영상 따라 소리 내 확언 1회 · 6~7분 가장 와닿은 문장 한 줄 메모.", actionMinutes: 7, videoReason: "긍정확언 영상." },
    { mission: "감정 거리두기", actionTitle: "'나는 ___을 느낀다' 형식 변환", actionHowTo: "0~1분 자주 쓰는 '나는 슬프다' 같은 문장 떠올리기 · 1~2분 '나는 슬픔을 느낀다' 형식으로 바꿔 적기 3개 · 2~3분 소리 내 말해보기.", actionMinutes: 3, videoReason: "생각 비우기 명상." },
    { mission: "감정 패턴 진단", actionTitle: "불안 결 진단으로 감정 패턴 객관화", actionHowTo: "0~1분 /anxiety-package 열기 · 1~5분 응답 완료 · 5~6분 가장 높은 영역을 워크북에 기록.", actionMinutes: 6, videoReason: "호흡명상." },
    { mission: "자기 친절 편지", actionTitle: "나에게 짧은 편지 3줄", actionHowTo: "0~1분 노트 펼치기 · 1~4분 '오늘 ___한 너에게'로 시작하는 3줄 편지 · 4~5분 마지막 줄에 자신을 안아주는 한 마디.", actionMinutes: 5, videoReason: "자애 명상." },
    { mission: "감정 발산 안전한 방법", actionTitle: "글·그림·노래 중 1개 5분 발산", actionHowTo: "0~1분 도구 정하기(글·그림·노래) · 1~5분 평가 없이 5분간 자유 발산 · 끝나면 워크북에 '발산 후 강도 변화' 한 줄.", actionMinutes: 5, videoReason: "호흡으로 마음 정렬." },
    { mission: "자유 기록 5분", actionTitle: "감정 그대로 5분 자유 기록", actionHowTo: "0~1분 타이머 5분 · 1~5분 떠오르는 감정 단어를 멈추지 않고 적기 · 끝나면 가장 자주 나온 단어에 동그라미.", actionMinutes: 5, videoReason: "저널링 직전 호흡." },
    { mission: "2주차 비교", actionTitle: "스트레스 진단 반복 (2주차)", actionHowTo: "0~1분 /stress-package 열기 · 1~5분 응답 완료 · 5~6분 변화량 기록.", actionMinutes: 5, videoReason: "2주차 명상." },
    { mission: "효과있던 루틴 강화", actionTitle: "기분에 가장 효과 좋았던 루틴 3개 재실행", actionHowTo: "0~1분 1~14일 체크인에서 기분이 좋아진 루틴 3개 선정 · 1~5분 1개 지금 시도 · 5~6분 나머지 2개 캘린더에 시각 등록.", actionMinutes: 6, videoReason: "15일차 명상." },
    { mission: "부정 감정 마주하기", actionTitle: "피하던 감정 1개 이름 붙이기", actionHowTo: "0~1분 평소 피하던 감정 1개 떠올리기 · 1~3분 그 감정의 이름·강도·신체 위치 기록 · 3~5분 '나는 ___도 가지고 있다' 한 문장.", actionMinutes: 5, videoReason: "불편한 감정 명상." },
    { mission: "감사 일기", actionTitle: "오늘 감사 3개 구체적으로", actionHowTo: "0~1분 노트 펼치기 · 1~3분 '누가·무엇·왜 감사했는지' 형식으로 3개 · 3~4분 한 가지에 별표하고 그 사람에게 한 줄 감사 메시지.", actionMinutes: 4, videoReason: "긍정확언 영상." },
    { mission: "감정 강도 진단", actionTitle: "오늘 가장 강한 감정 0~10", actionHowTo: "0~1분 지금 감정 떠올리기 · 1~3분 단어 + 0~10 + 신체 위치 기록 · 3~5분 강도 줄이는 호흡 4-4-6 5번.", actionMinutes: 5, videoReason: "RAIN 명상." },
    { mission: "자기 칭찬", actionTitle: "오늘 잘한 일 1개 + 자기 칭찬", actionHowTo: "0~1분 오늘 한 일 훑기 · 1~2분 잘한 일 1개 구체적 기록 · 2~3분 '잘했어, ___' 한 문장 자기 칭찬.", actionMinutes: 3, videoReason: "자애 명상." },
    { mission: "감정 환경 점검", actionTitle: "감정 자극 1개 줄이기", actionHowTo: "0~1분 감정을 자주 흔드는 자극 1개 정하기(SNS·뉴스·특정 채팅방) · 1~3분 일일 사용시간 제한 또는 알림 끄기 · 3~5분 캘린더에 점검 시각 1개.", actionMinutes: 5, videoReason: "긍정확언." },
    { mission: "3주차 진단", actionTitle: "회복탄력성 진단 (3주차)", actionHowTo: "0~1분 /assessment/resilience 열기 · 1~6분 응답 완료 · 6~7분 1주차와 비교 한 줄.", actionMinutes: 7, videoReason: "3주 마무리 명상." },
    { mission: "워크북 심화", actionTitle: "반복 감정 1개 패턴 분석", actionHowTo: "0~1분 가장 반복되는 감정 1개 선정 · 1~5분 '상황·생각·반응' 3층 분해 · 5~8분 각 층 대응 1개씩 적기.", actionMinutes: 8, videoReason: "마음 비우기." },
    { mission: "코파일럿 1:1", actionTitle: "감정 주제 1개 코파일럿에 입력", actionHowTo: "0~1분 코파일럿 열기 · 1~3분 '요즘 ___ 감정이 자주 ___' 한 문장 입력 · 3~6분 답변 중 1개를 워크북에 옮기기.", actionMinutes: 6, videoReason: "명상." },
    { mission: "재발 방지", actionTitle: "감정 폭풍 신호 1줄", actionHowTo: "0~1분 최근 폭발 전 떠올리기 · 1~3분 '___ 신호가 오면 ___ 한다' 작성 · 3~5분 메모 고정.", actionMinutes: 5, videoReason: "알아차림 명상." },
    { mission: "핵심 루틴 고정", actionTitle: "감정 회복 루틴 TOP 3 시각 부여", actionHowTo: "0~1분 효과 컸던 루틴 3개 선정 · 1~4분 시각 부여 · 4~6분 알람 3개 등록.", actionMinutes: 6, videoReason: "데일리 명상." },
    { mission: "관계 점검", actionTitle: "감정에 영향 큰 관계 1개 적기", actionHowTo: "0~1분 최근 감정 흔든 관계 떠올리기 · 1~4분 '누가·어떤 상황·내 감정' 한 줄 · 4~6분 다음번 다르게 할 행동 1개.", actionMinutes: 6, videoReason: "호흡명상." },
    { mission: "거절 문장", actionTitle: "감정 보호 거절 1개 작성", actionHowTo: "0~1분 자주 흔들리는 부탁 1개 떠올리기 · 1~3분 '오늘은 ___ 때문에 어려워' 형식 1문장 · 3~4분 메모 저장.", actionMinutes: 4, videoReason: "이완명상." },
    { mission: "4주차 요약", actionTitle: "4주 동안 감정이 ___ 변했다", actionHowTo: "0~1분 1·4주차 감정 일기 비교 · 1~3분 변화 한 문장 · 3~5분 핵심 행동 1개 표시.", actionMinutes: 5, videoReason: "마무리 명상." },
    { mission: "최종 진단", actionTitle: "우울감 최종 진단 (Day 2 반복)", actionHowTo: "0~1분 /depression-package 열기 · 1~5분 응답 완료 · 5~6분 30일 그래프 저장.", actionMinutes: 6, videoReason: "마음 정리." },
    { mission: "30일 선언문", actionTitle: "'감정을 ___하는 사람'", actionHowTo: "0~1분 30일 변화 떠올리기 · 1~3분 '나는 감정을 ___하는 사람이다' 한 문장 · 3~5분 잠금화면 메모.", actionMinutes: 5, videoReason: "마무리 명상." },
  ],
  focus: [
    { mission: "산만함 베이스라인", actionTitle: "오늘 집중 깬 방해 요소 3개", actionHowTo: "0~1분 오늘 하루 떠올리기 · 1~3분 집중을 깬 3가지를 단어로 기록 · 3~4분 가장 자주 등장한 1개에 별표.", actionMinutes: 4, videoReason: "5초 법칙 영상." },
    { mission: "폰 사용 시간 측정", actionTitle: "스크린타임 확인 + 1줄 메모", actionHowTo: "0~1분 휴대폰 설정→스크린타임 열기 · 1~2분 어제 총 사용시간 + 가장 많이 쓴 앱 1개 기록 · 2~3분 줄일 앱 1개에 표시.", actionMinutes: 3, videoReason: "빼기 명상." },
    { mission: "알림 끄기 1개", actionTitle: "가장 산만한 앱 알림 1개 끄기", actionHowTo: "0~1분 가장 자주 울리는 앱 1개 정하기 · 1~2분 설정→알림→해당 앱 알림 OFF · 2~3분 워크북에 '오늘 끈 알림' 한 줄.", actionMinutes: 3, videoReason: "생각 비우기." },
    { mission: "딥워크 25분", actionTitle: "타이머 25분 한 가지만", actionHowTo: "0~1분 한 가지 작업 정하고 휴대폰 다른 방으로 · 1~26분 타이머 25분 그 한 가지만 · 26~27분 끝나고 한 줄 회고.", actionMinutes: 6, videoReason: "5분 명상." },
    { mission: "작업 환경 손보기", actionTitle: "책상 위 주의분산 1개 치우기", actionHowTo: "0~1분 책상 훑기 · 1~3분 가장 시선을 빼앗는 물건 1개 다른 방으로 이동 · 3~5분 빈자리에 물 한 잔만 두기.", actionMinutes: 5, videoReason: "5초 법칙." },
    { mission: "에너지 골든타임 찾기", actionTitle: "집중이 가장 잘 되는 시간대 1개", actionHowTo: "0~1분 어제 시간대별 집중도 떠올리기 · 1~3분 가장 좋았던 시간대 + 그때 한 일 한 줄 · 3~4분 내일 그 시간대에 딥워크 예약.", actionMinutes: 4, videoReason: "빼기 명상." },
    { mission: "1주차 진단", actionTitle: "회복탄력성 진단 (1주차)", actionHowTo: "0~1분 /assessment/resilience 열기 · 1~6분 응답 · 6~7분 점수 기록.", actionMinutes: 7, videoReason: "회복력 영상." },
    { mission: "같은 시간대 반복", actionTitle: "어제 미션 같은 시간 반복", actionHowTo: "0~1분 어제 효과 좋았던 미션 1개 확인 · 1~5분 같은 시간대에 다시 실행 · 끝나고 한 줄 비교.", actionMinutes: 5, videoReason: "루틴 영상." },
    { mission: "멀티태스킹 1개 끊기", actionTitle: "한 번에 1가지만 정하기", actionHowTo: "0~1분 자주 동시 처리하는 2가지 떠올리기 · 1~3분 둘 중 1개만 먼저 끝낸다는 룰 메모 · 3~4분 휴대폰 알람 OFF 후 1개에 집중.", actionMinutes: 4, videoReason: "생각 비우기." },
    { mission: "집중 패턴 진단", actionTitle: "불안 결 진단으로 방해 객관화", actionHowTo: "0~1분 /anxiety-package 열기 · 1~5분 응답 완료 · 5~6분 가장 높은 영역 기록.", actionMinutes: 6, videoReason: "호흡명상." },
    { mission: "관계 차단 시간", actionTitle: "집중 시간 알리고 차단", actionHowTo: "0~1분 가장 자주 끼어드는 1명 정하기 · 1~3분 '___까지 집중 중. 끝나면 연락할게' 메시지 발송 · 3~5분 채팅창 알림 OFF.", actionMinutes: 5, videoReason: "멈추는 호흡법." },
    { mission: "호흡 분산", actionTitle: "박스호흡 아·점·저 1세트씩", actionHowTo: "0~1분 알람 3개 등록 · 1~5분 지금 한 세트 5번 · 5~6분 다음 알람 시각 메모.", actionMinutes: 6, videoReason: "박스호흡." },
    { mission: "저널링 5분", actionTitle: "오늘 한 일 + 흐트러진 이유 1줄", actionHowTo: "0~1분 노트 펼치기 · 1~4분 오늘 마친 일 3개 + 가장 흐트러진 순간의 이유 한 줄 · 4~5분 내일 한 가지 다르게 할 행동 표시.", actionMinutes: 5, videoReason: "저널 직전 명상." },
    { mission: "2주차 비교", actionTitle: "스트레스 진단 반복 (2주차)", actionHowTo: "0~1분 /stress-package 열기 · 1~5분 응답 완료 · 5~6분 변화 기록.", actionMinutes: 5, videoReason: "호흡 명상." },
    { mission: "핵심 루틴 강화", actionTitle: "효과 컸던 집중 루틴 3개 재실행", actionHowTo: "0~1분 1~14일 체크인에서 효과 좋았던 루틴 3개 선정 · 1~5분 1개 지금 시도 · 5~6분 나머지 2개 캘린더에 등록.", actionMinutes: 6, videoReason: "빼기 명상." },
    { mission: "회피 마주하기", actionTitle: "미뤄둔 일 5분만 시도", actionHowTo: "0~1분 미뤄둔 일 1개 정하기 · 1~5분 타이머 5분만 시도 · 끝나면 다음 단계 한 줄 메모.", actionMinutes: 5, videoReason: "회피의 과학." },
    { mission: "도움 요청", actionTitle: "집중 위해 도움 1개 요청", actionHowTo: "0~1분 도움 줄 1명 정하기 · 1~3분 '___까지 ___ 좀 도와줄 수 있어?' 메시지 · 3~4분 전송.", actionMinutes: 4, videoReason: "회피형 극복." },
    { mission: "에너지 진단", actionTitle: "시간대별 에너지 0~10 기록", actionHowTo: "0~1분 노트에 아·점·저 칸 만들기 · 1~4분 각 시간대 에너지 점수 기록 · 4~5분 가장 높은 시간대에 별표하고 내일 딥워크 예약.", actionMinutes: 5, videoReason: "명상." },
    { mission: "자기 칭찬", actionTitle: "오늘 집중 잘된 1순간 칭찬", actionHowTo: "0~1분 오늘 가장 집중된 순간 떠올리기 · 1~2분 '___할 때 잘했어' 한 문장 · 2~3분 그 조건을 내일 다시 만들 방법 한 줄.", actionMinutes: 3, videoReason: "자애 명상." },
    { mission: "환경 1개 더 정리", actionTitle: "책상·폰·메일 중 1개 5분 정리", actionHowTo: "0~1분 가장 어수선한 1곳 정하기 · 1~5분 5분 안에 정리·삭제·차단 1개씩 실행.", actionMinutes: 5, videoReason: "긍정확언." },
    { mission: "3주차 진단", actionTitle: "회복탄력성 진단 (3주차)", actionHowTo: "0~1분 /assessment/resilience 열기 · 1~6분 응답 · 6~7분 변화 기록.", actionMinutes: 7, videoReason: "3주 마무리." },
    { mission: "워크북 심화", actionTitle: "집중 방해 트리거 3층 분해", actionHowTo: "0~1분 가장 큰 방해요소 1개 선정 · 1~5분 '상황·생각·행동' 3층 분해 · 5~8분 각 층 대응 1개씩.", actionMinutes: 8, videoReason: "마음 비우기." },
    { mission: "코파일럿 1:1", actionTitle: "집중 주제 1개 코파일럿 입력", actionHowTo: "0~1분 코파일럿 열기 · 1~3분 '요즘 ___ 때문에 산만' 한 문장 입력 · 3~6분 답변 중 1개를 워크북에 옮기기.", actionMinutes: 6, videoReason: "5분 아침명상." },
    { mission: "재발 방지", actionTitle: "집중 무너지는 신호 1줄", actionHowTo: "0~1분 최근 산만했던 순간 떠올리기 · 1~3분 '___ 신호가 오면 ___ 한다' 작성 · 3~5분 메모 고정.", actionMinutes: 5, videoReason: "알아차림 명상." },
    { mission: "핵심 루틴 고정", actionTitle: "집중 루틴 TOP 3 시각 부여", actionHowTo: "0~1분 효과 컸던 루틴 3개 선정 · 1~4분 시각 부여 · 4~6분 알람 3개 등록.", actionMinutes: 6, videoReason: "데일리 명상." },
    { mission: "관계 점검", actionTitle: "집중 방해 관계 1개 적기", actionHowTo: "0~1분 가장 자주 끼어드는 1명 떠올리기 · 1~4분 '누가·언제·어떻게 방해' 한 줄 · 4~6분 다음번 차단 행동 1개.", actionMinutes: 6, videoReason: "호흡 명상." },
    { mission: "거절 문장", actionTitle: "'지금은 집중 시간' 거절 1개", actionHowTo: "0~1분 자주 받는 끼어듦 1개 떠올리기 · 1~3분 '미안, ___까지 집중 중이야. ___에 다시 얘기하자' 한 문장 · 3~4분 메모 저장.", actionMinutes: 4, videoReason: "이완명상." },
    { mission: "4주차 요약", actionTitle: "4주 동안 집중이 ___ 변했다", actionHowTo: "0~1분 1·4주차 비교 · 1~3분 한 문장 요약 · 3~5분 핵심 행동 1개 표시.", actionMinutes: 5, videoReason: "마무리 명상." },
    { mission: "최종 진단", actionTitle: "우울감 최종 진단 (Day 2 반복)", actionHowTo: "0~1분 /depression-package 열기 · 1~5분 응답 · 5~6분 30일 그래프 저장.", actionMinutes: 6, videoReason: "리포트 직전 정렬." },
    { mission: "30일 선언문", actionTitle: "'집중을 ___하는 사람'", actionHowTo: "0~1분 30일 변화 떠올리기 · 1~3분 '나는 집중을 ___하는 사람이다' 한 문장 · 3~5분 잠금화면 메모.", actionMinutes: 5, videoReason: "마무리 명상." },
  ],
  relationship: [
    { mission: "관계 베이스라인", actionTitle: "최근 갈등 1장면 사실 1문장", actionHowTo: "0~1분 최근 갈등 1장면 떠올리기 · 1~3분 감정·해석 빼고 사실 1문장 · 3~4분 그때 강도 0~10 기록.", actionMinutes: 4, videoReason: "베이스라인 직후 호흡." },
    { mission: "내 관계 패턴 신호", actionTitle: "내 반복 반응 패턴 1줄", actionHowTo: "0~1분 갈등 시 자주 하는 행동 떠올리기 · 1~3분 '나는 ___할 때 ___한다' 한 문장 · 3~4분 그 패턴 강도 0~10.", actionMinutes: 4, videoReason: "감정 라벨링." },
    { mission: "경청 5분", actionTitle: "한 사람 5분 끊지 않고 듣기", actionHowTo: "0~1분 들을 사람 1명 정하고 시간 잡기 · 1~5분 끊지 않고 5분 듣기(고개 끄덕임만) · 5~6분 들은 핵심 한 문장으로 반영.", actionMinutes: 5, videoReason: "호흡으로 반응 멈추기." },
    { mission: "공감 1문장", actionTitle: "'그랬구나' 반영 1회", actionHowTo: "0~1분 오늘 대화 1회 정하기 · 1~2분 상대 말 끝에 '그랬구나, ___겠다' 한 문장 · 2~3분 끝나고 상대 반응 한 줄 메모.", actionMinutes: 3, videoReason: "자애 명상." },
    { mission: "경계 1개 정의", actionTitle: "'나는 ___은 어렵다' 한 줄", actionHowTo: "0~1분 자주 부담스러운 요청 1개 떠올리기 · 1~3분 '나는 ___은 어렵다' 한 문장으로 명문화 · 3~4분 메모 저장.", actionMinutes: 4, videoReason: "거절은 다정한 경계." },
    { mission: "부드러운 거절 1회", actionTitle: "오늘 작은 거절 1개 실행", actionHowTo: "0~1분 오늘 받은 작은 부탁 1개 정하기 · 1~3분 '고마워, 이번엔 ___ 때문에 어려워' 한 문장 · 3~4분 직접 또는 메시지로 전달.", actionMinutes: 4, videoReason: "거절 영상." },
    { mission: "1주차 진단", actionTitle: "회복탄력성 진단 (1주차)", actionHowTo: "0~1분 /assessment/resilience 열기 · 1~6분 응답 · 6~7분 점수 기록.", actionMinutes: 7, videoReason: "회복력 영상." },
    { mission: "같은 사람 같은 시간", actionTitle: "어제 대화 사람과 같은 시간 안부", actionHowTo: "0~1분 어제 대화 1명 정하기 · 1~4분 같은 시간대에 짧은 안부 메시지 · 4~5분 답변 받으면 한 줄 감사.", actionMinutes: 5, videoReason: "이완명상." },
    { mission: "자동 반응 멈추기", actionTitle: "'멈춤' + 호흡 5번", actionHowTo: "0~1분 평소 자동 반응 1개 떠올리기 · 1~2분 그 상황에 '멈춤' 소리 내고 4-4-6 호흡 5번 · 2~3분 다른 반응 1개 미리 정해두기.", actionMinutes: 3, videoReason: "호흡법." },
    { mission: "관계 패턴 진단", actionTitle: "관계 패턴 진단으로 객관화", actionHowTo: "0~1분 /relationship-package 열기 · 1~6분 응답 · 6~7분 가장 높은 영역 1개 기록.", actionMinutes: 7, videoReason: "호흡명상." },
    { mission: "최근 갈등 다시 보기", actionTitle: "상대 입장 1줄로 적기", actionHowTo: "0~1분 최근 갈등 1장면 떠올리기 · 1~4분 '상대는 그때 ___ 때문에 ___' 한 문장 · 4~5분 내가 다르게 할 1가지 메모.", actionMinutes: 5, videoReason: "감정 라벨링." },
    { mission: "호흡으로 반응 분산", actionTitle: "박스호흡 아·점·저 1세트씩", actionHowTo: "0~1분 알람 3개 등록 · 1~5분 지금 한 세트 5번 · 5~6분 다음 알람 메모.", actionMinutes: 6, videoReason: "호흡." },
    { mission: "자유 기록 5분", actionTitle: "관계 일기 5분 자유 기록", actionHowTo: "0~1분 타이머 5분 · 1~5분 떠오르는 사람·장면을 멈추지 않고 기록 · 끝나면 가장 자주 등장한 이름 1명에 별표.", actionMinutes: 5, videoReason: "저널 직전 명상." },
    { mission: "2주차 비교", actionTitle: "스트레스 진단 반복 (2주차)", actionHowTo: "0~1분 /stress-package 열기 · 1~5분 응답 · 5~6분 변화 기록.", actionMinutes: 5, videoReason: "호흡명상." },
    { mission: "효과있던 대화 강화", actionTitle: "효과 좋았던 대화 1개 같은 방식 반복", actionHowTo: "0~1분 1~14일 체크인에서 효과 좋았던 대화 1개 선정 · 1~5분 같은 사람·같은 방식으로 짧게 반복 · 5~6분 차이 한 줄.", actionMinutes: 6, videoReason: "명상." },
    { mission: "회피 마주하기", actionTitle: "미뤄둔 대화 5분만 시도", actionHowTo: "0~1분 미뤄둔 대화 1개 정하기 · 1~5분 타이머 5분만 시작(불편하면 멈춰도 OK) · 끝나면 다음 단계 한 줄.", actionMinutes: 5, videoReason: "회피의 과학." },
    { mission: "도움 요청", actionTitle: "한 사람에게 '얘기 좀 가능해?'", actionHowTo: "0~1분 가장 편한 1명 정하기 · 1~3분 '요즘 ___ 때문에 얘기 좀 가능해?' 메시지 · 3~4분 전송.", actionMinutes: 4, videoReason: "회피형 극복." },
    { mission: "감정 강도 진단", actionTitle: "관계 감정 0~10 기록", actionHowTo: "0~1분 가장 강한 관계 감정 1개 떠올리기 · 1~3분 단어 + 0~10 + 신체 위치 기록 · 3~5분 4-4-6 호흡 5번.", actionMinutes: 5, videoReason: "RAIN 명상." },
    { mission: "자기 친절", actionTitle: "관계에서 잘한 1개 자기 칭찬", actionHowTo: "0~1분 오늘 관계 한 장면 떠올리기 · 1~2분 잘한 행동 1개 기록 · 2~3분 '잘했어, ___' 자기 칭찬 한 문장.", actionMinutes: 3, videoReason: "자애 명상." },
    { mission: "관계 환경 1개 손보기", actionTitle: "연락 톤·시간·매체 1개 변경", actionHowTo: "0~1분 가장 피로한 연락 1개 정하기 · 1~3분 톤·시간·매체 중 1개 바꾸기 결정 · 3~5분 상대에게 한 줄 공지.", actionMinutes: 5, videoReason: "긍정확언." },
    { mission: "3주차 진단", actionTitle: "회복탄력성 진단 (3주차)", actionHowTo: "0~1분 /assessment/resilience 열기 · 1~6분 응답 · 6~7분 변화 한 줄.", actionMinutes: 7, videoReason: "3주 마무리." },
    { mission: "워크북 심화", actionTitle: "반복 관계 패턴 1개 분해", actionHowTo: "0~1분 가장 자주 반복되는 패턴 1개 선정 · 1~5분 '상황·내 반응·결과' 3층 분해 · 5~8분 각 층 대안 1개.", actionMinutes: 8, videoReason: "마음 비우기." },
    { mission: "코파일럿 1:1", actionTitle: "관계 주제 1개 코파일럿 입력", actionHowTo: "0~1분 코파일럿 열기 · 1~3분 '요즘 ___와 ___' 한 문장 입력 · 3~6분 답변 중 1개 워크북 옮기기.", actionMinutes: 6, videoReason: "5분 아침명상." },
    { mission: "재발 방지", actionTitle: "관계 무너질 신호 1줄", actionHowTo: "0~1분 최근 관계 흔들린 순간 떠올리기 · 1~3분 '___ 신호가 오면 ___ 한다' 작성 · 3~5분 메모 고정.", actionMinutes: 5, videoReason: "알아차림 명상." },
    { mission: "핵심 루틴 고정", actionTitle: "관계 루틴 TOP 3 시각 부여", actionHowTo: "0~1분 효과 컸던 관계 루틴 3개 선정 · 1~4분 시각 부여 · 4~6분 알람 3개 등록.", actionMinutes: 6, videoReason: "데일리 명상." },
    { mission: "관계 1순위 점검", actionTitle: "미뤄둔 대화 첫 문장 보내기", actionHowTo: "0~1분 가장 미뤄둔 1명 정하기 · 1~4분 '오랜만이야, ___' 첫 문장 작성 · 4~5분 전송.", actionMinutes: 5, videoReason: "이완명상." },
    { mission: "거절 문장", actionTitle: "관계 보호 거절 1개 작성", actionHowTo: "0~1분 자주 흔들리는 부탁 1개 정하기 · 1~3분 '오늘은 ___ 때문에 어려워, 다음에 ___' 한 문장 · 3~4분 메모 저장.", actionMinutes: 4, videoReason: "이완명상." },
    { mission: "4주차 요약", actionTitle: "4주 동안 관계가 ___ 변했다", actionHowTo: "0~1분 1·4주차 비교 · 1~3분 한 문장 요약 · 3~5분 핵심 행동 1개 표시.", actionMinutes: 5, videoReason: "마무리 명상." },
    { mission: "최종 진단", actionTitle: "우울감 최종 진단 (Day 2 반복)", actionHowTo: "0~1분 /depression-package 열기 · 1~5분 응답 · 5~6분 30일 그래프 저장.", actionMinutes: 6, videoReason: "마음 정리." },
    { mission: "30일 선언문", actionTitle: "'관계를 ___하는 사람'", actionHowTo: "0~1분 30일 변화 떠올리기 · 1~3분 '나는 관계를 ___하는 사람이다' 한 문장 · 3~5분 잠금화면 메모.", actionMinutes: 5, videoReason: "마무리 명상." },
  ],
  self: [
    { mission: "자기 이해 베이스라인", actionTitle: "내 핵심 가치 단어 3개", actionHowTo: "0~1분 눈 감고 중요한 가치 떠올리기 · 1~4분 단어 3개로 적기(예: 정직·자유·연결) · 4~5분 가장 큰 1개에 별표.", actionMinutes: 5, videoReason: "회복탄력성 영상." },
    { mission: "강점 3개", actionTitle: "내 강점 3개 적기", actionHowTo: "0~1분 주변 칭찬 떠올리기 · 1~3분 강점 3개 단어로 기록 · 3~4분 각 강점이 잘 발휘된 최근 사례 한 줄.", actionMinutes: 4, videoReason: "감정 라벨링." },
    { mission: "그림자 1개", actionTitle: "피하고 싶은 모습 1개 직면", actionHowTo: "0~1분 평소 인정하기 싫은 모습 1개 떠올리기 · 1~3분 '나는 ___이고 싶지 않다' 한 문장 · 3~4분 그 모습이 보호하려는 것 한 줄.", actionMinutes: 4, videoReason: "빼기 명상." },
    { mission: "이상적 하루", actionTitle: "이상적 하루 시간표 1줄씩", actionHowTo: "0~1분 노트 펼치기 · 1~5분 아침·점심·저녁·잠 직전 한 줄씩 이상 행동 · 5~6분 오늘 그중 1개만 시도하기로 표시.", actionMinutes: 6, videoReason: "긍정확언." },
    { mission: "자유 기록 5분", actionTitle: "5분 손 멈추지 않고 적기", actionHowTo: "0~1분 타이머 5분 · 1~5분 자신에 대해 떠오르는 단어를 멈추지 말고 적기 · 끝나면 가장 자주 나온 단어 1개에 별표.", actionMinutes: 5, videoReason: "저널 직전 명상." },
    { mission: "내면 대화 1개", actionTitle: "내면 비판자 목소리 1줄", actionHowTo: "0~1분 자주 들리는 자기비판 떠올리기 · 1~3분 비판자 목소리를 따옴표로 한 줄 적기 · 3~4분 그 목소리에 다정한 답변 한 줄.", actionMinutes: 4, videoReason: "자애 명상." },
    { mission: "1주차 진단", actionTitle: "회복탄력성 진단 (1주차)", actionHowTo: "0~1분 /assessment/resilience 열기 · 1~6분 응답 · 6~7분 점수 기록.", actionMinutes: 7, videoReason: "회복력 영상." },
    { mission: "어제 강점 다시", actionTitle: "어제 적은 강점 1개 의식적 사용", actionHowTo: "0~1분 어제 강점 노트 확인 · 1~4분 그 강점을 오늘 사용할 한 가지 상황 정하기 · 4~5분 실행 후 한 줄 메모.", actionMinutes: 5, videoReason: "명상." },
    { mission: "자동사고 멈추기", actionTitle: "비판자 등장 시 '멈춤' + 호흡", actionHowTo: "0~1분 비판자 출현 신호 떠올리기 · 1~2분 '멈춤' 소리 내고 4-4-6 호흡 5번 · 2~3분 자기 친절 한 문장 말하기.", actionMinutes: 3, videoReason: "빼기 명상." },
    { mission: "패턴 진단", actionTitle: "불안 결 진단으로 패턴 객관화", actionHowTo: "0~1분 /anxiety-package 열기 · 1~5분 응답 · 5~6분 가장 높은 영역 기록.", actionMinutes: 6, videoReason: "호흡 명상." },
    { mission: "내면 비판자 → 코치", actionTitle: "비판 1개 → 코치 말 1개로 변환", actionHowTo: "0~1분 자주 듣는 비판 1개 적기 · 1~3분 같은 내용을 다정한 코치 말로 다시 작성 · 3~4분 코치 말을 소리 내 말하기.", actionMinutes: 4, videoReason: "호흡으로 멈추기." },
    { mission: "호흡 분산", actionTitle: "박스호흡 아·점·저 1세트씩", actionHowTo: "0~1분 알람 3개 등록 · 1~5분 지금 1세트 5번 · 5~6분 다음 알람 메모.", actionMinutes: 6, videoReason: "명상." },
    { mission: "자유 기록 5분", actionTitle: "핵심 가치 vs 오늘 행동 차이 1줄", actionHowTo: "0~1분 핵심 가치 3개 다시 보기 · 1~4분 오늘 행동과의 갭 1줄씩 · 4~5분 가장 큰 갭 1개에 표시.", actionMinutes: 5, videoReason: "저널 직전 명상." },
    { mission: "2주차 비교", actionTitle: "스트레스 진단 반복 (2주차)", actionHowTo: "0~1분 /stress-package 열기 · 1~5분 응답 · 5~6분 변화 기록.", actionMinutes: 5, videoReason: "호흡명상." },
    { mission: "효과있던 루틴 강화", actionTitle: "자기 정렬에 좋았던 루틴 3개 재실행", actionHowTo: "0~1분 1~14일 체크인에서 효과 컸던 루틴 3개 선정 · 1~5분 1개 지금 시도 · 5~6분 나머지 시각 등록.", actionMinutes: 6, videoReason: "빼기 명상." },
    { mission: "그림자 마주하기", actionTitle: "피하던 모습 1개 5분 마주", actionHowTo: "0~1분 피하던 모습 1개 떠올리기 · 1~5분 '나는 ___도 가지고 있다' 문장으로 5분 자유 기록 · 끝나면 한 호흡.", actionMinutes: 5, videoReason: "불편 감정 명상." },
    { mission: "도움 요청", actionTitle: "나를 잘 아는 1명에게 피드백 요청", actionHowTo: "0~1분 신뢰하는 1명 정하기 · 1~3분 '요즘 내가 ___해 보여? 솔직히 한 줄만 부탁해' 메시지 · 3~4분 전송.", actionMinutes: 4, videoReason: "명상." },
    { mission: "정체성 진단", actionTitle: "핵심 감정 0~10 강도", actionHowTo: "0~1분 지금 가장 강한 감정 1개 · 1~3분 단어 + 0~10 + 신체 위치 · 3~5분 그 감정이 가치와 어떻게 연결되는지 한 줄.", actionMinutes: 5, videoReason: "명상." },
    { mission: "자기 친절", actionTitle: "오늘 잘한 일 1개 자기 칭찬", actionHowTo: "0~1분 오늘 한 일 떠올리기 · 1~2분 잘한 일 1개 기록 · 2~3분 '잘했어, ___' 한 문장.", actionMinutes: 3, videoReason: "자애 명상." },
    { mission: "환경 1개 정렬", actionTitle: "가치와 안 맞는 1개 손보기", actionHowTo: "0~1분 핵심 가치 다시 보기 · 1~3분 가치와 가장 안 맞는 환경/일정 1개 정하기 · 3~5분 5분 안에 가능한 변경 1개 실행.", actionMinutes: 5, videoReason: "긍정확언." },
    { mission: "3주차 진단", actionTitle: "회복탄력성 진단 (3주차)", actionHowTo: "0~1분 /assessment/resilience 열기 · 1~6분 응답 · 6~7분 변화 한 줄.", actionMinutes: 7, videoReason: "3주 마무리." },
    { mission: "워크북 심화", actionTitle: "핵심 가치 vs 일상 갭 3줄", actionHowTo: "0~1분 가치 3개 적기 · 1~5분 일상 행동과 갭을 3줄로 분해 · 5~8분 다음 주 줄일 행동 1개 표시.", actionMinutes: 8, videoReason: "마음 비우기." },
    { mission: "코파일럿 1:1", actionTitle: "자기 이해 주제 1개 입력", actionHowTo: "0~1분 코파일럿 열기 · 1~3분 '나는 ___을 원한다' 한 문장 입력 · 3~6분 답변 중 1개 워크북 옮기기.", actionMinutes: 6, videoReason: "5분 아침명상." },
    { mission: "재발 방지", actionTitle: "옛 패턴 신호 1줄", actionHowTo: "0~1분 옛 비판자 패턴 떠올리기 · 1~3분 '___ 신호가 오면 ___ 한다' 작성 · 3~5분 메모 고정.", actionMinutes: 5, videoReason: "알아차림 명상." },
    { mission: "핵심 루틴 고정", actionTitle: "자기 정렬 루틴 TOP 3 시각 부여", actionHowTo: "0~1분 효과 컸던 루틴 3개 선정 · 1~4분 시각 부여 · 4~6분 알람 3개 등록.", actionMinutes: 6, videoReason: "데일리 명상." },
    { mission: "관계 1순위 점검", actionTitle: "나를 도와줄 1명에게 메시지", actionHowTo: "0~1분 신뢰하는 1명 정하기 · 1~4분 '요즘 ___ 때문에 짧게 얘기 가능해?' 한 문장 · 4~5분 전송.", actionMinutes: 5, videoReason: "명상." },
    { mission: "거절 문장", actionTitle: "가치 보호 거절 1개", actionHowTo: "0~1분 가치를 흔드는 요청 1개 정하기 · 1~3분 '나에겐 ___가 중요해서 어려워' 한 문장 · 3~4분 메모 저장.", actionMinutes: 4, videoReason: "이완명상." },
    { mission: "4주차 요약", actionTitle: "4주 동안 나는 ___ 변했다", actionHowTo: "0~1분 1·4주차 노트 비교 · 1~3분 한 문장 요약 · 3~5분 핵심 행동 1개 표시.", actionMinutes: 5, videoReason: "마무리 명상." },
    { mission: "최종 진단", actionTitle: "우울감 최종 진단 (Day 2 반복)", actionHowTo: "0~1분 /depression-package 열기 · 1~5분 응답 · 5~6분 30일 그래프 저장.", actionMinutes: 6, videoReason: "마음 정리." },
    { mission: "30일 선언문", actionTitle: "'나는 ___한 사람으로 한 발 나아간다'", actionHowTo: "0~1분 30일 변화 떠올리기 · 1~3분 한 문장 작성 · 3~5분 잠금화면 메모.", actionMinutes: 5, videoReason: "마무리 명상." },
  ],
  parenting: [
    { mission: "번아웃 베이스라인", actionTitle: "오늘 에너지 0~10 아침·저녁", actionHowTo: "0~1분 노트 펼치기 · 1~3분 아침/저녁 에너지 점수 + 한 줄 이유 · 3~4분 가장 빠진 시간대에 별표.", actionMinutes: 4, videoReason: "부모 자애 명상." },
    { mission: "번아웃 신호 3개", actionTitle: "신호 단어 3개 적기", actionHowTo: "0~1분 최근 번아웃 떠올리기 · 1~3분 신체·감정 신호 3개 단어로 · 3~4분 가장 자주 나온 1개에 별표.", actionMinutes: 4, videoReason: "이완명상." },
    { mission: "나만의 5분 확보", actionTitle: "오늘 나만의 5분 확보", actionHowTo: "0~1분 화장실·베란다·차 안 등 장소 정하기 · 1~5분 그곳에서 휴대폰 끄고 깊은 숨 · 5~6분 끝나고 한 줄 메모.", actionMinutes: 5, videoReason: "호흡 명상." },
    { mission: "도움 요청 1개", actionTitle: "배우자·가족에게 1가지 요청", actionHowTo: "0~1분 도움받을 1가지 정하기 · 1~3분 '오늘 ___ 좀 해줄 수 있어?' 한 문장 · 3~4분 직접 또는 메시지.", actionMinutes: 4, videoReason: "호흡." },
    { mission: "자기 친절 한 줄", actionTitle: "'잘 하고 있어' 자기 칭찬", actionHowTo: "0~1분 오늘 양육 한 장면 떠올리기 · 1~2분 '잘하고 있어, ___' 한 문장 · 2~3분 거울 보고 소리 내 말하기.", actionMinutes: 3, videoReason: "자애 명상." },
    { mission: "호흡 1세트", actionTitle: "4-4-6 호흡 5번", actionHowTo: "0~1분 의자에 앉아 어깨 풀기 · 1~3분 4-4-6 호흡 5번 · 마지막 30초 그대로 가만히.", actionMinutes: 3, videoReason: "호흡." },
    { mission: "1주차 진단", actionTitle: "회복탄력성 진단 (1주차)", actionHowTo: "0~1분 /assessment/resilience 열기 · 1~6분 응답 · 6~7분 점수 기록.", actionMinutes: 7, videoReason: "회복력 영상." },
    { mission: "같은 시간 5분", actionTitle: "어제 5분을 같은 시간에 반복", actionHowTo: "0~1분 어제 나만의 5분 시각 확인 · 1~5분 같은 시각 같은 장소에서 5분 · 끝나고 한 줄 메모.", actionMinutes: 5, videoReason: "명상." },
    { mission: "자동 반응 멈추기", actionTitle: "아이 앞에서 '멈춤' + 호흡", actionHowTo: "0~1분 폭발 직전 신호 떠올리기 · 1~2분 그 순간 '멈춤' 속으로 외치고 호흡 5번 · 2~3분 다른 반응 1개 미리 정해두기.", actionMinutes: 3, videoReason: "호흡법." },
    { mission: "패턴 진단", actionTitle: "불안 결 진단으로 번아웃 객관화", actionHowTo: "0~1분 /anxiety-package 열기 · 1~5분 응답 · 5~6분 가장 높은 영역 기록.", actionMinutes: 6, videoReason: "호흡명상." },
    { mission: "최근 폭발 1장면", actionTitle: "사실 1문장으로 묘사", actionHowTo: "0~1분 최근 폭발 1장면 떠올리기 · 1~4분 사실 1문장으로 작성 · 4~5분 다음번 다르게 할 1가지 메모.", actionMinutes: 5, videoReason: "호흡." },
    { mission: "호흡 분산", actionTitle: "박스호흡 아·점·저 1세트씩", actionHowTo: "0~1분 알람 3개 등록 · 1~5분 지금 1세트 · 5~6분 다음 알람 메모.", actionMinutes: 6, videoReason: "호흡." },
    { mission: "저널 5분", actionTitle: "엄마/아빠로서 5분 자유 기록", actionHowTo: "0~1분 타이머 5분 · 1~5분 부모로서 떠오르는 단어 멈추지 말고 기록 · 끝나면 자주 나온 단어 별표.", actionMinutes: 5, videoReason: "명상." },
    { mission: "2주차 비교", actionTitle: "스트레스 진단 반복 (2주차)", actionHowTo: "0~1분 /stress-package 열기 · 1~5분 응답 · 5~6분 변화 기록.", actionMinutes: 5, videoReason: "호흡명상." },
    { mission: "회복 루틴 강화", actionTitle: "회복에 좋았던 루틴 3개 재실행", actionHowTo: "0~1분 1~14일 체크인에서 회복 효과 컸던 루틴 3개 선정 · 1~5분 1개 지금 시도 · 5~6분 나머지 시각 등록.", actionMinutes: 6, videoReason: "명상." },
    { mission: "회피 마주하기", actionTitle: "미뤄둔 자기돌봄 5분", actionHowTo: "0~1분 미뤄둔 자기돌봄 1개 정하기 · 1~5분 타이머 5분 시도 · 끝나면 한 줄 메모.", actionMinutes: 5, videoReason: "불편 감정 명상." },
    { mission: "도움 요청", actionTitle: "주변에 구체적 도움 1개 요청", actionHowTo: "0~1분 도움받을 1명·1가지 정하기 · 1~3분 '___ 시간에 ___ 좀 해줄 수 있어?' 메시지 · 3~4분 전송.", actionMinutes: 4, videoReason: "호흡." },
    { mission: "감정 강도 진단", actionTitle: "육아 감정 0~10 강도", actionHowTo: "0~1분 가장 강한 육아 감정 1개 · 1~3분 단어 + 0~10 + 신체 위치 · 3~5분 4-4-6 호흡 5번.", actionMinutes: 5, videoReason: "RAIN 명상." },
    { mission: "자기 칭찬", actionTitle: "오늘 잘한 양육 1개 자기 칭찬", actionHowTo: "0~1분 오늘 양육 한 장면 떠올리기 · 1~2분 잘한 1개 기록 · 2~3분 '잘했어, ___' 한 문장.", actionMinutes: 3, videoReason: "자애 명상." },
    { mission: "환경 1개 손보기", actionTitle: "육아 동선 1개 5분 조정", actionHowTo: "0~1분 가장 피곤한 동선 1개 정하기 · 1~5분 물건 위치·일정 1개 5분 안에 변경.", actionMinutes: 5, videoReason: "긍정확언." },
    { mission: "3주차 진단", actionTitle: "회복탄력성 진단 (3주차)", actionHowTo: "0~1분 /assessment/resilience 열기 · 1~6분 응답 · 6~7분 변화 한 줄.", actionMinutes: 7, videoReason: "3주 마무리." },
    { mission: "워크북 심화", actionTitle: "번아웃 트리거 1개 3층 분해", actionHowTo: "0~1분 가장 큰 트리거 1개 선정 · 1~5분 '상황·신체·감정' 3층 분해 · 5~8분 각 층 대응 1개씩.", actionMinutes: 8, videoReason: "마음 비우기." },
    { mission: "코파일럿 1:1", actionTitle: "육아 주제 1개 코파일럿 입력", actionHowTo: "0~1분 코파일럿 열기 · 1~3분 '요즘 ___ 때문에 ___' 한 문장 입력 · 3~6분 답변 중 1개 워크북 옮기기.", actionMinutes: 6, videoReason: "명상." },
    { mission: "재발 방지", actionTitle: "번아웃 신호 1줄", actionHowTo: "0~1분 최근 번아웃 직전 떠올리기 · 1~3분 '___ 신호가 오면 ___ 한다' 작성 · 3~5분 메모 고정.", actionMinutes: 5, videoReason: "알아차림 명상." },
    { mission: "핵심 루틴 고정", actionTitle: "회복 루틴 TOP 3 시각 부여", actionHowTo: "0~1분 효과 컸던 회복 루틴 3개 · 1~4분 시각 부여 · 4~6분 알람 3개 등록.", actionMinutes: 6, videoReason: "데일리 명상." },
    { mission: "관계 점검", actionTitle: "나를 지지할 1명에게 메시지", actionHowTo: "0~1분 가장 든든한 1명 정하기 · 1~4분 '요즘 ___ 한데 가끔 한 줄 응원 좀 해줘' 메시지 · 4~5분 전송.", actionMinutes: 5, videoReason: "이완명상." },
    { mission: "거절 문장", actionTitle: "에너지 보호 거절 1개", actionHowTo: "0~1분 자주 빼앗기는 일 1개 정하기 · 1~3분 '오늘은 아이와 ___ 때문에 어려워' 한 문장 · 3~4분 메모 저장.", actionMinutes: 4, videoReason: "이완명상." },
    { mission: "4주차 요약", actionTitle: "4주 동안 나는 ___ 변했다", actionHowTo: "0~1분 1·4주차 비교 · 1~3분 한 문장 요약 · 3~5분 핵심 행동 1개 표시.", actionMinutes: 5, videoReason: "마무리 명상." },
    { mission: "최종 진단", actionTitle: "우울감 최종 진단 (Day 2 반복)", actionHowTo: "0~1분 /depression-package 열기 · 1~5분 응답 · 5~6분 30일 그래프 저장.", actionMinutes: 6, videoReason: "마음 정리." },
    { mission: "30일 선언문", actionTitle: "'엄마/아빠로서 ___'", actionHowTo: "0~1분 30일 변화 떠올리기 · 1~3분 '엄마/아빠로서 나는 ___이다' 한 문장 · 3~5분 잠금화면 메모.", actionMinutes: 5, videoReason: "마무리 명상." },
  ],
  child_development: [
    { mission: "발달 베이스라인", actionTitle: "아이 강점 3개 적기", actionHowTo: "0~1분 노트 펼치기 · 1~3분 현재 잘하고 있는 강점 3개 단어로 · 3~4분 각 강점이 잘 보였던 최근 사례 한 줄.", actionMinutes: 4, videoReason: "회복탄력성 영상." },
    { mission: "성장 영역 3개", actionTitle: "성장 필요 영역 3개 적기", actionHowTo: "0~1분 최근 1주 관찰 떠올리기 · 1~3분 도움이 필요한 영역 3개 단어로 · 3~4분 가장 시급한 1개에 별표.", actionMinutes: 4, videoReason: "감정 라벨링." },
    { mission: "관찰 5분", actionTitle: "오늘 5분 행동 사실 관찰", actionHowTo: "0~1분 아이가 노는 자리 옆에 앉기 · 1~5분 평가 없이 행동 1개를 사실로 관찰 · 5~6분 본 것을 한 줄 기록.", actionMinutes: 5, videoReason: "회피의 과학." },
    { mission: "긍정 피드백 1회", actionTitle: "구체적 칭찬 1회 (행동 묘사)", actionHowTo: "0~1분 오늘 칭찬 거리 1개 정하기 · 1~2분 '~을 ~게 했구나' 형식으로 한 문장 · 2~3분 직접 말하고 반응 한 줄.", actionMinutes: 3, videoReason: "자애 명상." },
    { mission: "발달 활동 1개", actionTitle: "연령 맞춤 활동 5분", actionHowTo: "0~1분 책읽기·그리기·대화 중 1개 정하기 · 1~5분 5분간 함께 활동 · 5~6분 끝나고 한 줄 관찰 기록.", actionMinutes: 5, videoReason: "5분 호흡." },
    { mission: "기록 1줄", actionTitle: "오늘 발달 한 줄 일지", actionHowTo: "0~1분 오늘 본 발달 장면 떠올리기 · 1~2분 '오늘 ___을 ___게 했다' 한 줄 · 2~3분 워크북에 옮기기.", actionMinutes: 3, videoReason: "명상." },
    { mission: "1주차 진단", actionTitle: "회복탄력성 진단 (부모 1주차)", actionHowTo: "0~1분 /assessment/resilience 열기 · 1~6분 응답 · 6~7분 점수 기록.", actionMinutes: 7, videoReason: "회복력 영상." },
    { mission: "어제 활동 반복", actionTitle: "어제 활동을 같은 시간에 반복", actionHowTo: "0~1분 어제 활동·시각 확인 · 1~5분 같은 시각에 같은 활동 · 5~6분 차이 한 줄 메모.", actionMinutes: 5, videoReason: "명상." },
    { mission: "자동 평가 멈추기", actionTitle: "평가 전 '멈춤' + 호흡", actionHowTo: "0~1분 평가하고 싶은 순간 떠올리기 · 1~2분 그 순간 '멈춤' 속으로 외치고 호흡 5번 · 2~3분 평가 대신 사실 1줄 기록.", actionMinutes: 3, videoReason: "호흡법." },
    { mission: "패턴 진단", actionTitle: "불안 결 진단으로 아이 패턴 객관화", actionHowTo: "0~1분 /anxiety-package 열기 · 1~5분 부모 시점 응답 · 5~6분 가장 높은 영역 기록.", actionMinutes: 6, videoReason: "호흡명상." },
    { mission: "아이 감정 1개 라벨링", actionTitle: "아이 감정 단어 1개로 비춰주기", actionHowTo: "0~1분 아이의 감정 신호 떠올리기 · 1~3분 '지금 ___ 같아 보여' 한 문장 · 3~4분 아이 반응 한 줄 메모.", actionMinutes: 4, videoReason: "감정 라벨링." },
    { mission: "호흡 분산", actionTitle: "박스호흡 아·점·저 1세트씩", actionHowTo: "0~1분 알람 3개 등록 · 1~5분 지금 1세트 · 5~6분 다음 알람 메모.", actionMinutes: 6, videoReason: "호흡." },
    { mission: "저널 5분", actionTitle: "아이 관찰 5분 자유 기록", actionHowTo: "0~1분 타이머 5분 · 1~5분 오늘 관찰을 멈추지 말고 기록 · 끝나면 자주 등장한 행동 1개 별표.", actionMinutes: 5, videoReason: "명상." },
    { mission: "2주차 비교", actionTitle: "스트레스 진단 반복 (부모 2주차)", actionHowTo: "0~1분 /stress-package 열기 · 1~5분 응답 · 5~6분 변화 기록.", actionMinutes: 5, videoReason: "호흡명상." },
    { mission: "효과있던 활동 강화", actionTitle: "발달에 좋았던 활동 3개 재실행", actionHowTo: "0~1분 1~14일 체크인에서 좋았던 활동 3개 선정 · 1~5분 1개 지금 시도 · 5~6분 나머지 시각 등록.", actionMinutes: 6, videoReason: "명상." },
    { mission: "어려운 발달 영역 마주", actionTitle: "미뤄둔 활동 5분만 시도", actionHowTo: "0~1분 미뤄둔 발달 활동 1개 정하기 · 1~5분 타이머 5분만 시도 · 끝나면 한 줄 메모.", actionMinutes: 5, videoReason: "회피 영상." },
    { mission: "도움 요청", actionTitle: "교사·가족에게 피드백 1개 요청", actionHowTo: "0~1분 의견 받을 1명 정하기 · 1~3분 '요즘 ___에 대해 어떻게 보세요?' 메시지 · 3~4분 전송.", actionMinutes: 4, videoReason: "명상." },
    { mission: "감정 강도 진단", actionTitle: "육아 감정 0~10 강도", actionHowTo: "0~1분 가장 강한 육아 감정 1개 · 1~3분 단어 + 0~10 + 신체 위치 · 3~5분 4-4-6 호흡 5번.", actionMinutes: 5, videoReason: "RAIN 명상." },
    { mission: "자기 칭찬", actionTitle: "오늘 잘한 양육 1개 자기 칭찬", actionHowTo: "0~1분 오늘 한 양육 떠올리기 · 1~2분 잘한 1개 기록 · 2~3분 '잘했어, ___' 한 문장.", actionMinutes: 3, videoReason: "자애 명상." },
    { mission: "환경 1개 손보기", actionTitle: "발달 환경 1개 5분 조정", actionHowTo: "0~1분 책상·놀이공간·동선 중 1곳 정하기 · 1~5분 5분 안에 가능한 변경 1개 실행.", actionMinutes: 5, videoReason: "긍정확언." },
    { mission: "3주차 진단", actionTitle: "회복탄력성 진단 (3주차)", actionHowTo: "0~1분 /assessment/resilience 열기 · 1~6분 응답 · 6~7분 변화 한 줄.", actionMinutes: 7, videoReason: "3주 마무리." },
    { mission: "워크북 심화", actionTitle: "발달 영역 1개 깊이 분석", actionHowTo: "0~1분 가장 신경 쓰이는 영역 1개 선정 · 1~5분 '관찰·맥락·다음 단계' 3층 분해 · 5~8분 다음 1주 시도할 활동 1개.", actionMinutes: 8, videoReason: "마음 비우기." },
    { mission: "코파일럿 1:1", actionTitle: "발달 주제 1개 코파일럿 입력", actionHowTo: "0~1분 코파일럿 열기 · 1~3분 '우리 아이 ___' 한 문장 입력 · 3~6분 답변 중 1개 워크북 옮기기.", actionMinutes: 6, videoReason: "5분 아침명상." },
    { mission: "재발 방지", actionTitle: "발달 정체 신호 1줄", actionHowTo: "0~1분 최근 정체 신호 떠올리기 · 1~3분 '___ 신호가 오면 ___ 한다' 작성 · 3~5분 메모 고정.", actionMinutes: 5, videoReason: "알아차림 명상." },
    { mission: "핵심 루틴 고정", actionTitle: "관찰 루틴 TOP 3 시각 부여", actionHowTo: "0~1분 효과 컸던 관찰 루틴 3개 · 1~4분 시각 부여 · 4~6분 알람 3개 등록.", actionMinutes: 6, videoReason: "데일리 명상." },
    { mission: "관계 점검", actionTitle: "아이와 1:1 시간 10분 확보", actionHowTo: "0~1분 오늘 1:1 시각 정하기 · 1~9분 휴대폰 끄고 아이 주도 활동 9분 · 9~10분 끝나고 한 줄 메모.", actionMinutes: 5, videoReason: "명상." },
    { mission: "거절 문장", actionTitle: "외부 압박 거절 1개", actionHowTo: "0~1분 외부의 비교·압박 1개 정하기 · 1~3분 '우리 아이는 ___ 속도로 가고 있어' 한 문장 · 3~4분 메모 저장.", actionMinutes: 4, videoReason: "이완명상." },
    { mission: "4주차 요약", actionTitle: "4주 동안 아이가 ___ 변했다", actionHowTo: "0~1분 1·4주차 일지 비교 · 1~3분 한 문장 요약 · 3~5분 다음 달 핵심 1개 표시.", actionMinutes: 5, videoReason: "마무리 명상." },
    { mission: "최종 진단", actionTitle: "우울감 최종 진단 (부모 Day 2 반복)", actionHowTo: "0~1분 /depression-package 열기 · 1~5분 응답 · 5~6분 30일 그래프 저장.", actionMinutes: 6, videoReason: "마음 정리." },
    { mission: "30일 선언문", actionTitle: "'우리 아이를 ___하는 부모'", actionHowTo: "0~1분 30일 변화 떠올리기 · 1~3분 '나는 우리 아이를 ___하는 부모이다' 한 문장 · 3~5분 잠금화면 메모.", actionMinutes: 5, videoReason: "마무리 명상." },
  ],
  family_communication: [
    { mission: "소통 베이스라인", actionTitle: "최근 갈등 1장면 사실 1문장", actionHowTo: "0~1분 최근 가족 갈등 1장면 떠올리기 · 1~3분 사실 1문장 묘사 · 3~4분 그때 강도 0~10 기록.", actionMinutes: 4, videoReason: "거절은 다정한 경계." },
    { mission: "아이 감정 라벨링", actionTitle: "아이 감정 단어 1개로 비춰주기", actionHowTo: "0~1분 아이 감정 신호 떠올리기 · 1~3분 '지금 ___ 같아 보여' 한 문장 · 3~4분 아이 반응 한 줄.", actionMinutes: 4, videoReason: "감정 라벨링." },
    { mission: "경청 5분", actionTitle: "아이 5분 끊지 않고 듣기", actionHowTo: "0~1분 아이 옆에 앉아 시선 맞추기 · 1~5분 끊지 않고 5분 듣기(끄덕임만) · 5~6분 들은 핵심을 한 문장으로 반영.", actionMinutes: 5, videoReason: "호흡으로 반응 멈추기." },
    { mission: "반영 1문장", actionTitle: "'~게 느꼈구나' 반영 1회", actionHowTo: "0~1분 오늘 대화 1회 정하기 · 1~2분 아이 말 끝에 '~게 느꼈구나' 한 문장 · 2~3분 끝나고 반응 한 줄 메모.", actionMinutes: 3, videoReason: "자애 명상." },
    { mission: "훈육 언어 1개", actionTitle: "'안 돼' → '이렇게 하자' 변환", actionHowTo: "0~1분 자주 쓰는 '안 돼' 1개 떠올리기 · 1~3분 '___하자' 형식 1문장으로 변환 · 3~4분 오늘 한 번 사용 후 반응 한 줄.", actionMinutes: 4, videoReason: "불편 감정 명상." },
    { mission: "스킨십 1회", actionTitle: "오늘 10초 안아주기 1회", actionHowTo: "0~1분 자연스러운 타이밍 정하기 · 1~2분 10초 동안 말없이 안아주기 · 2~3분 끝나고 아이 표정 한 줄 메모.", actionMinutes: 3, videoReason: "긍정확언." },
    { mission: "1주차 진단", actionTitle: "회복탄력성 진단 (부모 1주차)", actionHowTo: "0~1분 /assessment/resilience 열기 · 1~6분 응답 · 6~7분 점수 기록.", actionMinutes: 7, videoReason: "회복력." },
    { mission: "같은 시간 같은 방식", actionTitle: "어제 대화 같은 시간 반복", actionHowTo: "0~1분 어제 대화 시각 확인 · 1~4분 같은 시각·같은 방식으로 짧은 대화 · 4~5분 차이 한 줄 메모.", actionMinutes: 5, videoReason: "명상." },
    { mission: "자동 반응 멈추기", actionTitle: "훈육 직전 '멈춤' + 호흡", actionHowTo: "0~1분 훈육 폭발 신호 떠올리기 · 1~2분 그 순간 '멈춤' 속으로 외치고 호흡 5번 · 2~3분 다른 반응 1개 미리 정해두기.", actionMinutes: 3, videoReason: "호흡법." },
    { mission: "관계 패턴 진단", actionTitle: "관계 패턴 진단으로 객관화", actionHowTo: "0~1분 /relationship-package 열기 · 1~6분 가족 관점 응답 · 6~7분 가장 높은 영역 기록.", actionMinutes: 7, videoReason: "호흡 명상." },
    { mission: "최근 폭발 다시 보기", actionTitle: "아이 입장 1줄로 적기", actionHowTo: "0~1분 최근 폭발 1장면 떠올리기 · 1~4분 '아이는 그때 ___ 때문에 ___' 한 문장 · 4~5분 다음번 다르게 할 1가지 메모.", actionMinutes: 5, videoReason: "감정 라벨링." },
    { mission: "호흡 분산", actionTitle: "박스호흡 아·점·저 1세트씩", actionHowTo: "0~1분 알람 3개 등록 · 1~5분 지금 1세트 · 5~6분 다음 알람 메모.", actionMinutes: 6, videoReason: "호흡." },
    { mission: "저널 5분", actionTitle: "오늘 대화 흐름 5분 자유 기록", actionHowTo: "0~1분 타이머 5분 · 1~5분 오늘 가족 대화를 멈추지 말고 기록 · 끝나면 가장 인상적이었던 한 마디 별표.", actionMinutes: 5, videoReason: "명상." },
    { mission: "2주차 비교", actionTitle: "스트레스 진단 반복 (2주차)", actionHowTo: "0~1분 /stress-package 열기 · 1~5분 응답 · 5~6분 변화 기록.", actionMinutes: 5, videoReason: "호흡명상." },
    { mission: "효과있던 대화 강화", actionTitle: "효과 좋았던 대화 1개 같은 방식 반복", actionHowTo: "0~1분 효과 좋았던 대화 1개 선정 · 1~5분 같은 사람·같은 방식 짧게 반복 · 5~6분 차이 한 줄.", actionMinutes: 6, videoReason: "명상." },
    { mission: "회피 마주하기", actionTitle: "미뤄둔 대화 5분만 시도", actionHowTo: "0~1분 미뤄둔 대화 1개 정하기 · 1~5분 타이머 5분만 시도 · 끝나면 다음 단계 한 줄.", actionMinutes: 5, videoReason: "불편 감정 명상." },
    { mission: "도움 요청", actionTitle: "배우자·가족에게 역할 분담 요청", actionHowTo: "0~1분 분담받을 1가지 정하기 · 1~3분 '___ 좀 맡아줄 수 있어?' 한 문장 · 3~4분 직접 또는 메시지.", actionMinutes: 4, videoReason: "명상." },
    { mission: "감정 강도 진단", actionTitle: "훈육 감정 0~10 강도", actionHowTo: "0~1분 가장 강한 훈육 감정 1개 · 1~3분 단어 + 0~10 + 신체 위치 · 3~5분 4-4-6 호흡 5번.", actionMinutes: 5, videoReason: "RAIN 명상." },
    { mission: "자기 친절", actionTitle: "오늘 잘한 양육 1개 자기 칭찬", actionHowTo: "0~1분 오늘 양육 한 장면 떠올리기 · 1~2분 잘한 1개 기록 · 2~3분 '잘했어, ___' 한 문장.", actionMinutes: 3, videoReason: "자애 명상." },
    { mission: "환경 1개 손보기", actionTitle: "대화 환경 1개 5분 조정", actionHowTo: "0~1분 식탁·거실·차 안 중 1곳 정하기 · 1~5분 휴대폰 위치·TV 끄기 등 5분 안에 가능한 변경 1개.", actionMinutes: 5, videoReason: "긍정확언." },
    { mission: "3주차 진단", actionTitle: "회복탄력성 진단 (3주차)", actionHowTo: "0~1분 /assessment/resilience 열기 · 1~6분 응답 · 6~7분 변화 한 줄.", actionMinutes: 7, videoReason: "3주 마무리." },
    { mission: "워크북 심화", actionTitle: "반복 훈육 패턴 1개 3층 분해", actionHowTo: "0~1분 가장 자주 반복되는 훈육 1개 선정 · 1~5분 '상황·내 반응·아이 반응' 3층 분해 · 5~8분 각 층 대안 1개.", actionMinutes: 8, videoReason: "마음 비우기." },
    { mission: "코파일럿 1:1", actionTitle: "훈육 주제 1개 코파일럿 입력", actionHowTo: "0~1분 코파일럿 열기 · 1~3분 '요즘 아이와 ___' 한 문장 입력 · 3~6분 답변 중 1개 워크북 옮기기.", actionMinutes: 6, videoReason: "5분 아침명상." },
    { mission: "재발 방지", actionTitle: "폭발 신호 1줄", actionHowTo: "0~1분 최근 폭발 직전 떠올리기 · 1~3분 '___ 신호가 오면 ___ 한다' 작성 · 3~5분 메모 고정.", actionMinutes: 5, videoReason: "알아차림 명상." },
    { mission: "핵심 루틴 고정", actionTitle: "애착 루틴 TOP 3 시각 부여", actionHowTo: "0~1분 효과 컸던 애착 루틴 3개 · 1~4분 시각 부여(예: 아침 인사·저녁 책읽기) · 4~6분 알람 3개 등록.", actionMinutes: 6, videoReason: "데일리 명상." },
    { mission: "관계 1순위", actionTitle: "아이와 1:1 10분 확보", actionHowTo: "0~1분 오늘 1:1 시각 정하기 · 1~9분 휴대폰 끄고 아이 주도 활동 9분 · 9~10분 끝나고 한 줄 메모.", actionMinutes: 5, videoReason: "이완명상." },
    { mission: "거절 문장", actionTitle: "아이 보호 거절 1개", actionHowTo: "0~1분 외부의 비교·압박 1개 정하기 · 1~3분 '우리 가족은 ___ 방식이에요' 한 문장 · 3~4분 메모 저장.", actionMinutes: 4, videoReason: "이완명상." },
    { mission: "4주차 요약", actionTitle: "4주 동안 아이와 ___ 변했다", actionHowTo: "0~1분 1·4주차 노트 비교 · 1~3분 한 문장 요약 · 3~5분 다음 달 핵심 1개 표시.", actionMinutes: 5, videoReason: "마무리 명상." },
    { mission: "최종 진단", actionTitle: "우울감 최종 진단 (Day 2 반복)", actionHowTo: "0~1분 /depression-package 열기 · 1~5분 응답 · 5~6분 30일 그래프 저장.", actionMinutes: 6, videoReason: "마음 정리." },
    { mission: "30일 선언문", actionTitle: "'아이와 ___한 부모'", actionHowTo: "0~1분 30일 변화 떠올리기 · 1~3분 '나는 아이와 ___한 부모이다' 한 문장 · 3~5분 잠금화면 메모.", actionMinutes: 5, videoReason: "마무리 명상." },
  ],
};

export function getTrackDailyContent(focusId: MindTrackFocusId, day: number): MindTrackDailyContent {
  const safeDay = Math.max(1, Math.min(30, day));
  const days = TRACK_DAYS[focusId];
  const def = days[safeDay - 1];
  const pool = VIDEO_POOLS[focusId];
  const video = { ...pool[(safeDay - 1) % pool.length], reason: def.videoReason };
  const assessment = ASSESSMENT_DAYS[safeDay] ?? null;
  return {
    day: safeDay,
    assessment,
    video,
    action: { title: def.actionTitle, howTo: def.actionHowTo, minutes: def.actionMinutes },
  };
}

/** 트랙별 mission 라벨만 가져오기 (대시보드 카드 헤더용). */
export function getTrackMissionLabel(focusId: MindTrackFocusId, day: number): string {
  const safeDay = Math.max(1, Math.min(30, day));
  return TRACK_DAYS[focusId][safeDay - 1].mission;
}

export const TRACK_CONTENT_VERSION = '2026.05-v1';
