/**
 * 트랙별 30일 큐레이션 매트릭스 — 9개 트랙 × 30일 = 270개 콘텐츠 슬롯
 *
 * 자동 생성 (scripts/gen_tracks.py). 수동 편집 시 각 트랙의 days[] 30개,
 * VIDEO_POOLS의 검증된 영상 ID만 사용하세요. 영상은 admin override
 * (mind_track_daily_content_overrides) 로 즉시 교체 가능합니다.
 */

import type {
  MindTrackDailyContent,
} from './mindTrackDailyContent';
import type { MindTrackFocusId } from './mindTrackFocusTracks';

type VideoPick = MindTrackDailyContent['video'];

const VIDEO_POOLS: Record<MindTrackFocusId, VideoPick[]> = {
  sleep: [
    { videoId: "c9W414XrdF0", title: "밤 명상 — 잠들기 전 하루를 마무리 하는 고요한 시간", channel: "명상하는그녀_내안의별", durationLabel: "10분", reason: '' },
    { videoId: "inxAScz0PTM", title: "누워서 하는 10분 명상 — 호흡명상 가이드", channel: "에일린 mind yoga", durationLabel: "10분", reason: '' },
    { videoId: "NsVVO9hnCJ4", title: "완벽한 피로회복 효과 이완명상", channel: "에일린 mind yoga", durationLabel: "15분", reason: '' },
    { videoId: "ZcEBlA-9r9k", title: "마음이 편안해지는 10분 명상 가이드", channel: "에일린 mind yoga", durationLabel: "10분", reason: '' },
    { videoId: "dZewQEbQQM0", title: "5분 호흡명상 — 뇌를 위한 최고의 휴식법", channel: "에일린 mind yoga", durationLabel: "5분", reason: '' },
    { videoId: "yiysD0Jl2Wo", title: "명상이 필요할 때 10분 명상 가이드", channel: "에일린 mind yoga", durationLabel: "10분", reason: '' },
    { videoId: "GBBh694I1bw", title: "쉽게 배워보는 마음챙김 명상 \"바디스캔\"", channel: "한국MBSR마음챙김연구소", durationLabel: "15분", reason: '' },
  ],
  stress: [
    { videoId: "TGoAN5L_oPI", title: "5분 마음챙김 명상 — 마음을 다스리는 호흡", channel: "에일린 mind yoga", durationLabel: "5분", reason: '' },
    { videoId: "dZewQEbQQM0", title: "5분 호흡명상 — 뇌를 위한 최고의 휴식법", channel: "에일린 mind yoga", durationLabel: "5분", reason: '' },
    { videoId: "XgVjs-WeBWY", title: "불안하고 생각이 많을 때 즉시 도움되는 10분 호흡명상", channel: "마보TV", durationLabel: "10분", reason: '' },
    { videoId: "QN9v0nkmR_o", title: "박스 호흡법 따라해보세요", channel: "세바시 인생질문", durationLabel: "4분", reason: '' },
    { videoId: "NKoiz6YtlRE", title: "생각이 많아질 때 멈추는 호흡법", channel: "헤럴드TV", durationLabel: "5분", reason: '' },
    { videoId: "GQgjJUN02u4", title: "스트레스 관리 — 알아차림 명상", channel: "명상상담 Meditation TV", durationLabel: "12분", reason: '' },
    { videoId: "Lllh4HdUMvk", title: "회복탄력성 향상법 두 가지 — 김주환 교수", channel: "김주환의 내면소통", durationLabel: "12분", reason: '' },
  ],
  mood: [
    { videoId: "3hyTLOCQFTE", title: "감정 라벨링의 힘", channel: "모찌 심리학", durationLabel: "7분", reason: '' },
    { videoId: "wQfWgYCMeLw", title: "내 몸 안에서 감정 느끼고 흘려보내기 명상", channel: "마인드풀tv", durationLabel: "10분", reason: '' },
    { videoId: "YkFiiNBo6O0", title: "나를 사랑하는 연습 — 자애 명상", channel: "마보TV", durationLabel: "10분", reason: '' },
    { videoId: "TtTbhde9A3E", title: "감정을 피하지 않고 마주하는 RAIN 자기돌봄 명상", channel: "숲의그림자MindfulDay", durationLabel: "15분", reason: '' },
    { videoId: "hTSLx_wCQjU", title: "불편한 감정을 건강히 다루는 명상", channel: "숨쉬는고래", durationLabel: "12분", reason: '' },
    { videoId: "xeul9fEvo-Q", title: "7분 긍정확언 — 나는 결국 잘될 것이다", channel: "에일린 mind yoga", durationLabel: "7분", reason: '' },
    { videoId: "RptypCXGN-c", title: "매일 아침 따라 해보세요 — 10분 긍정확언", channel: "마음빛 글", durationLabel: "10분", reason: '' },
  ],
  focus: [
    { videoId: "Uuq4OME-7-M", title: "인생을 성공으로 이끄는 5초 법칙 — 멜 로빈스", channel: "잭스파이어", durationLabel: "8분", reason: '' },
    { videoId: "Bcs33wFg-KA", title: "회피형 성격 극복 방법 — 회피의 과학", channel: "장동선의 궁금한 뇌", durationLabel: "12분", reason: '' },
    { videoId: "6Qu5E3MrVH8", title: "5분 명상 — 인생을 180도 바꾸는 습관", channel: "에일린 mind yoga", durationLabel: "5분", reason: '' },
    { videoId: "LaM3-_ntnjU", title: "복잡한 생각, 5분 만에 정리하는 빼기명상", channel: "마음수련 명상", durationLabel: "5분", reason: '' },
    { videoId: "cvPS_25gRPs", title: "생각 비우기 명상", channel: "에일린 mind yoga", durationLabel: "10분", reason: '' },
    { videoId: "PIoK5ZdYk6E", title: "5분 아침명상", channel: "에일린 mind yoga", durationLabel: "5분", reason: '' },
    { videoId: "0KROAacWzEA", title: "진정한 명상은 생각을 쉬게하는 것", channel: "용수스님의렛고명상", durationLabel: "10분", reason: '' },
  ],
  relationship: [
    { videoId: "Oo43FrfVXOk", title: "거절은 다정한 경계", channel: "행복한 오늘", durationLabel: "8분", reason: '' },
    { videoId: "Tiwk1f6ZS9Y", title: "회피형 성격의 인생이 꼬이는 이유 & 극복법", channel: "희렌최널", durationLabel: "12분", reason: '' },
    { videoId: "inxAScz0PTM", title: "누워서 하는 10분 호흡명상", channel: "에일린 mind yoga", durationLabel: "10분", reason: '' },
    { videoId: "NsVVO9hnCJ4", title: "완벽한 피로회복 이완명상", channel: "에일린 mind yoga", durationLabel: "15분", reason: '' },
    { videoId: "YkFiiNBo6O0", title: "나를 사랑하는 연습 — 자애 명상", channel: "마보TV", durationLabel: "10분", reason: '' },
    { videoId: "3hyTLOCQFTE", title: "감정 라벨링의 힘", channel: "모찌 심리학", durationLabel: "7분", reason: '' },
    { videoId: "NKoiz6YtlRE", title: "생각이 많아질 때 멈추는 호흡법", channel: "헤럴드TV", durationLabel: "5분", reason: '' },
  ],
  self: [
    { videoId: "Lllh4HdUMvk", title: "회복탄력성 향상법 두 가지 — 김주환 교수", channel: "김주환의 내면소통", durationLabel: "12분", reason: '' },
    { videoId: "0KROAacWzEA", title: "진정한 명상은 생각을 쉬게하는 것", channel: "용수스님의렛고명상", durationLabel: "10분", reason: '' },
    { videoId: "LaM3-_ntnjU", title: "복잡한 생각, 5분 만에 정리하는 빼기명상", channel: "마음수련 명상", durationLabel: "5분", reason: '' },
    { videoId: "YkFiiNBo6O0", title: "나를 사랑하는 연습 — 자애 명상", channel: "마보TV", durationLabel: "10분", reason: '' },
    { videoId: "xeul9fEvo-Q", title: "7분 긍정확언", channel: "에일린 mind yoga", durationLabel: "7분", reason: '' },
    { videoId: "ZcEBlA-9r9k", title: "마음이 편안해지는 10분 명상 가이드", channel: "에일린 mind yoga", durationLabel: "10분", reason: '' },
    { videoId: "3hyTLOCQFTE", title: "감정 라벨링의 힘", channel: "모찌 심리학", durationLabel: "7분", reason: '' },
  ],
  parenting: [
    { videoId: "YkFiiNBo6O0", title: "나를 사랑하는 연습 — 자애 명상", channel: "마보TV", durationLabel: "10분", reason: '' },
    { videoId: "NsVVO9hnCJ4", title: "완벽한 피로회복 이완명상", channel: "에일린 mind yoga", durationLabel: "15분", reason: '' },
    { videoId: "hTSLx_wCQjU", title: "불편한 감정을 건강히 다루는 명상", channel: "숨쉬는고래", durationLabel: "12분", reason: '' },
    { videoId: "dZewQEbQQM0", title: "5분 호흡명상 — 뇌를 위한 휴식", channel: "에일린 mind yoga", durationLabel: "5분", reason: '' },
    { videoId: "inxAScz0PTM", title: "누워서 하는 10분 호흡명상", channel: "에일린 mind yoga", durationLabel: "10분", reason: '' },
    { videoId: "xeul9fEvo-Q", title: "7분 긍정확언", channel: "에일린 mind yoga", durationLabel: "7분", reason: '' },
    { videoId: "c9W414XrdF0", title: "밤 명상 — 잠들기 전 하루 마무리", channel: "명상하는그녀_내안의별", durationLabel: "10분", reason: '' },
  ],
  child_development: [
    { videoId: "Lllh4HdUMvk", title: "회복탄력성 — 김주환 교수", channel: "김주환의 내면소통", durationLabel: "12분", reason: '' },
    { videoId: "3hyTLOCQFTE", title: "감정 라벨링의 힘", channel: "모찌 심리학", durationLabel: "7분", reason: '' },
    { videoId: "Bcs33wFg-KA", title: "회피의 과학 — 장동선의 궁금한 뇌", channel: "장동선의 궁금한 뇌", durationLabel: "12분", reason: '' },
    { videoId: "YkFiiNBo6O0", title: "자애 명상 — 부모의 마음 자원 채우기", channel: "마보TV", durationLabel: "10분", reason: '' },
    { videoId: "dZewQEbQQM0", title: "5분 호흡명상", channel: "에일린 mind yoga", durationLabel: "5분", reason: '' },
    { videoId: "PIoK5ZdYk6E", title: "5분 아침명상", channel: "에일린 mind yoga", durationLabel: "5분", reason: '' },
    { videoId: "ZcEBlA-9r9k", title: "편안해지는 10분 명상", channel: "에일린 mind yoga", durationLabel: "10분", reason: '' },
  ],
  family_communication: [
    { videoId: "Oo43FrfVXOk", title: "거절은 다정한 경계 — 양육에 적용", channel: "행복한 오늘", durationLabel: "8분", reason: '' },
    { videoId: "3hyTLOCQFTE", title: "감정 라벨링의 힘", channel: "모찌 심리학", durationLabel: "7분", reason: '' },
    { videoId: "NKoiz6YtlRE", title: "생각이 많아질 때 멈추는 호흡법", channel: "헤럴드TV", durationLabel: "5분", reason: '' },
    { videoId: "YkFiiNBo6O0", title: "자애 명상 — 부모-아이 관계", channel: "마보TV", durationLabel: "10분", reason: '' },
    { videoId: "hTSLx_wCQjU", title: "불편한 감정을 건강히 다루는 명상", channel: "숨쉬는고래", durationLabel: "12분", reason: '' },
    { videoId: "TtTbhde9A3E", title: "RAIN 자기돌봄 명상", channel: "숲의그림자MindfulDay", durationLabel: "15분", reason: '' },
    { videoId: "xeul9fEvo-Q", title: "긍정확언 — 부모의 자기 강화", channel: "에일린 mind yoga", durationLabel: "7분", reason: '' },
  ],
};

export const ASSESSMENT_DAYS: Record<number, MindTrackDailyContent['assessment']> = {
  1: { route: "/stress-package", title: "스트레스 베이스라인 진단", desc: "오늘의 긴장도 · 회복 여력을 객관 점수로 측정", minutes: 5, why: "30일 변화 그래프의 0번째 점이 됩니다." },
  2: { route: "/depression-package", title: "마음 무게 진단", desc: "최근 2주 마음의 무게를 단계별로 짚어봐요", minutes: 6, why: "미션을 더 정확히 맞춤화하기 위해 두 번째 층을 확인합니다." },
  7: { route: "/assessment/resilience", title: "회복탄력성 1주차 진단", desc: "한 주 변화를 회복력 관점에서 측정", minutes: 7, why: "1주간 데이터를 진단 점수와 합쳐 첫 주간 인사이트가 만들어집니다." },
  10: { route: "/anxiety-package", title: "불안 결 진단", desc: "내 패턴이 가장 떨어지는 시간대를 진단으로 짚어요", minutes: 6, why: "골든타임을 정하기 전 패턴을 확인합니다." },
  14: { route: "/stress-package", title: "스트레스 진단 (2주차)", desc: "Day 1과 같은 진단을 다시 하고 변화량을 그래프로", minutes: 5, why: "시작 점수와 똑같은 측정을 해야 변화 그래프가 만들어집니다." },
  18: { route: "/anxiety-package", title: "감정 강도 진단", desc: "오늘 가장 강한 감정의 강도를 0~10으로 측정", minutes: 5, why: "감정 강도 다루기 미션의 베이스라인이 됩니다." },
  21: { route: "/assessment/resilience", title: "회복탄력성 3주차 진단", desc: "3주간의 패턴 전환이 회복력에 미친 영향 측정", minutes: 7, why: "3주차 코칭 인사이트의 핵심 데이터가 됩니다." },
  26: { route: "/relationship-package", title: "관계 패턴 진단", desc: "관계 회복의 한 걸음 전, 내 관계 패턴 측정", minutes: 7, why: "관계 회복 미션이 더 정확해지도록 패턴을 객관화합니다." },
  29: { route: "/depression-package", title: "우울감 최종 진단", desc: "Day 2와 같은 진단을 다시 — 30일 변화 그래프 완성", minutes: 6, why: "내일의 종합 리포트가 정확해지려면 마지막 측정이 필요해요." },
};

export interface DayDef {
  mission: string;
  actionTitle: string;
  actionHowTo: string;
  actionMinutes: number;
  videoReason: string;
}

export const TRACK_DAYS: Record<MindTrackFocusId, DayDef[]> = {
  sleep: [
    { mission: "취침·기상 시각 기록", actionTitle: "오늘 수면 시각 기록", actionHowTo: "어젯밤 잠든 시각 / 오늘 일어난 시각을 적어요.", actionMinutes: 3, videoReason: "수면 베이스라인 직후 가장 가벼운 호흡 루틴." },
    { mission: "수면 환경 점검", actionTitle: "침실 조도·온도 1가지 손보기", actionHowTo: "조명을 한 단계 낮추거나 실내온도를 1도 조정.", actionMinutes: 4, videoReason: "취침 전 자극을 줄이는 호흡법." },
    { mission: "카페인 컷오프 시간 정하기", actionTitle: "오후 2시 이후 카페인 끊기", actionHowTo: "오늘 카페인 마감 시간을 기록하고 지켜요.", actionMinutes: 3, videoReason: "각성 신호를 누그러뜨리는 명상." },
    { mission: "스크린 타임 제한", actionTitle: "취침 60분 전 화면 끄기 알람 설정", actionHowTo: "스마트폰 알람을 취침 60분 전으로 설정.", actionMinutes: 3, videoReason: "잠들기 전 마음을 차분히 정리." },
    { mission: "취침 1시간 전 루틴 1개", actionTitle: "따뜻한 물로 손·발 씻기", actionHowTo: "30초 따뜻한 물로 손·발을 씻고 가볍게 닦아요.", actionMinutes: 4, videoReason: "각성된 신경을 가라앉히는 5분 호흡." },
    { mission: "호흡으로 잠들기 시도", actionTitle: "4-7-8 호흡 5세트", actionHowTo: "4초 들이쉬고 7초 멈추고 8초 내쉬기 × 5번.", actionMinutes: 5, videoReason: "잠 들기 직전 누워 따라하기 좋은 가이드." },
    { mission: "1주차 수면 회고", actionTitle: "가장 잘 잔 날 1개 메모", actionHowTo: "가장 잘 잔 날과 그날의 행동 1가지를 기록.", actionMinutes: 4, videoReason: "1주 흐름을 정리하는 명상." },
    { mission: "저녁 운동 강도 낮추기", actionTitle: "저녁 가벼운 산책 10분", actionHowTo: "해가 진 뒤 가벼운 산책으로 마무리.", actionMinutes: 5, videoReason: "부교감 신경을 활성화하는 호흡." },
    { mission: "취침 직전 생각 비우기", actionTitle: "'내일 할 일' 3개 적고 덮기", actionHowTo: "머릿속 일들을 종이에 옮기고 노트북·종이 덮기.", actionMinutes: 4, videoReason: "생각의 자동재생을 멈추는 가이드." },
    { mission: "수면 중간 깸 대처", actionTitle: "깼을 때 시계 안 보기 규칙", actionHowTo: "깨도 시계를 보지 않고 호흡 5세트.", actionMinutes: 3, videoReason: "한밤중에도 적용 가능한 호흡법." },
    { mission: "아침 햇빛 받기", actionTitle: "기상 후 10분 내 햇빛", actionHowTo: "커튼 열고 햇빛 5분 받으며 깊은 호흡.", actionMinutes: 5, videoReason: "수면-각성 리듬을 맞춰주는 명상." },
    { mission: "취침 알람 자동화", actionTitle: "'잠 준비 알람' 설정", actionHowTo: "매일 같은 시각 잠 준비 알람을 휴대폰에 등록.", actionMinutes: 3, videoReason: "취침 직전 짧은 호흡 가이드." },
    { mission: "저녁 식사 시간 고정", actionTitle: "저녁을 평소보다 30분 일찍", actionHowTo: "오늘은 평소보다 30분 일찍 식사를 마쳐요.", actionMinutes: 4, videoReason: "위장 부담을 줄여 더 잘 자도록 돕는 명상." },
    { mission: "2주차 비교 측정", actionTitle: "스트레스 진단 다시 하기", actionHowTo: "Day 1과 동일 진단을 반복.", actionMinutes: 6, videoReason: "중간 점검 직후 차분히 마음을 가라앉히는 호흡." },
    { mission: "효과 있던 루틴 강화", actionTitle: "TOP 2 루틴 다시 실행", actionHowTo: "지금까지 가장 효과있던 2가지를 오늘 다시.", actionMinutes: 6, videoReason: "15일차의 정체감을 통과하는 짧은 명상." },
    { mission: "취침 전 글쓰기", actionTitle: "오늘 감사한 일 1개", actionHowTo: "감사한 일 1개를 1문장으로 적고 잠.", actionMinutes: 4, videoReason: "마음을 비워 잘 잠들도록 돕는 명상." },
    { mission: "주말 수면 보정", actionTitle: "주말도 평일과 동일 시각 기상", actionHowTo: "평일과 같은 시각에 일어나기.", actionMinutes: 3, videoReason: "리듬을 깨지 않는 짧은 호흡." },
    { mission: "수면 강도 진단", actionTitle: "오늘 수면의 질 0~10 기록", actionHowTo: "어젯밤 수면을 0~10으로 기록.", actionMinutes: 4, videoReason: "수면 패턴을 객관화하는 명상." },
    { mission: "자기 친절 한 줄", actionTitle: "'잘 자고 있어' 자기 칭찬", actionHowTo: "자신에게 한 문장 칭찬.", actionMinutes: 3, videoReason: "자기 친절의 한국어 가이드." },
    { mission: "환경 1개 더 손보기", actionTitle: "베개·이불 중 1개 점검", actionHowTo: "베개 높이/이불 두께를 점검.", actionMinutes: 5, videoReason: "이완 효과가 큰 가이드 명상." },
    { mission: "3주차 진단", actionTitle: "회복탄력성 진단", actionHowTo: "3주간 변화를 회복력 관점에서 측정.", actionMinutes: 7, videoReason: "3주차 마무리 명상." },
    { mission: "워크북 심화 1개", actionTitle: "수면-에너지 관계 작성", actionHowTo: "'잘 잔 날 vs 못 잔 날' 차이 3줄.", actionMinutes: 8, videoReason: "맞춤 워크북 심화 직전 마음 비우기." },
    { mission: "코파일럿 1:1", actionTitle: "오늘 수면 주제 1개 던지기", actionHowTo: "'잠을 깊게 자려면 ___ 가 필요해요' 입력.", actionMinutes: 6, videoReason: "코파일럿 직전 차분한 명상." },
    { mission: "재발 방지 신호", actionTitle: "'수면 무너질 때 신호' 1줄", actionHowTo: "'___ 신호가 오면 ___ 한다' 작성.", actionMinutes: 5, videoReason: "재발 방지 알아차림 명상." },
    { mission: "핵심 루틴 고정", actionTitle: "수면 루틴 TOP 3 시각 고정", actionHowTo: "핵심 3가지에 시각을 부여.", actionMinutes: 6, videoReason: "매일 짧게 — 데일리 명상." },
    { mission: "관계 패턴 점검", actionTitle: "수면을 방해하는 관계 1개", actionHowTo: "수면을 방해하는 1가지를 적어요.", actionMinutes: 6, videoReason: "마음을 정렬하는 호흡 명상." },
    { mission: "거절 문장 1개", actionTitle: "'늦은 약속 거절' 템플릿", actionHowTo: "거절 문장 1개를 미리 작성.", actionMinutes: 4, videoReason: "두려움을 내려놓는 이완명상." },
    { mission: "4주차 요약", actionTitle: "'4주 동안 수면이 ___ 변했다'", actionHowTo: "한 문장으로 정리.", actionMinutes: 5, videoReason: "리포트 직전 마무리 명상." },
    { mission: "최종 진단", actionTitle: "우울감 최종 진단", actionHowTo: "Day 2와 같은 진단 반복.", actionMinutes: 6, videoReason: "리포트 직전 마음 정리." },
    { mission: "30일 선언문", actionTitle: "'나는 ___한 수면을 가진 사람'", actionHowTo: "선언문 1문장.", actionMinutes: 5, videoReason: "30일을 차분히 마무리하는 명상." },
  ],
  stress: [
    { mission: "긴장 베이스라인", actionTitle: "4-4-6 호흡 1세트", actionHowTo: "4초 들이쉬고 4초 멈추고 6초 내쉬기 × 5.", actionMinutes: 3, videoReason: "베이스라인 직후 가장 가벼운 진정 루틴." },
    { mission: "내 스트레스 신호 3개", actionTitle: "신호 단어 3개 적기", actionHowTo: "어깨/턱/속 등 신체 신호 3개.", actionMinutes: 4, videoReason: "몸의 긴장을 풀어주는 명상." },
    { mission: "스트레스 강도 0~10", actionTitle: "오늘 가장 강했던 순간 기록", actionHowTo: "순간 + 강도 1줄.", actionMinutes: 4, videoReason: "긴장 직후 빠른 호흡 가이드." },
    { mission: "바디스캔 1회", actionTitle: "어깨·턱 풀기", actionHowTo: "눈감고 머리부터 발끝까지 긴장 풀기.", actionMinutes: 5, videoReason: "바디스캔 한국어 가이드." },
    { mission: "5초 마이크로 결정", actionTitle: "미루던 5분 일 처리", actionHowTo: "5분이면 끝나는 한 가지를 즉시.", actionMinutes: 5, videoReason: "행동 시작의 심리적 장벽 영상." },
    { mission: "에너지 도둑 1개", actionTitle: "줄일 한 가지 정하기", actionHowTo: "에너지 도둑 1개와 줄일 방법 1줄.", actionMinutes: 4, videoReason: "다정한 경계의 언어 영상." },
    { mission: "1주차 진단", actionTitle: "회복탄력성 진단", actionHowTo: "한 주 변화를 회복력 관점에서 측정.", actionMinutes: 7, videoReason: "1주차 정리 영상." },
    { mission: "호흡 강화", actionTitle: "박스호흡 4-4-4-4", actionHowTo: "아침·점심·저녁 1세트씩.", actionMinutes: 6, videoReason: "박스호흡 가이드." },
    { mission: "자동사고 멈추기", actionTitle: "'멈춤' 한 단어 + 호흡", actionHowTo: "반복 생각 → 멈춤 → 4-4-6.", actionMinutes: 3, videoReason: "생각 비우기 명상." },
    { mission: "스트레스 패턴 진단", actionTitle: "불안 결 진단", actionHowTo: "스트레스 패턴 객관화.", actionMinutes: 6, videoReason: "불안 호흡 가이드." },
    { mission: "최근 갈등 1장면", actionTitle: "사실 1문장 묘사", actionHowTo: "최근 한 장면을 사실 그대로.", actionMinutes: 5, videoReason: "호흡으로 반응 멈추기." },
    { mission: "호흡 분산 적용", actionTitle: "아침/점심/저녁 1세트", actionHowTo: "틈마다 박스호흡.", actionMinutes: 6, videoReason: "박스호흡 가이드." },
    { mission: "자유 기록 5분", actionTitle: "손 멈추지 말고 적기", actionHowTo: "타이머 5분, 멈추지 않고.", actionMinutes: 5, videoReason: "저널링 직전 호흡." },
    { mission: "2주차 비교", actionTitle: "스트레스 진단 반복", actionHowTo: "Day 1과 같은 진단.", actionMinutes: 5, videoReason: "2주차 변화 직전 호흡." },
    { mission: "루틴 TOP 3 강화", actionTitle: "효과있던 3가지 다시", actionHowTo: "오늘 다시 실행.", actionMinutes: 6, videoReason: "15일차 통과 명상." },
    { mission: "회피 마주하기", actionTitle: "미뤄둔 일 5분만", actionHowTo: "타이머 5분만, 멈춰도 OK.", actionMinutes: 5, videoReason: "회피의 과학 영상." },
    { mission: "도움 요청", actionTitle: "'좀 도와줄 수 있어?'", actionHowTo: "한 사람에게 메시지.", actionMinutes: 4, videoReason: "도움 요청 장벽 낮추기." },
    { mission: "감정 강도 진단", actionTitle: "감정 강도 0~10", actionHowTo: "가장 강한 감정 1개.", actionMinutes: 5, videoReason: "강도 객관화 명상." },
    { mission: "자기 친절", actionTitle: "오늘 잘한 일 1개 칭찬", actionHowTo: "1문장 자기 칭찬.", actionMinutes: 3, videoReason: "자애 명상." },
    { mission: "환경 1개 손보기", actionTitle: "책상·휴대폰·소파 중 1개", actionHowTo: "위치/설정 5분 안에 변경.", actionMinutes: 5, videoReason: "긍정확언 영상." },
    { mission: "3주차 진단", actionTitle: "회복탄력성 진단", actionHowTo: "3주간 패턴 변화 측정.", actionMinutes: 7, videoReason: "3주차 마무리 명상." },
    { mission: "워크북 심화 1개", actionTitle: "스트레스 트리거 분해", actionHowTo: "트리거 1개를 3층으로.", actionMinutes: 8, videoReason: "마음 비우기 명상." },
    { mission: "코파일럿 1:1", actionTitle: "오늘 주제 1개 던지기", actionHowTo: "'요즘 ___ 때문에 ___' 입력.", actionMinutes: 6, videoReason: "코파일럿 직전 명상." },
    { mission: "재발 방지 신호", actionTitle: "'스트레스 무너질 때 신호'", actionHowTo: "'___ → ___' 1문장.", actionMinutes: 5, videoReason: "알아차림 명상." },
    { mission: "핵심 루틴 고정", actionTitle: "TOP 3에 시간 부여", actionHowTo: "각 시간대 정해 고정.", actionMinutes: 6, videoReason: "데일리 명상." },
    { mission: "관계 패턴 진단", actionTitle: "관계 패턴 진단", actionHowTo: "스트레스 유발 관계 점검.", actionMinutes: 7, videoReason: "호흡명상." },
    { mission: "거절 문장 1개", actionTitle: "거절 템플릿 작성", actionHowTo: "미리 1개 만들어두기.", actionMinutes: 4, videoReason: "이완명상." },
    { mission: "4주차 요약", actionTitle: "'4주 동안 ___'", actionHowTo: "한 문장 요약.", actionMinutes: 5, videoReason: "마무리 명상." },
    { mission: "최종 진단", actionTitle: "우울감 최종 진단", actionHowTo: "Day 2 동일 진단 반복.", actionMinutes: 6, videoReason: "리포트 직전 정렬." },
    { mission: "30일 선언문", actionTitle: "'스트레스를 ___하는 사람'", actionHowTo: "선언문 1문장.", actionMinutes: 5, videoReason: "마무리 명상." },
  ],
  mood: [
    { mission: "감정 베이스라인", actionTitle: "오늘 감정 단어 3개", actionHowTo: "감정을 단어 3개로 분리.", actionMinutes: 4, videoReason: "감정 라벨링의 신경과학." },
    { mission: "감정 강도 기록", actionTitle: "0~10 강도 기록", actionHowTo: "가장 강한 감정 + 강도.", actionMinutes: 4, videoReason: "감정을 흘려보내는 명상." },
    { mission: "감정-신체 연결", actionTitle: "감정 → 신체 위치", actionHowTo: "느낀 감정의 위치 1줄.", actionMinutes: 4, videoReason: "몸 안에서 감정 느끼기." },
    { mission: "자기자비 한 줄", actionTitle: "'친구라면 뭐라할까'", actionHowTo: "친한 친구처럼 위로 1문장.", actionMinutes: 3, videoReason: "자애 명상." },
    { mission: "RAIN 1회", actionTitle: "Recognize-Allow-Investigate-Nurture", actionHowTo: "RAIN 4단계 따라하기.", actionMinutes: 6, videoReason: "RAIN 명상." },
    { mission: "감정 일기 5분", actionTitle: "오늘의 감정 흐름", actionHowTo: "아침-점심-저녁 흐름 1줄씩.", actionMinutes: 5, videoReason: "감정 흘려보내기." },
    { mission: "1주차 진단", actionTitle: "회복탄력성 진단", actionHowTo: "1주차 측정.", actionMinutes: 7, videoReason: "회복력 영상." },
    { mission: "긍정 확언 1회", actionTitle: "아침 확언 따라하기", actionHowTo: "영상 따라 1회 확언.", actionMinutes: 7, videoReason: "긍정확언 영상." },
    { mission: "감정 거리두기", actionTitle: "'나는 ___을 느낀다'", actionHowTo: "'나는 슬프다' → '나는 슬픔을 느낀다'.", actionMinutes: 3, videoReason: "생각 비우기 명상." },
    { mission: "감정 패턴 진단", actionTitle: "불안 결 진단", actionHowTo: "감정 패턴 객관화.", actionMinutes: 6, videoReason: "호흡명상." },
    { mission: "자기 친절 편지", actionTitle: "나에게 짧은 편지", actionHowTo: "3줄 편지를 자신에게.", actionMinutes: 5, videoReason: "자애 명상." },
    { mission: "감정 발산 안전한 방법", actionTitle: "글쓰기/그림/노래 1개", actionHowTo: "5분간 자유롭게.", actionMinutes: 5, videoReason: "호흡으로 마음 정렬." },
    { mission: "자유 기록 5분", actionTitle: "감정 그대로 적기", actionHowTo: "타이머 5분.", actionMinutes: 5, videoReason: "저널링 전 명상." },
    { mission: "2주차 비교", actionTitle: "스트레스 진단 반복", actionHowTo: "변화 측정.", actionMinutes: 5, videoReason: "2주차 명상." },
    { mission: "효과있던 루틴 강화", actionTitle: "TOP 3 다시", actionHowTo: "오늘 다시 실행.", actionMinutes: 6, videoReason: "15일차 명상." },
    { mission: "부정 감정 마주하기", actionTitle: "피하던 감정 1개 이름붙이기", actionHowTo: "피하던 감정 1개 적기.", actionMinutes: 5, videoReason: "불편한 감정 명상." },
    { mission: "감사 일기", actionTitle: "오늘 감사 3개", actionHowTo: "구체적 3가지.", actionMinutes: 4, videoReason: "긍정확언 영상." },
    { mission: "감정 강도 진단", actionTitle: "감정 강도 0~10", actionHowTo: "가장 강한 감정.", actionMinutes: 5, videoReason: "RAIN 명상." },
    { mission: "자기 칭찬", actionTitle: "잘한 일 1개 + 칭찬", actionHowTo: "자기 칭찬 1문장.", actionMinutes: 3, videoReason: "자애 명상." },
    { mission: "감정 환경 점검", actionTitle: "감정 자극 1개 줄이기", actionHowTo: "SNS/뉴스 시간 단축.", actionMinutes: 5, videoReason: "긍정확언." },
    { mission: "3주차 진단", actionTitle: "회복탄력성 진단", actionHowTo: "3주차 측정.", actionMinutes: 7, videoReason: "3주 마무리 명상." },
    { mission: "워크북 심화", actionTitle: "감정 패턴 분석", actionHowTo: "반복 감정 1개 작성.", actionMinutes: 8, videoReason: "마음 비우기." },
    { mission: "코파일럿 1:1", actionTitle: "감정 주제 1개", actionHowTo: "'요즘 ___ 감정이 자주' 입력.", actionMinutes: 6, videoReason: "명상." },
    { mission: "재발 방지", actionTitle: "'감정 폭풍 신호'", actionHowTo: "'___ → ___' 작성.", actionMinutes: 5, videoReason: "알아차림 명상." },
    { mission: "핵심 루틴 고정", actionTitle: "감정 회복 루틴 TOP 3", actionHowTo: "시간대 부여.", actionMinutes: 6, videoReason: "데일리 명상." },
    { mission: "관계 점검", actionTitle: "감정 영향 관계 1개", actionHowTo: "관계 1개 적기.", actionMinutes: 6, videoReason: "호흡명상." },
    { mission: "거절 문장", actionTitle: "감정 보호 거절", actionHowTo: "거절 1개 작성.", actionMinutes: 4, videoReason: "이완명상." },
    { mission: "4주차 요약", actionTitle: "'4주 동안 감정이 ___'", actionHowTo: "한 문장 요약.", actionMinutes: 5, videoReason: "마무리 명상." },
    { mission: "최종 진단", actionTitle: "우울감 최종 진단", actionHowTo: "Day 2 반복.", actionMinutes: 6, videoReason: "마음 정리." },
    { mission: "30일 선언문", actionTitle: "'감정을 ___하는 사람'", actionHowTo: "선언문 1문장.", actionMinutes: 5, videoReason: "마무리 명상." },
  ],
  focus: [
    { mission: "산만함 베이스라인", actionTitle: "오늘 방해 요소 3개", actionHowTo: "오늘 집중 깬 3가지.", actionMinutes: 4, videoReason: "5초 법칙 영상." },
    { mission: "폰 사용 시간 측정", actionTitle: "스크린타임 확인", actionHowTo: "오늘 스크린타임 기록.", actionMinutes: 3, videoReason: "빼기 명상." },
    { mission: "알림 끄기 1개", actionTitle: "앱 알림 1개 끄기", actionHowTo: "가장 산만한 앱 1개.", actionMinutes: 3, videoReason: "생각 비우기." },
    { mission: "딥워크 25분", actionTitle: "타이머 25분 한 가지", actionHowTo: "폰 멀리 두고 25분.", actionMinutes: 6, videoReason: "5분 명상." },
    { mission: "작업 환경 손보기", actionTitle: "책상 위 1개 치우기", actionHowTo: "주의 분산 1개 제거.", actionMinutes: 5, videoReason: "5초 법칙." },
    { mission: "에너지 골든타임 찾기", actionTitle: "집중 잘되는 시간 1개", actionHowTo: "골든타임 1개 적기.", actionMinutes: 4, videoReason: "빼기 명상." },
    { mission: "1주차 진단", actionTitle: "회복탄력성 진단", actionHowTo: "측정.", actionMinutes: 7, videoReason: "회복력 영상." },
    { mission: "같은 시간대 반복", actionTitle: "어제 미션 같은 시간 반복", actionHowTo: "루틴화 시도.", actionMinutes: 5, videoReason: "루틴 영상." },
    { mission: "멀티태스킹 1개 끊기", actionTitle: "한 번에 1가지", actionHowTo: "멀티태스킹 의식적 중단.", actionMinutes: 4, videoReason: "생각 비우기." },
    { mission: "집중 패턴 진단", actionTitle: "불안 결 진단", actionHowTo: "집중 방해 객관화.", actionMinutes: 6, videoReason: "호흡명상." },
    { mission: "관계 차단 시간", actionTitle: "집중 방해 사람 차단", actionHowTo: "집중 시간 알리기.", actionMinutes: 5, videoReason: "멈추는 호흡법." },
    { mission: "호흡 분산", actionTitle: "박스호흡 3세트", actionHowTo: "아침·점심·저녁.", actionMinutes: 6, videoReason: "박스호흡." },
    { mission: "저널링 5분", actionTitle: "한 일 + 한 가지 흐트러진 이유", actionHowTo: "5분 자유 기록.", actionMinutes: 5, videoReason: "저널 직전 명상." },
    { mission: "2주차 비교", actionTitle: "스트레스 진단 반복", actionHowTo: "측정.", actionMinutes: 5, videoReason: "호흡 명상." },
    { mission: "핵심 루틴 강화", actionTitle: "TOP 3 다시", actionHowTo: "오늘 다시.", actionMinutes: 6, videoReason: "빼기 명상." },
    { mission: "회피 마주하기", actionTitle: "미뤄둔 일 5분", actionHowTo: "타이머 5분.", actionMinutes: 5, videoReason: "회피의 과학." },
    { mission: "도움 요청", actionTitle: "집중 위해 도움 요청 1개", actionHowTo: "한 사람에게 메시지.", actionMinutes: 4, videoReason: "회피형 극복." },
    { mission: "에너지 진단", actionTitle: "에너지 0~10 시간대별", actionHowTo: "아침·점심·저녁 점수.", actionMinutes: 5, videoReason: "명상." },
    { mission: "자기 칭찬", actionTitle: "집중 잘된 1순간 칭찬", actionHowTo: "1문장 칭찬.", actionMinutes: 3, videoReason: "자애 명상." },
    { mission: "환경 1개 더 정리", actionTitle: "책상·폰·메일 중 1개", actionHowTo: "5분 정리.", actionMinutes: 5, videoReason: "긍정확언." },
    { mission: "3주차 진단", actionTitle: "회복탄력성 진단", actionHowTo: "측정.", actionMinutes: 7, videoReason: "3주 마무리." },
    { mission: "워크북 심화", actionTitle: "집중 방해 트리거 분해", actionHowTo: "3층으로.", actionMinutes: 8, videoReason: "마음 비우기." },
    { mission: "코파일럿 1:1", actionTitle: "집중 주제 1개", actionHowTo: "'요즘 ___ 때문에 산만' 입력.", actionMinutes: 6, videoReason: "5분 아침명상." },
    { mission: "재발 방지", actionTitle: "'집중 무너지는 신호'", actionHowTo: "'___ → ___'.", actionMinutes: 5, videoReason: "알아차림 명상." },
    { mission: "핵심 루틴 고정", actionTitle: "집중 루틴 TOP 3", actionHowTo: "시간대 부여.", actionMinutes: 6, videoReason: "데일리 명상." },
    { mission: "관계 점검", actionTitle: "집중 방해 관계 1개", actionHowTo: "적어두기.", actionMinutes: 6, videoReason: "호흡 명상." },
    { mission: "거절 문장", actionTitle: "'지금은 집중 시간' 거절", actionHowTo: "거절 1개 작성.", actionMinutes: 4, videoReason: "이완명상." },
    { mission: "4주차 요약", actionTitle: "'4주 동안 집중이 ___'", actionHowTo: "한 문장.", actionMinutes: 5, videoReason: "마무리 명상." },
    { mission: "최종 진단", actionTitle: "우울감 최종 진단", actionHowTo: "Day 2 반복.", actionMinutes: 6, videoReason: "리포트 직전 정렬." },
    { mission: "30일 선언문", actionTitle: "'집중을 ___하는 사람'", actionHowTo: "선언문 1문장.", actionMinutes: 5, videoReason: "마무리 명상." },
  ],
  relationship: [
    { mission: "관계 베이스라인", actionTitle: "최근 갈등 1장면 기록", actionHowTo: "사실 1문장 묘사.", actionMinutes: 4, videoReason: "베이스라인 직후 호흡." },
    { mission: "내 관계 패턴 신호", actionTitle: "나의 반응 패턴 1개", actionHowTo: "반복하는 반응 1줄.", actionMinutes: 4, videoReason: "감정 라벨링." },
    { mission: "경청 5분", actionTitle: "오늘 한 사람 5분 듣기", actionHowTo: "끊지 않고 5분 듣기.", actionMinutes: 5, videoReason: "호흡으로 반응 멈추기." },
    { mission: "공감 1문장", actionTitle: "'그랬구나' 반영하기", actionHowTo: "상대 말 끝에 1문장.", actionMinutes: 3, videoReason: "자애 명상." },
    { mission: "경계 1개 정의", actionTitle: "'나는 ___은 어렵다'", actionHowTo: "경계 1개 명문화.", actionMinutes: 4, videoReason: "거절은 다정한 경계." },
    { mission: "부드러운 거절 1회", actionTitle: "오늘 작은 거절 1개", actionHowTo: "작은 부탁 1개 거절.", actionMinutes: 4, videoReason: "거절 영상." },
    { mission: "1주차 진단", actionTitle: "회복탄력성 진단", actionHowTo: "측정.", actionMinutes: 7, videoReason: "회복력 영상." },
    { mission: "같은 사람 같은 시간", actionTitle: "어제 대화 사람과 다시", actionHowTo: "같은 시간 짧은 안부.", actionMinutes: 5, videoReason: "이완명상." },
    { mission: "자동 반응 멈추기", actionTitle: "'멈춤' + 호흡", actionHowTo: "반응 전에 멈춤 + 호흡.", actionMinutes: 3, videoReason: "호흡법." },
    { mission: "관계 패턴 진단", actionTitle: "관계 패턴 진단", actionHowTo: "객관화.", actionMinutes: 7, videoReason: "호흡명상." },
    { mission: "최근 갈등 다시 보기", actionTitle: "상대 입장 1줄", actionHowTo: "상대 입장 1문장.", actionMinutes: 5, videoReason: "감정 라벨링." },
    { mission: "호흡으로 반응 분산", actionTitle: "박스호흡 3세트", actionHowTo: "아침·점심·저녁.", actionMinutes: 6, videoReason: "호흡." },
    { mission: "자유 기록 5분", actionTitle: "관계 일기", actionHowTo: "5분 자유 기록.", actionMinutes: 5, videoReason: "저널 직전 명상." },
    { mission: "2주차 비교", actionTitle: "스트레스 진단 반복", actionHowTo: "측정.", actionMinutes: 5, videoReason: "호흡명상." },
    { mission: "효과있던 대화 강화", actionTitle: "효과있던 대화 1개 다시", actionHowTo: "같은 사람 같은 방식.", actionMinutes: 6, videoReason: "명상." },
    { mission: "회피 마주하기", actionTitle: "미뤄둔 대화 5분", actionHowTo: "타이머 5분만.", actionMinutes: 5, videoReason: "회피의 과학." },
    { mission: "도움 요청", actionTitle: "'얘기 좀 가능해?'", actionHowTo: "한 사람에게.", actionMinutes: 4, videoReason: "회피형 극복." },
    { mission: "감정 강도 진단", actionTitle: "관계 감정 0~10", actionHowTo: "가장 강한 관계 감정.", actionMinutes: 5, videoReason: "RAIN 명상." },
    { mission: "자기 친절", actionTitle: "관계에서 잘한 1개", actionHowTo: "1문장 칭찬.", actionMinutes: 3, videoReason: "자애 명상." },
    { mission: "관계 환경 1개 손보기", actionTitle: "연락 방식 1개 변경", actionHowTo: "톤/시간/매체 1개 조정.", actionMinutes: 5, videoReason: "긍정확언." },
    { mission: "3주차 진단", actionTitle: "회복탄력성 진단", actionHowTo: "측정.", actionMinutes: 7, videoReason: "3주 마무리." },
    { mission: "워크북 심화", actionTitle: "관계 패턴 분해", actionHowTo: "반복 패턴 1개.", actionMinutes: 8, videoReason: "마음 비우기." },
    { mission: "코파일럿 1:1", actionTitle: "관계 주제 1개", actionHowTo: "'요즘 ___와 ___' 입력.", actionMinutes: 6, videoReason: "5분 아침명상." },
    { mission: "재발 방지", actionTitle: "'관계 무너질 신호'", actionHowTo: "'___ → ___'.", actionMinutes: 5, videoReason: "알아차림 명상." },
    { mission: "핵심 루틴 고정", actionTitle: "관계 루틴 TOP 3", actionHowTo: "시간대 부여.", actionMinutes: 6, videoReason: "데일리 명상." },
    { mission: "관계 1순위 점검", actionTitle: "미뤄둔 대화 첫 문장", actionHowTo: "한 사람에게 메시지.", actionMinutes: 5, videoReason: "이완명상." },
    { mission: "거절 문장", actionTitle: "관계 보호 거절", actionHowTo: "거절 1개.", actionMinutes: 4, videoReason: "이완명상." },
    { mission: "4주차 요약", actionTitle: "'4주 동안 관계가 ___'", actionHowTo: "한 문장.", actionMinutes: 5, videoReason: "마무리 명상." },
    { mission: "최종 진단", actionTitle: "우울감 최종 진단", actionHowTo: "Day 2 반복.", actionMinutes: 6, videoReason: "마음 정리." },
    { mission: "30일 선언문", actionTitle: "'관계를 ___하는 사람'", actionHowTo: "선언문 1문장.", actionMinutes: 5, videoReason: "마무리 명상." },
  ],
  self: [
    { mission: "자기 이해 베이스라인", actionTitle: "핵심 가치 단어 3개", actionHowTo: "나에게 중요한 가치 3개.", actionMinutes: 5, videoReason: "회복탄력성 영상." },
    { mission: "강점 3개", actionTitle: "나의 강점 3개 적기", actionHowTo: "주변 피드백 떠올리며.", actionMinutes: 4, videoReason: "감정 라벨링." },
    { mission: "그림자 1개", actionTitle: "피하고 싶은 모습 1개", actionHowTo: "'나는 ___이고 싶지 않다'.", actionMinutes: 4, videoReason: "빼기 명상." },
    { mission: "이상적 하루", actionTitle: "이상적 하루 시간표", actionHowTo: "아침-저녁 흐름 1줄씩.", actionMinutes: 6, videoReason: "긍정확언." },
    { mission: "자유 기록 5분", actionTitle: "손 멈추지 말기", actionHowTo: "타이머 5분.", actionMinutes: 5, videoReason: "저널 직전 명상." },
    { mission: "내면 대화 1개", actionTitle: "'내면 비판자' 알아차리기", actionHowTo: "비판자 목소리 1줄.", actionMinutes: 4, videoReason: "자애 명상." },
    { mission: "1주차 진단", actionTitle: "회복탄력성 진단", actionHowTo: "측정.", actionMinutes: 7, videoReason: "회복력 영상." },
    { mission: "어제 강점 다시", actionTitle: "어제 적은 강점 1개 사용", actionHowTo: "오늘 의식적으로 적용.", actionMinutes: 5, videoReason: "명상." },
    { mission: "자동사고 멈추기", actionTitle: "'멈춤' + 호흡", actionHowTo: "비판자 등장 시.", actionMinutes: 3, videoReason: "빼기 명상." },
    { mission: "패턴 진단", actionTitle: "불안 결 진단", actionHowTo: "객관화.", actionMinutes: 6, videoReason: "호흡 명상." },
    { mission: "내면 비판자 → 코치", actionTitle: "비판자 말을 코치 말로", actionHowTo: "비판 1개 → 코치 1개.", actionMinutes: 4, videoReason: "호흡으로 멈추기." },
    { mission: "호흡 분산", actionTitle: "박스호흡 3세트", actionHowTo: "아침·점심·저녁.", actionMinutes: 6, videoReason: "명상." },
    { mission: "자유 기록 5분", actionTitle: "핵심 가치와 행동 차이", actionHowTo: "갭 1줄.", actionMinutes: 5, videoReason: "저널 직전 명상." },
    { mission: "2주차 비교", actionTitle: "스트레스 진단 반복", actionHowTo: "측정.", actionMinutes: 5, videoReason: "호흡명상." },
    { mission: "효과있던 루틴 강화", actionTitle: "TOP 3 다시", actionHowTo: "오늘 다시.", actionMinutes: 6, videoReason: "빼기 명상." },
    { mission: "그림자 마주하기", actionTitle: "피하던 1개 5분 마주", actionHowTo: "'나는 ___도 가지고 있다'.", actionMinutes: 5, videoReason: "불편 감정 명상." },
    { mission: "도움 요청", actionTitle: "나를 잘 아는 사람에게", actionHowTo: "피드백 요청 1개.", actionMinutes: 4, videoReason: "명상." },
    { mission: "정체성 진단", actionTitle: "감정 강도 0~10", actionHowTo: "핵심 감정 1개.", actionMinutes: 5, videoReason: "명상." },
    { mission: "자기 친절", actionTitle: "오늘 잘한 1개 칭찬", actionHowTo: "1문장.", actionMinutes: 3, videoReason: "자애 명상." },
    { mission: "환경 1개 정렬", actionTitle: "가치와 안 맞는 1개 손보기", actionHowTo: "5분 안에.", actionMinutes: 5, videoReason: "긍정확언." },
    { mission: "3주차 진단", actionTitle: "회복탄력성 진단", actionHowTo: "측정.", actionMinutes: 7, videoReason: "3주 마무리." },
    { mission: "워크북 심화", actionTitle: "핵심 가치 vs 일상 갭", actionHowTo: "갭 3줄.", actionMinutes: 8, videoReason: "마음 비우기." },
    { mission: "코파일럿 1:1", actionTitle: "자기 이해 주제 1개", actionHowTo: "'나는 ___을 원한다' 입력.", actionMinutes: 6, videoReason: "5분 아침명상." },
    { mission: "재발 방지", actionTitle: "'옛 패턴 신호'", actionHowTo: "'___ → ___'.", actionMinutes: 5, videoReason: "알아차림 명상." },
    { mission: "핵심 루틴 고정", actionTitle: "자기 정렬 루틴 TOP 3", actionHowTo: "시간대 부여.", actionMinutes: 6, videoReason: "데일리 명상." },
    { mission: "관계 1순위 점검", actionTitle: "나를 도와줄 1명", actionHowTo: "미뤄둔 메시지.", actionMinutes: 5, videoReason: "명상." },
    { mission: "거절 문장", actionTitle: "가치 보호 거절", actionHowTo: "거절 1개.", actionMinutes: 4, videoReason: "이완명상." },
    { mission: "4주차 요약", actionTitle: "'4주 동안 나는 ___'", actionHowTo: "한 문장.", actionMinutes: 5, videoReason: "마무리 명상." },
    { mission: "최종 진단", actionTitle: "우울감 최종 진단", actionHowTo: "Day 2 반복.", actionMinutes: 6, videoReason: "마음 정리." },
    { mission: "30일 선언문", actionTitle: "'나는 ___한 사람으로 한 발'", actionHowTo: "선언문 1문장.", actionMinutes: 5, videoReason: "마무리 명상." },
  ],
  parenting: [
    { mission: "번아웃 베이스라인", actionTitle: "오늘 에너지 0~10", actionHowTo: "아침/저녁 점수.", actionMinutes: 4, videoReason: "부모 자애 명상." },
    { mission: "번아웃 신호 3개", actionTitle: "신호 단어 3개", actionHowTo: "피로/짜증/무감각 등.", actionMinutes: 4, videoReason: "이완명상." },
    { mission: "나만의 5분 확보", actionTitle: "오늘 나만의 5분", actionHowTo: "화장실/베란다 5분.", actionMinutes: 5, videoReason: "호흡 명상." },
    { mission: "도움 요청 1개", actionTitle: "배우자/가족에게", actionHowTo: "오늘 한 가지 요청.", actionMinutes: 4, videoReason: "호흡." },
    { mission: "자기 친절 한 줄", actionTitle: "'잘 하고 있어' 칭찬", actionHowTo: "1문장 자기 칭찬.", actionMinutes: 3, videoReason: "자애 명상." },
    { mission: "호흡 1세트", actionTitle: "4-4-6 호흡", actionHowTo: "5번.", actionMinutes: 3, videoReason: "호흡." },
    { mission: "1주차 진단", actionTitle: "회복탄력성 진단", actionHowTo: "측정.", actionMinutes: 7, videoReason: "회복력 영상." },
    { mission: "같은 시간 5분", actionTitle: "어제 5분 같은 시간", actionHowTo: "루틴화.", actionMinutes: 5, videoReason: "명상." },
    { mission: "자동 반응 멈추기", actionTitle: "'멈춤' + 호흡", actionHowTo: "아이 앞에서.", actionMinutes: 3, videoReason: "호흡법." },
    { mission: "패턴 진단", actionTitle: "불안 결 진단", actionHowTo: "번아웃 객관화.", actionMinutes: 6, videoReason: "호흡명상." },
    { mission: "최근 폭발 1장면", actionTitle: "사실 1문장", actionHowTo: "사실 그대로.", actionMinutes: 5, videoReason: "호흡." },
    { mission: "호흡 분산", actionTitle: "박스호흡 3세트", actionHowTo: "아침·점심·저녁.", actionMinutes: 6, videoReason: "호흡." },
    { mission: "저널 5분", actionTitle: "'엄마/아빠로서' 1줄", actionHowTo: "5분 자유 기록.", actionMinutes: 5, videoReason: "명상." },
    { mission: "2주차 비교", actionTitle: "스트레스 진단 반복", actionHowTo: "측정.", actionMinutes: 5, videoReason: "호흡명상." },
    { mission: "회복 루틴 강화", actionTitle: "효과있던 3가지 다시", actionHowTo: "오늘 다시.", actionMinutes: 6, videoReason: "명상." },
    { mission: "회피 마주하기", actionTitle: "미뤄둔 자기돌봄 5분", actionHowTo: "타이머 5분.", actionMinutes: 5, videoReason: "불편 감정 명상." },
    { mission: "도움 요청", actionTitle: "주변에 짧은 메시지", actionHowTo: "구체적 도움 1개.", actionMinutes: 4, videoReason: "호흡." },
    { mission: "감정 강도 진단", actionTitle: "육아 감정 강도", actionHowTo: "가장 강한 감정.", actionMinutes: 5, videoReason: "RAIN 명상." },
    { mission: "자기 칭찬", actionTitle: "오늘 잘한 양육 1개", actionHowTo: "1문장 칭찬.", actionMinutes: 3, videoReason: "자애 명상." },
    { mission: "환경 1개 손보기", actionTitle: "육아 동선 1개 조정", actionHowTo: "5분 안에.", actionMinutes: 5, videoReason: "긍정확언." },
    { mission: "3주차 진단", actionTitle: "회복탄력성 진단", actionHowTo: "측정.", actionMinutes: 7, videoReason: "3주 마무리." },
    { mission: "워크북 심화", actionTitle: "번아웃 트리거 분해", actionHowTo: "트리거 1개.", actionMinutes: 8, videoReason: "마음 비우기." },
    { mission: "코파일럿 1:1", actionTitle: "육아 주제 1개", actionHowTo: "'요즘 ___ 때문에 ___' 입력.", actionMinutes: 6, videoReason: "명상." },
    { mission: "재발 방지", actionTitle: "'번아웃 신호'", actionHowTo: "'___ → ___'.", actionMinutes: 5, videoReason: "알아차림 명상." },
    { mission: "핵심 루틴 고정", actionTitle: "회복 루틴 TOP 3", actionHowTo: "시간대 부여.", actionMinutes: 6, videoReason: "데일리 명상." },
    { mission: "관계 점검", actionTitle: "나를 지지할 1명", actionHowTo: "미뤄둔 메시지.", actionMinutes: 5, videoReason: "이완명상." },
    { mission: "거절 문장", actionTitle: "에너지 보호 거절", actionHowTo: "거절 1개.", actionMinutes: 4, videoReason: "이완명상." },
    { mission: "4주차 요약", actionTitle: "'4주 동안 나는 ___'", actionHowTo: "한 문장.", actionMinutes: 5, videoReason: "마무리 명상." },
    { mission: "최종 진단", actionTitle: "우울감 최종 진단", actionHowTo: "Day 2 반복.", actionMinutes: 6, videoReason: "마음 정리." },
    { mission: "30일 선언문", actionTitle: "'엄마/아빠로서 ___'", actionHowTo: "선언문 1문장.", actionMinutes: 5, videoReason: "마무리 명상." },
  ],
  child_development: [
    { mission: "발달 베이스라인", actionTitle: "아이 강점 3개", actionHowTo: "현재 강점 3개.", actionMinutes: 4, videoReason: "회복탄력성 영상." },
    { mission: "성장 영역 3개", actionTitle: "성장 필요 3개", actionHowTo: "관찰 결과.", actionMinutes: 4, videoReason: "감정 라벨링." },
    { mission: "관찰 5분", actionTitle: "오늘 5분 관찰 메모", actionHowTo: "행동 1개 사실 기록.", actionMinutes: 5, videoReason: "회피의 과학." },
    { mission: "긍정 피드백 1회", actionTitle: "구체적 칭찬 1회", actionHowTo: "'~을 ~게 했구나'.", actionMinutes: 3, videoReason: "자애 명상." },
    { mission: "발달 활동 1개", actionTitle: "연령 맞춤 활동 5분", actionHowTo: "책읽기/그리기/대화.", actionMinutes: 5, videoReason: "5분 호흡." },
    { mission: "기록 1줄", actionTitle: "오늘 발달 한 줄", actionHowTo: "오늘 본 한 가지.", actionMinutes: 3, videoReason: "명상." },
    { mission: "1주차 진단", actionTitle: "회복탄력성 진단", actionHowTo: "부모 측정.", actionMinutes: 7, videoReason: "회복력 영상." },
    { mission: "어제 활동 반복", actionTitle: "어제 활동 같은 시간", actionHowTo: "루틴화.", actionMinutes: 5, videoReason: "명상." },
    { mission: "자동 평가 멈추기", actionTitle: "'멈춤' + 호흡", actionHowTo: "평가 전 호흡.", actionMinutes: 3, videoReason: "호흡법." },
    { mission: "패턴 진단", actionTitle: "불안 결 진단", actionHowTo: "아이 패턴 객관화.", actionMinutes: 6, videoReason: "호흡명상." },
    { mission: "아이 감정 1개 라벨링", actionTitle: "아이 감정 단어 1개", actionHowTo: "'지금 ___ 같아'.", actionMinutes: 4, videoReason: "감정 라벨링." },
    { mission: "호흡 분산", actionTitle: "박스호흡 3세트", actionHowTo: "아침·점심·저녁.", actionMinutes: 6, videoReason: "호흡." },
    { mission: "저널 5분", actionTitle: "아이 관찰 5분", actionHowTo: "5분 자유 기록.", actionMinutes: 5, videoReason: "명상." },
    { mission: "2주차 비교", actionTitle: "스트레스 진단 반복", actionHowTo: "부모 측정.", actionMinutes: 5, videoReason: "호흡명상." },
    { mission: "효과있던 활동 강화", actionTitle: "TOP 3 다시", actionHowTo: "오늘 다시.", actionMinutes: 6, videoReason: "명상." },
    { mission: "어려운 발달 영역 마주", actionTitle: "미뤄둔 활동 5분", actionHowTo: "타이머 5분.", actionMinutes: 5, videoReason: "회피 영상." },
    { mission: "도움 요청", actionTitle: "교사/가족에게", actionHowTo: "피드백 1개.", actionMinutes: 4, videoReason: "명상." },
    { mission: "감정 강도 진단", actionTitle: "육아 감정 강도", actionHowTo: "가장 강한 감정.", actionMinutes: 5, videoReason: "RAIN 명상." },
    { mission: "자기 칭찬", actionTitle: "오늘 잘한 양육 1개", actionHowTo: "1문장 칭찬.", actionMinutes: 3, videoReason: "자애 명상." },
    { mission: "환경 1개 손보기", actionTitle: "발달 환경 1개 조정", actionHowTo: "5분 안에.", actionMinutes: 5, videoReason: "긍정확언." },
    { mission: "3주차 진단", actionTitle: "회복탄력성 진단", actionHowTo: "측정.", actionMinutes: 7, videoReason: "3주 마무리." },
    { mission: "워크북 심화", actionTitle: "발달 영역 분석", actionHowTo: "영역 1개 깊게.", actionMinutes: 8, videoReason: "마음 비우기." },
    { mission: "코파일럿 1:1", actionTitle: "발달 주제 1개", actionHowTo: "'우리 아이 ___' 입력.", actionMinutes: 6, videoReason: "5분 아침명상." },
    { mission: "재발 방지", actionTitle: "'발달 정체 신호'", actionHowTo: "'___ → ___'.", actionMinutes: 5, videoReason: "알아차림 명상." },
    { mission: "핵심 루틴 고정", actionTitle: "관찰 루틴 TOP 3", actionHowTo: "시간대 부여.", actionMinutes: 6, videoReason: "데일리 명상." },
    { mission: "관계 점검", actionTitle: "아이와의 1:1 시간", actionHowTo: "오늘 10분 확보.", actionMinutes: 5, videoReason: "명상." },
    { mission: "거절 문장", actionTitle: "아이 보호 거절", actionHowTo: "외부 압박 거절 1개.", actionMinutes: 4, videoReason: "이완명상." },
    { mission: "4주차 요약", actionTitle: "'4주 동안 아이가 ___'", actionHowTo: "한 문장.", actionMinutes: 5, videoReason: "마무리 명상." },
    { mission: "최종 진단", actionTitle: "우울감 최종 진단", actionHowTo: "부모 측정.", actionMinutes: 6, videoReason: "마음 정리." },
    { mission: "30일 선언문", actionTitle: "'우리 아이를 ___하는 부모'", actionHowTo: "선언문 1문장.", actionMinutes: 5, videoReason: "마무리 명상." },
  ],
  family_communication: [
    { mission: "소통 베이스라인", actionTitle: "최근 갈등 1장면", actionHowTo: "사실 1문장.", actionMinutes: 4, videoReason: "거절은 다정한 경계." },
    { mission: "아이 감정 라벨링", actionTitle: "아이 감정 단어 1개", actionHowTo: "'지금 ___ 같아'.", actionMinutes: 4, videoReason: "감정 라벨링." },
    { mission: "경청 5분", actionTitle: "아이 5분 끊지 않고", actionHowTo: "5분 듣기.", actionMinutes: 5, videoReason: "호흡으로 반응 멈추기." },
    { mission: "반영 1문장", actionTitle: "'~게 느꼈구나' 반영", actionHowTo: "아이 말 끝에.", actionMinutes: 3, videoReason: "자애 명상." },
    { mission: "훈육 언어 1개", actionTitle: "'안 돼' → 구체적 행동", actionHowTo: "'~하자' 형식.", actionMinutes: 4, videoReason: "불편 감정 명상." },
    { mission: "스킨십 1회", actionTitle: "오늘 안아주기 1회", actionHowTo: "10초 안아주기.", actionMinutes: 3, videoReason: "긍정확언." },
    { mission: "1주차 진단", actionTitle: "회복탄력성 진단", actionHowTo: "부모 측정.", actionMinutes: 7, videoReason: "회복력." },
    { mission: "같은 시간 같은 방식", actionTitle: "어제 대화 같은 시간", actionHowTo: "루틴화.", actionMinutes: 5, videoReason: "명상." },
    { mission: "자동 반응 멈추기", actionTitle: "'멈춤' + 호흡", actionHowTo: "훈육 전 호흡.", actionMinutes: 3, videoReason: "호흡법." },
    { mission: "관계 패턴 진단", actionTitle: "관계 패턴 진단", actionHowTo: "객관화.", actionMinutes: 7, videoReason: "호흡 명상." },
    { mission: "최근 폭발 다시 보기", actionTitle: "아이 입장 1줄", actionHowTo: "아이 입장 1문장.", actionMinutes: 5, videoReason: "감정 라벨링." },
    { mission: "호흡 분산", actionTitle: "박스호흡 3세트", actionHowTo: "아침·점심·저녁.", actionMinutes: 6, videoReason: "호흡." },
    { mission: "저널 5분", actionTitle: "오늘 대화 흐름 5분", actionHowTo: "5분 자유 기록.", actionMinutes: 5, videoReason: "명상." },
    { mission: "2주차 비교", actionTitle: "스트레스 진단 반복", actionHowTo: "측정.", actionMinutes: 5, videoReason: "호흡명상." },
    { mission: "효과있던 대화 강화", actionTitle: "효과있던 1개 다시", actionHowTo: "같은 방식.", actionMinutes: 6, videoReason: "명상." },
    { mission: "회피 마주하기", actionTitle: "미뤄둔 대화 5분", actionHowTo: "타이머 5분.", actionMinutes: 5, videoReason: "불편 감정 명상." },
    { mission: "도움 요청", actionTitle: "배우자/가족에게", actionHowTo: "역할 분담 요청.", actionMinutes: 4, videoReason: "명상." },
    { mission: "감정 강도 진단", actionTitle: "훈육 감정 0~10", actionHowTo: "가장 강한 감정.", actionMinutes: 5, videoReason: "RAIN 명상." },
    { mission: "자기 친절", actionTitle: "오늘 잘한 양육 1개", actionHowTo: "1문장 칭찬.", actionMinutes: 3, videoReason: "자애 명상." },
    { mission: "환경 1개 손보기", actionTitle: "대화 환경 1개 조정", actionHowTo: "5분 안에.", actionMinutes: 5, videoReason: "긍정확언." },
    { mission: "3주차 진단", actionTitle: "회복탄력성 진단", actionHowTo: "측정.", actionMinutes: 7, videoReason: "3주 마무리." },
    { mission: "워크북 심화", actionTitle: "훈육 패턴 분해", actionHowTo: "패턴 1개 3층.", actionMinutes: 8, videoReason: "마음 비우기." },
    { mission: "코파일럿 1:1", actionTitle: "훈육 주제 1개", actionHowTo: "'요즘 아이와 ___' 입력.", actionMinutes: 6, videoReason: "5분 아침명상." },
    { mission: "재발 방지", actionTitle: "'폭발 신호'", actionHowTo: "'___ → ___'.", actionMinutes: 5, videoReason: "알아차림 명상." },
    { mission: "핵심 루틴 고정", actionTitle: "애착 루틴 TOP 3", actionHowTo: "시간대 부여.", actionMinutes: 6, videoReason: "데일리 명상." },
    { mission: "관계 1순위", actionTitle: "아이와의 1:1", actionHowTo: "오늘 10분 확보.", actionMinutes: 5, videoReason: "이완명상." },
    { mission: "거절 문장", actionTitle: "아이 보호 거절", actionHowTo: "외부 압박 거절 1개.", actionMinutes: 4, videoReason: "이완명상." },
    { mission: "4주차 요약", actionTitle: "'4주 동안 아이와 ___'", actionHowTo: "한 문장.", actionMinutes: 5, videoReason: "마무리 명상." },
    { mission: "최종 진단", actionTitle: "우울감 최종 진단", actionHowTo: "Day 2 반복.", actionMinutes: 6, videoReason: "마음 정리." },
    { mission: "30일 선언문", actionTitle: "'아이와 ___한 부모'", actionHowTo: "선언문 1문장.", actionMinutes: 5, videoReason: "마무리 명상." },
  ],
};

export function getTrackDailyContent(focusId: MindTrackFocusId, day: number): MindTrackDailyContent {
  const safeDay = Math.max(1, Math.min(30, day));
  const days = TRACK_DAYS[focusId];
  const def = days[safeDay - 1];
  const pool = VIDEO_POOLS[focusId];
  const video = { ...pool[(safeDay - 1) % pool.length], reason: def.videoReason };
  const assessment = ASSESSMENT_DAYS[safeDay] ?? null;
  return {
    day: safeDay,
    assessment,
    video,
    action: { title: def.actionTitle, howTo: def.actionHowTo, minutes: def.actionMinutes },
  };
}

/** 트랙별 mission 라벨만 가져오기 (대시보드 카드 헤더용). */
export function getTrackMissionLabel(focusId: MindTrackFocusId, day: number): string {
  const safeDay = Math.max(1, Math.min(30, day));
  return TRACK_DAYS[focusId][safeDay - 1].mission;
}

export const TRACK_CONTENT_VERSION = '2026.05-v1';
