// SaaS 과금 구조
// 구독자: ₩9,900/월 → 모든 기능 무제한
// 비구독자: 기본 검사 무료, 전문 검사/리포트는 크레딧 필요

// === 기능별 무료 체험 횟수 (비구독자 기준) ===
export const FREE_TRIAL_LIMITS: Record<string, number> = {
  // ──── 항상 무료 (훅 역할, 유입 유도) ────
  DREAM_INTERPRETATION: -1,
  SAJU_ANALYSIS: -1,
  PAST_LIFE_JOB: -1,
  ANIMAL_FACE_MATCH: -1,
  INNER_ANIMAL: -1,
  IEP_GENERATION: -1,
  CRISIS_DETECTION: -1,

  // ──── 기본 검사: 2회 무료 (체험 후 유료 전환) ────
  PSYCHOLOGICAL_TEST: 2,
  DEPRESSION_TEST: 2,
  PANIC_TEST: 2,
  STRESS_INDEX: 2,
  SELF_WORTH: 2,
  FOCUS_CHECK: 2,

  // ──── 전문 검사: 1회 무료 체험 후 크레딧 필요 ────
  FIVE_D_PERSONALITY: 1,
  RELATIONSHIP_TYPE: 1,
  DEFENSE_MECHANISM: 1,
  CAREER_INTEREST: 1,
  LANGUAGE_TEST: 1,
  HAN_MEDICINE_TEST: 1,
  DEVELOPMENTAL_DELAY_TEST: 1,
  SENSORY_INTEGRATION_TEST: 1,
  LEARNING_DISABILITY_TEST: 1,
  SOCIAL_DEVELOPMENT_TEST: 1,

  // ──── 프리미엄 (심층 분석): 무료 체험 없음 → 바로 크레딧/구독 ────
  PREMIUM_ASSESSMENT: 0,
  OBSERVATION_ANALYSIS: 1,
  PROFESSIONAL_REPORT: 0,
  COMPREHENSIVE_REPORT: 0,
  AI_COACH: 1,
  EXPERT_MATCHING: 1,
  AI_COUNSELOR_CHAT: 2,
};

// 하위 호환성을 위한 TOKEN_COSTS (모두 0으로 설정 - 구독 기반으로 전환)
export const TOKEN_COSTS = {
  PSYCHOLOGICAL_TEST: 0,
  FOCUS_CHECK: 0,
  DEPRESSION_TEST: 0,
  PANIC_TEST: 0,
  LANGUAGE_TEST: 0,
  HAN_MEDICINE_TEST: 0,
  DEVELOPMENTAL_DELAY_TEST: 0,
  SENSORY_INTEGRATION_TEST: 0,
  LEARNING_DISABILITY_TEST: 0,
  SOCIAL_DEVELOPMENT_TEST: 0,
  FIVE_D_PERSONALITY: 0,
  RELATIONSHIP_TYPE: 0,
  STRESS_INDEX: 0,
  CAREER_INTEREST: 0,
  SELF_WORTH: 0,
  DEFENSE_MECHANISM: 0,
  AI_COACH: 0,
  EXPERT_MATCHING: 0,
  PREMIUM_ASSESSMENT: 0,
  OBSERVATION_ANALYSIS: 0,
  PROFESSIONAL_REPORT: 0,
  COMPREHENSIVE_REPORT: 0,
  DREAM_INTERPRETATION: 0,
  SAJU_ANALYSIS: 0,
  IEP_GENERATION: 0,
  CRISIS_DETECTION: 0,
  PAST_LIFE_JOB: 0,
  ANIMAL_FACE_MATCH: 0,
  INNER_ANIMAL: 0,
  CONTENT_RECOMMENDATION: 0,
  AI_COUNSELOR_CHAT: 0,
} as const;

export const TOKEN_COST_DESCRIPTIONS = {
  0: "구독 시 무제한",
} as const;

// 구독 요금
export const SUBSCRIPTION_PRICE = 9900;
export const SUBSCRIPTION_ORIGINAL_PRICE = 19900;
export const SUBSCRIPTION_DISCOUNT_PERCENT = 50;

// 단건 결제 (심층 리포트 1회)
export const SINGLE_REPORT_PRICE = 3900;
