// 구독 기반 접근 제어
// 19,900원/월 구독 시 모든 기능 무제한
// 비구독자는 기능별 1-2회 무료 체험 후 구독 유도

// 기능별 무료 체험 횟수 (비구독자 기준)
export const FREE_TRIAL_LIMITS: Record<string, number> = {
  // 심리검사 - 2회 무료 체험
  PSYCHOLOGICAL_TEST: 2,
  FOCUS_CHECK: 2,
  DEPRESSION_TEST: 2,
  PANIC_TEST: 2,
  LANGUAGE_TEST: 2,
  HAN_MEDICINE_TEST: 2,
  DEVELOPMENTAL_DELAY_TEST: 2,
  SENSORY_INTEGRATION_TEST: 2,
  LEARNING_DISABILITY_TEST: 2,
  SOCIAL_DEVELOPMENT_TEST: 2,
  FIVE_D_PERSONALITY: 2,
  RELATIONSHIP_TYPE: 2,
  STRESS_INDEX: 2,
  CAREER_INTEREST: 2,
  SELF_WORTH: 2,
  DEFENSE_MECHANISM: 2,

  // 심층 분석 - 1회 무료 체험
  PREMIUM_ASSESSMENT: 1,
  OBSERVATION_ANALYSIS: 1,
  PROFESSIONAL_REPORT: 1,
  COMPREHENSIVE_REPORT: 1,
  AI_COACH: 1,
  EXPERT_MATCHING: 1,

  // 엔터테인먼트 - 2회 무료 체험
  PAST_LIFE_JOB: 2,
  ANIMAL_FACE_MATCH: 2,
  INNER_ANIMAL: 2,
  CONTENT_RECOMMENDATION: 2,
  AI_COUNSELOR_CHAT: 2,

  // 항상 무료
  DREAM_INTERPRETATION: -1,  // -1 = 무제한
  SAJU_ANALYSIS: -1,
  IEP_GENERATION: -1,
  CRISIS_DETECTION: -1,
};

// 하위 호환성을 위한 TOKEN_COSTS (모두 0으로 설정 - 구독 기반으로 전환)
export const TOKEN_COSTS = {
  PSYCHOLOGICAL_TEST: 0,
  FOCUS_CHECK: 0,
  DEPRESSION_TEST: 0,
  PANIC_TEST: 0,
  LANGUAGE_TEST: 0,
  HAN_MEDICINE_TEST: 0,
  DEVELOPMENTAL_DELAY_TEST: 0,
  SENSORY_INTEGRATION_TEST: 0,
  LEARNING_DISABILITY_TEST: 0,
  SOCIAL_DEVELOPMENT_TEST: 0,
  FIVE_D_PERSONALITY: 0,
  RELATIONSHIP_TYPE: 0,
  STRESS_INDEX: 0,
  CAREER_INTEREST: 0,
  SELF_WORTH: 0,
  DEFENSE_MECHANISM: 0,
  AI_COACH: 0,
  EXPERT_MATCHING: 0,
  PREMIUM_ASSESSMENT: 0,
  OBSERVATION_ANALYSIS: 0,
  PROFESSIONAL_REPORT: 0,
  COMPREHENSIVE_REPORT: 0,
  DREAM_INTERPRETATION: 0,
  SAJU_ANALYSIS: 0,
  IEP_GENERATION: 0,
  CRISIS_DETECTION: 0,
  PAST_LIFE_JOB: 0,
  ANIMAL_FACE_MATCH: 0,
  INNER_ANIMAL: 0,
  CONTENT_RECOMMENDATION: 0,
  AI_COUNSELOR_CHAT: 0,
} as const;

export const TOKEN_COST_DESCRIPTIONS = {
  0: "구독 시 무제한",
} as const;

// 구독 요금
export const SUBSCRIPTION_PRICE = 9900;
export const SUBSCRIPTION_ORIGINAL_PRICE = 19900;
export const SUBSCRIPTION_DISCOUNT_PERCENT = 50;

// 단건 결제 (심층 리포트 1회)
export const SINGLE_REPORT_PRICE = 3900;
