import React, { useState } from 'react';
import { FileText, Download, Copy, Check } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useLanguage } from '@/i18n/LanguageContext';

interface ReferralLetterCardProps {
  testName: string;
  totalScore: number | string;
  maxScore?: number;
  severity: string;
  domains?: { label: string; score: number; maxScore: number; level: string }[];
  userName?: string;
  className?: string;
}

export const ReferralLetterCard: React.FC<ReferralLetterCardProps> = ({
  testName, totalScore, maxScore, severity, domains = [], userName, className = ''
}) => {
  const { isEnglish } = useLanguage();
  const [copied, setCopied] = useState(false);
  const [expanded, setExpanded] = useState(false);

  const today = new Date().toLocaleDateString(isEnglish ? 'en-US' : 'ko-KR', {
    year: 'numeric', month: 'long', day: 'numeric'
  });

  const domainSummary = domains.map(d =>
    `  - ${d.label}: ${d.score}/${d.maxScore} (${d.level})`
  ).join('\n');

  const letterKo = `
[참고용 소견서]

작성일: ${today}
평가명: ${testName}
대상자: ${userName || '(이름 미기재)'}

1. 평가 개요
본 소견서는 AIHPRO 플랫폼에서 실시한 자기보고식 선별검사 결과를 정리한 것으로,
전문적인 임상 진단을 대체하지 않으며 참고 자료로만 활용하시기 바랍니다.

2. 검사 결과 요약
- 검사명: ${testName}
- 총점: ${totalScore}${maxScore ? ` / ${maxScore}` : ''}
- 판정: ${severity}
${domainSummary ? `\n3. 영역별 세부 결과\n${domainSummary}` : ''}

4. 소견
상기 결과에 따르면 현재 '${severity}' 수준으로 평가됩니다.
보다 정확한 진단과 적절한 치료 계획 수립을 위해
전문 의료기관에서의 정밀 평가를 권고드립니다.

5. 권고 사항
- 정신건강의학과 또는 심리상담센터 방문 권장
- 본 결과를 지참하시어 초진 상담 시 참고 자료로 활용
- 필요 시 추가 심리검사 및 임상 면담 병행 권고

※ 본 문서는 의료법상 진단서가 아닌 참고용 소견서이며,
   AIHPRO AI 분석 엔진을 통해 생성되었습니다.
   정확한 진단은 반드시 전문 의료인과 상담하시기 바랍니다.

발행: AIHPRO (aihpro.com)
`.trim();

  const letterEn = `
[Referral Summary - For Reference Only]

Date: ${today}
Assessment: ${testName}
Subject: ${userName || '(Name not provided)'}

1. Assessment Overview
This summary is based on a self-report screening conducted on the AIHPRO platform.
It does not replace professional clinical diagnosis and should be used as reference material only.

2. Results Summary
- Assessment: ${testName}
- Total Score: ${totalScore}${maxScore ? ` / ${maxScore}` : ''}
- Classification: ${severity}
${domainSummary ? `\n3. Domain Breakdown\n${domainSummary}` : ''}

4. Clinical Impression
Based on the results, the current level is assessed as '${severity}'.
A comprehensive evaluation at a specialized medical facility is recommended
for accurate diagnosis and appropriate treatment planning.

5. Recommendations
- Visit a psychiatry department or psychological counseling center
- Bring this document as reference material for initial consultation
- Additional psychological testing and clinical interview may be warranted

※ This document is a reference summary, not a medical diagnosis.
   Generated by AIHPRO AI Analysis Engine.
   Please consult a licensed healthcare professional for accurate diagnosis.

Issued by: AIHPRO (aihpro.com)
`.trim();

  const letter = isEnglish ? letterEn : letterKo;

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(letter);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch { /* fallback */ }
  };

  const handleDownload = () => {
    const blob = new Blob([letter], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${isEnglish ? 'Referral_Summary' : '참고용_소견서'}_${today.replace(/\s/g, '_')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className={`rounded-2xl border border-border/40 bg-card p-4 ${className}`}>
      <div className="flex items-center justify-between mb-3">
        <h3 className="text-sm font-bold text-foreground flex items-center gap-2">
          <FileText className="w-4 h-4 text-primary" />
          {isEnglish ? 'Referral Summary' : '참고용 소견서'}
        </h3>
        <div className="flex items-center gap-1.5">
          <Button variant="ghost" size="sm" className="h-7 px-2 text-[10px]" onClick={handleCopy}>
            {copied ? <Check className="w-3 h-3 mr-1" /> : <Copy className="w-3 h-3 mr-1" />}
            {copied ? (isEnglish ? 'Copied' : '복사됨') : (isEnglish ? 'Copy' : '복사')}
          </Button>
          <Button variant="ghost" size="sm" className="h-7 px-2 text-[10px]" onClick={handleDownload}>
            <Download className="w-3 h-3 mr-1" />
            {isEnglish ? 'Download' : '다운로드'}
          </Button>
        </div>
      </div>

      <p className="text-[10px] text-muted-foreground mb-3">
        {isEnglish
          ? 'A reference summary you can bring to your healthcare provider for initial consultation.'
          : '병원 초진 상담 시 의료진에게 제출할 수 있는 참고용 소견서입니다.'}
      </p>

      <div
        className={`bg-muted/20 rounded-lg p-3 font-mono text-[10px] leading-relaxed text-foreground/80 whitespace-pre-wrap ${
          expanded ? '' : 'max-h-[200px] overflow-hidden relative'
        }`}
      >
        {letter}
        {!expanded && (
          <div className="absolute bottom-0 left-0 right-0 h-12 bg-gradient-to-t from-card to-transparent" />
        )}
      </div>

      {!expanded && (
        <button
          onClick={() => setExpanded(true)}
          className="w-full text-center text-[11px] text-primary font-medium mt-2 hover:underline"
        >
          {isEnglish ? 'Show full document' : '전체 보기'}
        </button>
      )}

      <p className="text-[9px] text-muted-foreground/50 mt-3 text-center">
        {isEnglish
          ? '※ This is NOT a medical diagnosis. Consult a licensed professional.'
          : '※ 본 문서는 의료법상 진단서가 아닌 참고용이며, 정확한 진단은 전문의와 상담하세요.'}
      </p>
    </div>
  );
};

export default ReferralLetterCard;
