// Regenerate Day 1~7 personalized missions based on a deeper user concern.
// - Updates enrollment.baseline_data.primary_concern
// - Replaces existing mind_track_daily_missions for this enrollment (Day 1~7)
// - Inserts 7 new missions generated by Lovable AI Gateway
// - Writes step-by-step progress rows to public.mind_track_regen_progress
//   so the client overlay can poll real progression.
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

interface Body {
  enrollmentId: string;
  concern: string;
  sessionId?: string;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  // Shared admin client (declared early so the catch handler can write a fail row)
  const adminSupabase = createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
    { auth: { persistSession: false } },
  );

  let sessionId: string | undefined;
  let userIdForFail: string | undefined;
  let enrollmentIdForFail: string | undefined;

  const writeProgress = async (
    stage: string,
    percent: number,
    message: string,
    theory?: string,
  ) => {
    if (!sessionId || !userIdForFail || !enrollmentIdForFail) return;
    try {
      await adminSupabase.from("mind_track_regen_progress").insert({
        session_id: sessionId,
        user_id: userIdForFail,
        enrollment_id: enrollmentIdForFail,
        stage,
        percent,
        message,
        theory: theory ?? null,
      });
    } catch (_) {
      // Best-effort progress; never block main flow.
    }
  };

  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) throw new Error("No authorization header");

    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_ANON_KEY")!,
      { global: { headers: { Authorization: authHeader } } },
    );

    const { data: { user } } = await supabase.auth.getUser();
    if (!user) throw new Error("Not authenticated");
    userIdForFail = user.id;

    const body = (await req.json()) as Body;
    if (!body?.enrollmentId || !body?.concern || body.concern.trim().length < 20) {
      throw new Error("Invalid input: enrollmentId and concern (>=20 chars) required");
    }
    sessionId = body.sessionId;
    enrollmentIdForFail = body.enrollmentId;
    const concern = body.concern.trim().slice(0, 1200);

    await writeProgress(
      "parse",
      8,
      "고민을 의미 단위(감정·상황·관계·트리거)로 분해하는 중",
      "Affect Labeling (Lieberman, 2007)",
    );

    // 1) Load enrollment (verify ownership) + audience/goal context
    const { data: enr, error: e1 } = await adminSupabase
      .from("mind_track_enrollments")
      .select("id, user_id, audience, goal_focus, baseline_data")
      .eq("id", body.enrollmentId)
      .eq("user_id", user.id)
      .maybeSingle();
    if (e1) throw e1;
    if (!enr) throw new Error("Enrollment not found");

    const audience = (enr.audience as string) ?? "adult";
    const goal = (enr.goal_focus as string) ?? "stress";
    const prevBaseline =
      enr.baseline_data && typeof enr.baseline_data === "object" && !Array.isArray(enr.baseline_data)
        ? (enr.baseline_data as Record<string, unknown>)
        : {};

    await writeProgress(
      "map",
      22,
      "발달·심리 이론과 매핑 — 자율성·유능감·관계성의 결핍 지점 정렬",
      "Self-Determination Theory · CBT 행동 활성화",
    );

    // 2) Generate Day 1~7 missions via AI
    const audienceLabel: Record<string, string> = {
      child: "아이의 행동/발달 코칭이 주제인 부모",
      parent: "육아 번아웃 회복이 주제인 부모",
      adult: "성인 본인의 마음 회복",
      teen: "청소년 본인의 마음 회복",
    };
    const systemPrompt = `당신은 깊이 있는 코칭 가이드입니다. 사용자가 적은 ‘진짜 고민’ 한 단락을 바탕으로 7일 마음 트랙의 Day 1~7 맞춤 미션을 다시 설계하세요.

[엄격한 규칙]
- 의료 용어(진단/치료/환자/증상) 금지
- 외부 브랜드/학계 약어(Noom/Calm/Wysa/CBT/PHQ-9/MBTI/RCI) 금지
- 따뜻하지만 명료한 한국어. 추상어 남발 금지, 상황/도구/트리거 명시
- 모든 응답은 반드시 JSON 형식
- Day 1·4·7은 평가/전문가/회고가 자연스럽게 어울리는 ‘무거운 Day’,
  Day 2·3·5·6은 5~10분짜리 ‘가벼운 실천 Day’로 구성

[미션 품질 기준]
1) title: 8~16자, 동사로 시작하는 구체 행동
2) description: 2~3문장. 언제/어디서/얼마나/무엇을 명확히 (사용자 고민의 단어 활용)
3) why_it_matters: 1문장. 이 미션이 사용자의 고민과 어떻게 연결되는지
4) action_steps: 3~5개의 순서 있는 짧은 행동 단계 (각 6~20자)
5) success_criteria: 1문장. 객관적 완료 기준
6) deeper_prompts: 2~3개 자기성찰 질문
7) difficulty: easy | medium | deep
8) minutes: 3~15

[출력 JSON 스키마]
{
  "missions": [
    { "day": 1, "title": "...", "description": "...", "type": "reflection|action|breathing|journaling|connection", "minutes": 7, "difficulty": "easy|medium|deep", "why_it_matters": "...", "action_steps": ["1단계","2단계","3단계"], "success_criteria": "...", "deeper_prompts": ["질문1","질문2"] }
    // day 2~7 동일 스키마, 총 7개
  ]
}`;

    const userPrompt = `[대상] ${audienceLabel[audience] ?? audienceLabel.adult}
[기존 목표 포커스] ${goal}
[사용자가 적은 진짜 고민 — 가장 중요]
"""
${concern}
"""

위 고민의 구체적 단어·상황·관계를 그대로 반영한 Day 1~7 미션 7개를 JSON으로만 출력하세요.`;

    await writeProgress(
      "design",
      40,
      "Day 1~7 흐름 설계 — 무거운/가벼운 Day 리듬으로 재구성",
      "Behavioral Activation · Tiny Habits (Fogg)",
    );

    const aiRes = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${Deno.env.get("LOVABLE_API_KEY")}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash",
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: userPrompt },
        ],
        response_format: { type: "json_object" },
      }),
    });
    if (!aiRes.ok) {
      const errText = await aiRes.text();
      throw new Error(`AI generation failed: ${errText}`);
    }
    const aiData = await aiRes.json();
    const content = aiData.choices?.[0]?.message?.content;
    if (!content) throw new Error("AI returned empty content");
    const parsed = JSON.parse(content);
    const missions = Array.isArray(parsed?.missions) ? parsed.missions : [];
    if (missions.length === 0) throw new Error("AI returned no missions");

    await writeProgress(
      "personalize",
      72,
      "당신의 단어로 미션 개인화 — ‘언제·어디서·누구와’ 새기는 중",
      "Implementation Intentions (Gollwitzer)",
    );

    // 3) Find workbook_id (optional)
    const { data: wb } = await adminSupabase
      .from("mind_track_workbooks")
      .select("id")
      .eq("enrollment_id", body.enrollmentId)
      .eq("user_id", user.id)
      .maybeSingle();

    // 4) Replace existing Day 1~7 daily missions
    const { error: delErr } = await adminSupabase
      .from("mind_track_daily_missions")
      .delete()
      .eq("enrollment_id", body.enrollmentId)
      .eq("user_id", user.id)
      .lte("day_number", 7);
    if (delErr) throw delErr;

    const byDay = new Map<number, any>();
    for (const m of missions) {
      const d = Number(m?.day);
      if (!Number.isFinite(d) || d < 1 || d > 7) continue;
      if (!byDay.has(d)) byDay.set(d, m);
    }
    const rows = Array.from(byDay.values()).map((m: any) => ({
      user_id: user.id,
      enrollment_id: body.enrollmentId,
      workbook_id: wb?.id ?? null,
      day_number: m.day,
      week_number: 1,
      mission_title: String(m.title ?? "").slice(0, 120),
      mission_description: String(m.description ?? "").slice(0, 600),
      mission_type: m.type ?? "reflection",
      estimated_minutes: typeof m.minutes === "number" ? m.minutes : 7,
      difficulty: m.difficulty ?? "medium",
      why_it_matters: m.why_it_matters ?? null,
      action_steps: Array.isArray(m.action_steps) ? m.action_steps : [],
      success_criteria: m.success_criteria ?? null,
      deeper_prompts: Array.isArray(m.deeper_prompts) ? m.deeper_prompts : [],
    }));

    await writeProgress(
      "verify",
      88,
      "안전성·실행 가능성 검증 — 위기 신호·과부담 미션 필터링",
      "Stage of Change · 안전 가이드",
    );

    const { error: insErr } = await adminSupabase
      .from("mind_track_daily_missions")
      .upsert(rows, { onConflict: "enrollment_id,day_number" });
    if (insErr) throw insErr;

    // 5) Update enrollment baseline_data with the refined concern
    const nextBaseline = {
      ...prevBaseline,
      primary_concern: concern,
      concern_refined_at: new Date().toISOString(),
    };
    await adminSupabase
      .from("mind_track_enrollments")
      .update({ baseline_data: nextBaseline })
      .eq("id", body.enrollmentId)
      .eq("user_id", user.id);

    await writeProgress(
      "done",
      100,
      `Day 1~7 맞춤 미션 ${rows.length}개 생성 완료`,
      "전 과정 이론 근거 적용 완료",
    );

    return new Response(
      JSON.stringify({ success: true, regenerated: rows.length, sessionId }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } },
    );
  } catch (e: any) {
    console.error("mind-track-regenerate error:", e);
    await writeProgress("error", 100, e?.message ?? String(e));
    return new Response(
      JSON.stringify({ success: false, error: e?.message ?? String(e) }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } },
    );
  }
});
