import { useState, useEffect } from "react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";
import { 
  FileText, 
  Download, 
  Save, 
  Calendar,
  User,
  Brain,
  TrendingUp,
  Clock,
  Target
} from "lucide-react";
import { ExpertProfile } from "@/types/assessment";

interface ObservationLog {
  id: string;
  sessionId: string;
  clientId: string;
  expertId: string;
  sessionDate: Date;
  sessionDuration: number;
  mainIssues: string[];
  observedBehaviors: string[];
  mentalStatusExam: {
    appearance: string;
    mood: string;
    thought: string;
    cognition: string;
    insight: string;
  };
  progressAssessment: {
    previousGoals: string;
    achievement: string;
    newIssues: string;
    changePattern: string;
  };
  nextSessionPlan: {
    shortTermGoals: string[];
    techniques: string[];
    homework: string[];
  };
  clinicalImpression: string;
  riskAssessment: 'low' | 'medium' | 'high';
  autoGenerated: boolean;
  aiSummary?: string;
}

interface AutoObservationLogProps {
  sessionData: {
    clientInfo: any;
    sessionDate: Date;
    mainIssues: string[];
    observedBehaviors: string[];
    sessionKeywords: string[];
    expert: ExpertProfile;
  };
  onSave: (log: ObservationLog) => void;
}

const AutoObservationLog = ({ sessionData, onSave }: AutoObservationLogProps) => {
  const [observationLog, setObservationLog] = useState<ObservationLog>({
    id: '',
    sessionId: '',
    clientId: '',
    expertId: sessionData.expert.id,
    sessionDate: sessionData.sessionDate,
    sessionDuration: 50,
    mainIssues: sessionData.mainIssues,
    observedBehaviors: sessionData.observedBehaviors,
    mentalStatusExam: {
      appearance: '',
      mood: '',
      thought: '',
      cognition: '',
      insight: ''
    },
    progressAssessment: {
      previousGoals: '',
      achievement: '',
      newIssues: '',
      changePattern: ''
    },
    nextSessionPlan: {
      shortTermGoals: [],
      techniques: [],
      homework: []
    },
    clinicalImpression: '',
    riskAssessment: 'low',
    autoGenerated: true,
    aiSummary: ''
  });

  const [isGenerating, setIsGenerating] = useState(false);
  const [editMode, setEditMode] = useState(false);

  useEffect(() => {
    generateObservationLog();
  }, []);

  const generateObservationLog = async () => {
    setIsGenerating(true);
    
    try {
      // AI 기반 관찰일지 자동 생성 시뮬레이션
      await new Promise(resolve => setTimeout(resolve, 3000));
      
      const generatedLog: ObservationLog = {
        ...observationLog,
        id: Date.now().toString(),
        sessionId: `session_${Date.now()}`,
        clientId: `client_${Math.random().toString(36).substr(2, 9)}`,
        mentalStatusExam: {
          appearance: "단정한 복장, 적절한 자세 유지. 눈맞춤은 간헐적이나 전반적으로 협조적인 태도 보임.",
          mood: "우울한 기분 호소, 표정에서 슬픔이 관찰됨. 목소리 톤이 낮고 말의 속도가 느림.",
          thought: "논리적 사고과정 유지, 현실검증력 양호. 부정적 인지패턴과 자기비난적 사고 관찰됨.",
          cognition: "주의집중력 다소 저하, 기억력은 양호. 판단력과 추상적 사고능력 정상 범위.",
          insight: "자신의 문제에 대한 인식은 있으나 변화 동기는 제한적. 치료적 관계 형성에 협조적."
        },
        progressAssessment: {
          previousGoals: "일상 활동 참여 증가, 부정적 사고 패턴 인식",
          achievement: "일주일 중 3-4일 산책하기 목표 70% 달성. 자동적 사고 일지 작성 지속.",
          newIssues: "대인관계에서의 회피 패턴이 새롭게 관찰됨. 직장 스트레스 증가.",
          changePattern: "점진적 개선 양상이나 변화 속도는 완만함. 의욕 저하로 인한 일시적 후퇴 있음."
        },
        nextSessionPlan: {
          shortTermGoals: [
            "대인관계 회피 패턴 탐색 및 대안 행동 개발",
            "직장 스트레스 관리 기법 학습",
            "자기효능감 향상을 위한 작은 성취 경험 늘리기"
          ],
          techniques: [
            "인지행동치료 기법 (인지재구성)",
            "점진적 노출요법",
            "마음챙김 기반 스트레스 감소법"
          ],
          homework: [
            "대인관계 상황에서의 감정 및 행동 기록하기",
            "일일 감사 일지 작성",
            "주 2회 이상 사회적 활동 참여하기"
          ]
        },
        clinicalImpression: `내담자는 중등도의 우울 증상을 보이며, 최근 대인관계 회피와 직장 스트레스로 인한 어려움을 겪고 있음. 치료 동기와 협조도는 양호하나 변화에 대한 두려움이 관찰됨. 
        
인지행동치료 접근을 통한 부정적 사고패턴 수정과 점진적 행동 변화가 필요함. 현재 자해나 자살 사고는 부인하나 지속적인 모니터링이 필요함.

예후는 양호할 것으로 예상되며, 정기적인 개별상담과 함께 그룹치료 참여도 고려해볼 수 있음.`,
        riskAssessment: 'medium',
        aiSummary: `AI 분석: 이번 세션에서 내담자는 우울감과 대인관계 어려움을 주요하게 호소했습니다. 치료 진행도는 중간 정도이며, 다음 세션에서는 대인관계 기술 향상에 초점을 맞출 것을 권장합니다. 위험도는 중등도로 평가되며 정기적인 추적관찰이 필요합니다.`
      };
      
      setObservationLog(generatedLog);
    } catch (error) {
      console.error('Observation log generation error:', error);
    }
    
    setIsGenerating(false);
  };

  const handleSave = () => {
    onSave(observationLog);
  };

  const handleExport = () => {
    const logText = `
========= 상담 관찰일지 =========

기본 정보:
- 상담 일시: ${observationLog.sessionDate.toLocaleString()}
- 상담 시간: ${observationLog.sessionDuration}분
- 전문가: ${sessionData.expert.name}

주요 호소 문제:
${observationLog.mainIssues.map(issue => `- ${issue}`).join('\n')}

정신상태 검사 (MSE):
- 외모 및 태도: ${observationLog.mentalStatusExam.appearance}
- 정동 및 기분: ${observationLog.mentalStatusExam.mood}
- 사고과정: ${observationLog.mentalStatusExam.thought}
- 인지기능: ${observationLog.mentalStatusExam.cognition}
- 병식 및 판단력: ${observationLog.mentalStatusExam.insight}

진전도 평가:
- 이전 목표 달성도: ${observationLog.progressAssessment.achievement}
- 새로운 문제: ${observationLog.progressAssessment.newIssues}
- 변화 양상: ${observationLog.progressAssessment.changePattern}

다음 세션 계획:
단기 목표:
${observationLog.nextSessionPlan.shortTermGoals.map(goal => `- ${goal}`).join('\n')}

사용 기법:
${observationLog.nextSessionPlan.techniques.map(tech => `- ${tech}`).join('\n')}

과제:
${observationLog.nextSessionPlan.homework.map(hw => `- ${hw}`).join('\n')}

임상적 인상:
${observationLog.clinicalImpression}

AI 요약:
${observationLog.aiSummary}

위험도 평가: ${observationLog.riskAssessment}
    `;

    const blob = new Blob([logText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `관찰일지_${observationLog.sessionDate.toISOString().split('T')[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (isGenerating) {
    return (
      <div className="max-w-4xl mx-auto p-6">
        <Card className="p-8 text-center space-y-6">
          <div className="w-16 h-16 mx-auto bg-gradient-to-br from-primary to-primary-glow rounded-full flex items-center justify-center animate-pulse">
            <Brain className="w-8 h-8 text-white" />
          </div>
          <div>
            <h2 className="text-2xl font-bold text-foreground mb-2">AI 관찰일지 생성 중</h2>
            <p className="text-muted-foreground">전문가급 관찰일지를 자동으로 작성하고 있습니다...</p>
          </div>
          <div className="space-y-2">
            <div className="text-sm text-primary">분석 진행 단계:</div>
            <div className="space-y-1 text-xs text-muted-foreground">
              <div>✓ 세션 데이터 수집 완료</div>
              <div>✓ 행동 관찰 패턴 분석 완료</div>
              <div>🔄 정신상태 검사 작성 중...</div>
              <div>⏳ 치료 계획 수립 대기</div>
              <div>⏳ 임상적 인상 정리 대기</div>
            </div>
          </div>
        </Card>
      </div>
    );
  }

  return (
    <div className="max-w-6xl mx-auto p-6 space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-foreground">자동 생성 관찰일지</h1>
          <p className="text-muted-foreground">AI가 자동으로 생성한 전문적 관찰일지입니다</p>
        </div>
        <div className="flex items-center gap-3">
          <Badge className="bg-green-100 text-green-700">
            <Brain className="w-3 h-3 mr-1" />
            AI 생성 완료
          </Badge>
          <Button variant="outline" onClick={() => setEditMode(!editMode)}>
            {editMode ? '보기 모드' : '수정 모드'}
          </Button>
          <Button onClick={handleExport} variant="outline">
            <Download className="w-4 h-4 mr-2" />
            내보내기
          </Button>
          <Button onClick={handleSave} className="btn-brand">
            <Save className="w-4 h-4 mr-2" />
            저장
          </Button>
        </div>
      </div>

      {/* Session Info */}
      <Card className="p-6">
        <div className="grid md:grid-cols-4 gap-4 text-center">
          <div className="space-y-2">
            <Calendar className="w-6 h-6 mx-auto text-primary" />
            <div className="text-sm text-muted-foreground">상담 일시</div>
            <div className="font-semibold">{observationLog.sessionDate.toLocaleDateString()}</div>
          </div>
          <div className="space-y-2">
            <Clock className="w-6 h-6 mx-auto text-primary" />
            <div className="text-sm text-muted-foreground">상담 시간</div>
            <div className="font-semibold">{observationLog.sessionDuration}분</div>
          </div>
          <div className="space-y-2">
            <User className="w-6 h-6 mx-auto text-primary" />
            <div className="text-sm text-muted-foreground">담당 전문가</div>
            <div className="font-semibold">{sessionData.expert.name}</div>
          </div>
          <div className="space-y-2">
            <Target className="w-6 h-6 mx-auto text-primary" />
            <div className="text-sm text-muted-foreground">위험도</div>
            <Badge className={
              observationLog.riskAssessment === 'high' ? 'bg-red-100 text-red-700' :
              observationLog.riskAssessment === 'medium' ? 'bg-yellow-100 text-yellow-700' :
              'bg-green-100 text-green-700'
            }>
              {observationLog.riskAssessment === 'high' ? '높음' :
               observationLog.riskAssessment === 'medium' ? '보통' : '낮음'}
            </Badge>
          </div>
        </div>
      </Card>

      {/* Main Issues */}
      <Card className="p-6 space-y-4">
        <h3 className="text-lg font-semibold text-foreground">주요 호소 문제</h3>
        <div className="flex flex-wrap gap-2">
          {observationLog.mainIssues.map((issue, index) => (
            <Badge key={index} className="bg-primary/20 text-primary">
              {issue}
            </Badge>
          ))}
        </div>
      </Card>

      {/* Mental Status Examination */}
      <Card className="p-6 space-y-6">
        <h3 className="text-lg font-semibold text-foreground">정신상태 검사 (MSE)</h3>
        <div className="grid md:grid-cols-2 gap-6">
          <div className="space-y-4">
            <div>
              <label className="text-sm font-medium text-foreground">외모 및 태도</label>
              {editMode ? (
                <Textarea 
                  value={observationLog.mentalStatusExam.appearance}
                  onChange={(e) => setObservationLog(prev => ({
                    ...prev,
                    mentalStatusExam: { ...prev.mentalStatusExam, appearance: e.target.value }
                  }))}
                  className="mt-1"
                />
              ) : (
                <p className="text-sm text-muted-foreground mt-1">{observationLog.mentalStatusExam.appearance}</p>
              )}
            </div>
            <div>
              <label className="text-sm font-medium text-foreground">정동 및 기분</label>
              {editMode ? (
                <Textarea 
                  value={observationLog.mentalStatusExam.mood}
                  onChange={(e) => setObservationLog(prev => ({
                    ...prev,
                    mentalStatusExam: { ...prev.mentalStatusExam, mood: e.target.value }
                  }))}
                  className="mt-1"
                />
              ) : (
                <p className="text-sm text-muted-foreground mt-1">{observationLog.mentalStatusExam.mood}</p>
              )}
            </div>
          </div>
          <div className="space-y-4">
            <div>
              <label className="text-sm font-medium text-foreground">사고과정</label>
              {editMode ? (
                <Textarea 
                  value={observationLog.mentalStatusExam.thought}
                  onChange={(e) => setObservationLog(prev => ({
                    ...prev,
                    mentalStatusExam: { ...prev.mentalStatusExam, thought: e.target.value }
                  }))}
                  className="mt-1"
                />
              ) : (
                <p className="text-sm text-muted-foreground mt-1">{observationLog.mentalStatusExam.thought}</p>
              )}
            </div>
            <div>
              <label className="text-sm font-medium text-foreground">인지기능</label>
              {editMode ? (
                <Textarea 
                  value={observationLog.mentalStatusExam.cognition}
                  onChange={(e) => setObservationLog(prev => ({
                    ...prev,
                    mentalStatusExam: { ...prev.mentalStatusExam, cognition: e.target.value }
                  }))}
                  className="mt-1"
                />
              ) : (
                <p className="text-sm text-muted-foreground mt-1">{observationLog.mentalStatusExam.cognition}</p>
              )}
            </div>
          </div>
        </div>
      </Card>

      {/* Progress Assessment */}
      <Card className="p-6 space-y-4">
        <h3 className="text-lg font-semibold text-foreground flex items-center gap-2">
          <TrendingUp className="w-5 h-5" />
          진전도 평가
        </h3>
        <div className="space-y-4">
          <div>
            <label className="text-sm font-medium text-foreground">이전 목표 달성도</label>
            <p className="text-sm text-muted-foreground mt-1">{observationLog.progressAssessment.achievement}</p>
          </div>
          <div>
            <label className="text-sm font-medium text-foreground">새로운 문제 발견</label>
            <p className="text-sm text-muted-foreground mt-1">{observationLog.progressAssessment.newIssues}</p>
          </div>
          <div>
            <label className="text-sm font-medium text-foreground">변화 양상</label>
            <p className="text-sm text-muted-foreground mt-1">{observationLog.progressAssessment.changePattern}</p>
          </div>
        </div>
      </Card>

      {/* Next Session Plan */}
      <Card className="p-6 space-y-4">
        <h3 className="text-lg font-semibold text-foreground">다음 세션 계획</h3>
        <div className="grid md:grid-cols-3 gap-6">
          <div>
            <label className="text-sm font-medium text-foreground">단기 목표</label>
            <ul className="mt-2 space-y-1">
              {observationLog.nextSessionPlan.shortTermGoals.map((goal, index) => (
                <li key={index} className="text-sm text-muted-foreground flex items-start gap-2">
                  <span className="w-1 h-1 bg-primary rounded-full mt-2 flex-shrink-0" />
                  {goal}
                </li>
              ))}
            </ul>
          </div>
          <div>
            <label className="text-sm font-medium text-foreground">사용 기법</label>
            <ul className="mt-2 space-y-1">
              {observationLog.nextSessionPlan.techniques.map((technique, index) => (
                <li key={index} className="text-sm text-muted-foreground flex items-start gap-2">
                  <span className="w-1 h-1 bg-primary rounded-full mt-2 flex-shrink-0" />
                  {technique}
                </li>
              ))}
            </ul>
          </div>
          <div>
            <label className="text-sm font-medium text-foreground">과제 제안</label>
            <ul className="mt-2 space-y-1">
              {observationLog.nextSessionPlan.homework.map((hw, index) => (
                <li key={index} className="text-sm text-muted-foreground flex items-start gap-2">
                  <span className="w-1 h-1 bg-primary rounded-full mt-2 flex-shrink-0" />
                  {hw}
                </li>
              ))}
            </ul>
          </div>
        </div>
      </Card>

      {/* Clinical Impression */}
      <Card className="p-6 space-y-4">
        <h3 className="text-lg font-semibold text-foreground">임상적 인상 및 권고사항</h3>
        {editMode ? (
          <Textarea 
            value={observationLog.clinicalImpression}
            onChange={(e) => setObservationLog(prev => ({
              ...prev,
              clinicalImpression: e.target.value
            }))}
            rows={8}
          />
        ) : (
          <div className="text-sm text-muted-foreground whitespace-pre-wrap">
            {observationLog.clinicalImpression}
          </div>
        )}
      </Card>

      {/* AI Summary */}
      <Card className="p-6 space-y-4 bg-blue-50 border-blue-200">
        <h3 className="text-lg font-semibold text-blue-700 flex items-center gap-2">
          <Brain className="w-5 h-5" />
          AI 분석 요약
        </h3>
        <p className="text-sm text-blue-600">{observationLog.aiSummary}</p>
      </Card>
    </div>
  );
};

export default AutoObservationLog;