-- 3개의 새로운 제휴기관 추가
INSERT INTO public.partner_institutions (
  name, 
  institution_type, 
  address, 
  phone, 
  email, 
  services_offered, 
  specializations,
  partnership_status,
  website_url,
  description,
  established_year,
  total_experts,
  rating,
  review_count,
  created_at, 
  updated_at
) VALUES 
(
  '조이발달센터',
  'developmental_center',
  '경기도 용인시',
  '031-000-0000',
  'info@joy-development.co.kr',
  ARRAY['발달장애 아동 치료', '언어치료', '인지치료', '사회성 훈련'],
  ARRAY['자폐스펙트럼', 'ADHD', '언어발달지연', '사회성 장애'],
  'active',
  'https://naver.me/GbDqtqzO',
  '경기도 용인시에 위치한 전문 발달치료센터입니다.',
  2018,
  5,
  4.5,
  20,
  now(),
  now()
),
(
  '틔움통합발달센터 용인점',
  'developmental_center', 
  '경기도 용인시',
  '031-000-0001',
  'info@teuim-yongin.co.kr',
  ARRAY['통합발달치료', '언어치료', '작업치료', '놀이치료'],
  ARRAY['발달지연', '자폐스펙트럼', '감각처리장애', '학습장애'],
  'active',
  'https://naver.me/FjbaT9yi',
  '용인 지역 최고의 통합발달치료센터입니다.',
  2016,
  8,
  4.7,
  35,
  now(),
  now()
),
(
  '틔움사회서비스센터(장애인주간활동서비스)',
  'social_service_center',
  '경기도 용인시',
  '031-000-0002', 
  'info@teuim-social.co.kr',
  ARRAY['장애인주간활동서비스', '사회적응훈련', '일상생활훈련'],
  ARRAY['발달장애', '지적장애', '자폐성장애', '사회적응'],
  'active',
  'https://naver.me/5b0vJuUq',
  '장애인의 자립과 사회참여를 지원하는 전문기관입니다.',
  2020,
  12,
  4.8,
  28,
  now(),
  now()
);