// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybhvjfkpwjwyufaynuyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InliaHZqZmtwd2p3eXVmYXludXlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MDIzMzgsImV4cCI6MjA3MDk3ODMzOH0.4M3WUAzFYNqTOdUcFoaX1bd-HJF59H30tEYVFm2lHx8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});